/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addonsQueryAddon } from "../../funcs/addonsQueryAddon.js";
import { AddonFilter$zodSchema } from "../../models/addonfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AddonFilter$zodSchema,
};

export const tool$addonsQueryAddon: ToolDefinition<typeof args> = {
  name: "addons-query-addon",
  description: `Query addons

Use when listing or searching addons (e.g. catalog or subscription builder). Returns a paginated list; supports filtering and sorting.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await addonsQueryAddon(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
