/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addonsGetAddonsLookupLookupKey } from "../../funcs/addonsGetAddonsLookupLookupKey.js";
import { GetAddonsLookupLookupKeyRequest$zodSchema } from "../../models/getaddonslookuplookupkeyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAddonsLookupLookupKeyRequest$zodSchema,
};

export const tool$addonsGetAddonsLookupLookupKey: ToolDefinition<typeof args> =
  {
    name: "addons-get-addons-lookup-lookup-key",
    description: `Get addon by lookup key

Get an addon by lookup key`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await addonsGetAddonsLookupLookupKey(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
