/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addonsGetAddons } from "../../funcs/addonsGetAddons.js";
import { GetAddonsRequest$zodSchema } from "../../models/getaddonsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAddonsRequest$zodSchema.optional(),
};

export const tool$addonsGetAddons: ToolDefinition<typeof args> = {
  name: "addons-get-addons",
  description: `List addons

Get addons with optional filtering`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await addonsGetAddons(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
