/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addonsGetAddonsId } from "../../funcs/addonsGetAddonsId.js";
import { GetAddonsIdRequest$zodSchema } from "../../models/getaddonsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAddonsIdRequest$zodSchema,
};

export const tool$addonsGetAddonsId: ToolDefinition<typeof args> = {
  name: "addons-get-addons-id",
  description: `Get addon

Get an addon by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await addonsGetAddonsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
