/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addonsPostAddonsSearch } from "../../funcs/addonsPostAddonsSearch.js";
import { TypesAddonFilter$zodSchema } from "../../models/typesaddonfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesAddonFilter$zodSchema,
};

export const tool$addonsPostAddonsSearch: ToolDefinition<typeof args> = {
  name: "addons-post-addons-search",
  description: `List addons by filter

List addons by filter`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await addonsPostAddonsSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
