/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addonsDeleteAddonsId } from "../../funcs/addonsDeleteAddonsId.js";
import { DeleteAddonsIdRequest$zodSchema } from "../../models/deleteaddonsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteAddonsIdRequest$zodSchema,
};

export const tool$addonsDeleteAddonsId: ToolDefinition<typeof args> = {
  name: "addons-delete-addons-id",
  description: `Delete addon

Delete an addon`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await addonsDeleteAddonsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
