/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addonsPutAddonsId } from "../../funcs/addonsPutAddonsId.js";
import { PutAddonsIdRequest$zodSchema } from "../../models/putaddonsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutAddonsIdRequest$zodSchema,
};

export const tool$addonsPutAddonsId: ToolDefinition<typeof args> = {
  name: "addons-put-addons-id",
  description: `Update addon

Update an existing addon`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await addonsPutAddonsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
