/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { alertLogsPostAlertSearch } from "../../funcs/alertLogsPostAlertSearch.js";
import { TypesAlertLogFilter$zodSchema } from "../../models/typesalertlogfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesAlertLogFilter$zodSchema,
};

export const tool$alertLogsPostAlertSearch: ToolDefinition<typeof args> = {
  name: "alert-logs-post-alert-search",
  description: `List alert logs by filter

List alert logs by filter with optional expand for customer, wallet, and feature`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await alertLogsPostAlertSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
