/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authPostAuthSignup } from "../../funcs/authPostAuthSignup.js";
import { DtoSignUpRequest$zodSchema } from "../../models/dtosignuprequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoSignUpRequest$zodSchema,
};

export const tool$authPostAuthSignup: ToolDefinition<typeof args> = {
  name: "auth-post-auth-signup",
  description: `Sign up

Sign up a new user`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await authPostAuthSignup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
