/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectionsPostConnectionsSearch } from "../../funcs/connectionsPostConnectionsSearch.js";
import { TypesConnectionFilter$zodSchema } from "../../models/typesconnectionfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesConnectionFilter$zodSchema,
};

export const tool$connectionsPostConnectionsSearch: ToolDefinition<
  typeof args
> = {
  name: "connections-post-connections-search",
  description: `List connections by filter

List connections by filter`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await connectionsPostConnectionsSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
