/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectionsDeleteConnectionsId } from "../../funcs/connectionsDeleteConnectionsId.js";
import { DeleteConnectionsIdRequest$zodSchema } from "../../models/deleteconnectionsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteConnectionsIdRequest$zodSchema,
};

export const tool$connectionsDeleteConnectionsId: ToolDefinition<typeof args> =
  {
    name: "connections-delete-connections-id",
    description: `Delete a connection

Delete a connection by ID`,
    annotations: {
      "title": "",
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await connectionsDeleteConnectionsId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
