/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectionsPutConnectionsId } from "../../funcs/connectionsPutConnectionsId.js";
import { PutConnectionsIdRequest$zodSchema } from "../../models/putconnectionsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutConnectionsIdRequest$zodSchema,
};

export const tool$connectionsPutConnectionsId: ToolDefinition<typeof args> = {
  name: "connections-put-connections-id",
  description: `Update a connection

Update a connection by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await connectionsPutConnectionsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
