/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectionsGetConnections } from "../../funcs/connectionsGetConnections.js";
import { GetConnectionsRequest$zodSchema } from "../../models/getconnectionsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetConnectionsRequest$zodSchema.optional(),
};

export const tool$connectionsGetConnections: ToolDefinition<typeof args> = {
  name: "connections-get-connections",
  description: `Get connections

Get a list of connections`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await connectionsGetConnections(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
