/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsGetCostsId } from "../../funcs/costsGetCostsId.js";
import { GetCostsIdRequest$zodSchema } from "../../models/getcostsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCostsIdRequest$zodSchema,
};

export const tool$costsGetCostsId: ToolDefinition<typeof args> = {
  name: "costs-get-costs-id",
  description: `Get a costsheet by ID

Get a costsheet by ID with optional price expansion`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await costsGetCostsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
