/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsPutCostsId } from "../../funcs/costsPutCostsId.js";
import { PutCostsIdRequest$zodSchema } from "../../models/putcostsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutCostsIdRequest$zodSchema,
};

export const tool$costsPutCostsId: ToolDefinition<typeof args> = {
  name: "costs-put-costs-id",
  description: `Update a costsheet

Update a costsheet with the specified configuration`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await costsPutCostsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
