/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsDeleteCostsId } from "../../funcs/costsDeleteCostsId.js";
import { DeleteCostsIdRequest$zodSchema } from "../../models/deletecostsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteCostsIdRequest$zodSchema,
};

export const tool$costsDeleteCostsId: ToolDefinition<typeof args> = {
  name: "costs-delete-costs-id",
  description: `Delete a costsheet

Soft delete a costsheet by setting its status to deleted`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await costsDeleteCostsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
