/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsPostCostsAnalyticsV2 } from "../../funcs/costsPostCostsAnalyticsV2.js";
import { DtoGetCostAnalyticsRequest$zodSchema } from "../../models/dtogetcostanalyticsrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoGetCostAnalyticsRequest$zodSchema,
};

export const tool$costsPostCostsAnalyticsV2: ToolDefinition<typeof args> = {
  name: "costs-post-costs-analytics-v2",
  description: `Get combined revenue and cost analytics

Retrieve combined analytics with ROI, margin, and detailed breakdowns. If start_time and end_time are not provided, defaults to last 7 days.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await costsPostCostsAnalyticsV2(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
