/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { couponsDeleteCouponsId } from "../../funcs/couponsDeleteCouponsId.js";
import { DeleteCouponsIdRequest$zodSchema } from "../../models/deletecouponsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteCouponsIdRequest$zodSchema,
};

export const tool$couponsDeleteCouponsId: ToolDefinition<typeof args> = {
  name: "coupons-delete-coupons-id",
  description: `Delete a coupon

Deletes a coupon`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await couponsDeleteCouponsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
