/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { couponsGetCoupons } from "../../funcs/couponsGetCoupons.js";
import { GetCouponsRequest$zodSchema } from "../../models/getcouponsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCouponsRequest$zodSchema.optional(),
};

export const tool$couponsGetCoupons: ToolDefinition<typeof args> = {
  name: "coupons-get-coupons",
  description: `List coupons with filtering

Lists coupons with filtering`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await couponsGetCoupons(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
