/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { couponsGetCouponsId } from "../../funcs/couponsGetCouponsId.js";
import { GetCouponsIdRequest$zodSchema } from "../../models/getcouponsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCouponsIdRequest$zodSchema,
};

export const tool$couponsGetCouponsId: ToolDefinition<typeof args> = {
  name: "coupons-get-coupons-id",
  description: `Get a coupon by ID

Retrieves a coupon by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await couponsGetCouponsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
