/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { couponsPutCouponsId } from "../../funcs/couponsPutCouponsId.js";
import { PutCouponsIdRequest$zodSchema } from "../../models/putcouponsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutCouponsIdRequest$zodSchema,
};

export const tool$couponsPutCouponsId: ToolDefinition<typeof args> = {
  name: "coupons-put-coupons-id",
  description: `Update a coupon

Updates an existing coupon`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await couponsPutCouponsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
