/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditGrantsGetCreditgrants } from "../../funcs/creditGrantsGetCreditgrants.js";
import { GetCreditgrantsRequest$zodSchema } from "../../models/getcreditgrantsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCreditgrantsRequest$zodSchema.optional(),
};

export const tool$creditGrantsGetCreditgrants: ToolDefinition<typeof args> = {
  name: "credit-grants-get-creditgrants",
  description: `Get credit grants

Get credit grants with the specified filter`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await creditGrantsGetCreditgrants(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
