/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditNotesGetCreditnotes } from "../../funcs/creditNotesGetCreditnotes.js";
import { GetCreditnotesRequest$zodSchema } from "../../models/getcreditnotesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCreditnotesRequest$zodSchema.optional(),
};

export const tool$creditNotesGetCreditnotes: ToolDefinition<typeof args> = {
  name: "credit-notes-get-creditnotes",
  description: `List credit notes with filtering

Lists credit notes with filtering`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await creditNotesGetCreditnotes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
