/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditNotesPostCreditnotesIdFinalize } from "../../funcs/creditNotesPostCreditnotesIdFinalize.js";
import { PostCreditnotesIdFinalizeRequest$zodSchema } from "../../models/postcreditnotesidfinalizeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostCreditnotesIdFinalizeRequest$zodSchema,
};

export const tool$creditNotesPostCreditnotesIdFinalize: ToolDefinition<
  typeof args
> = {
  name: "credit-notes-post-creditnotes-id-finalize",
  description: `Process a draft credit note

Processes a draft credit note`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await creditNotesPostCreditnotesIdFinalize(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
