/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditNotesGetCreditnotesId } from "../../funcs/creditNotesGetCreditnotesId.js";
import { GetCreditnotesIdRequest$zodSchema } from "../../models/getcreditnotesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCreditnotesIdRequest$zodSchema,
};

export const tool$creditNotesGetCreditnotesId: ToolDefinition<typeof args> = {
  name: "credit-notes-get-creditnotes-id",
  description: `Get a credit note by ID

Retrieves a credit note by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await creditNotesGetCreditnotesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
