/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditGrantsDeleteCreditgrantsId } from "../../funcs/creditGrantsDeleteCreditgrantsId.js";
import { DeleteCreditgrantsIdRequest$zodSchema } from "../../models/deletecreditgrantsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteCreditgrantsIdRequest$zodSchema,
};

export const tool$creditGrantsDeleteCreditgrantsId: ToolDefinition<
  typeof args
> = {
  name: "credit-grants-delete-creditgrants-id",
  description: `Delete a credit grant

Delete a credit grant`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await creditGrantsDeleteCreditgrantsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
