/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditNotesPostCreditnotes } from "../../funcs/creditNotesPostCreditnotes.js";
import { DtoCreateCreditNoteRequest$zodSchema } from "../../models/dtocreatecreditnoterequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateCreditNoteRequest$zodSchema,
};

export const tool$creditNotesPostCreditnotes: ToolDefinition<typeof args> = {
  name: "credit-notes-post-creditnotes",
  description: `Create a new credit note

Creates a new credit note`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await creditNotesPostCreditnotes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
