/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersPostCustomersSearch } from "../../funcs/customersPostCustomersSearch.js";
import { TypesCustomerFilter$zodSchema } from "../../models/typescustomerfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesCustomerFilter$zodSchema,
};

export const tool$customersPostCustomersSearch: ToolDefinition<typeof args> = {
  name: "customers-post-customers-search",
  description: `List customers by filter

List customers by filter`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersPostCustomersSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
