/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetCustomersIdEntitlements } from "../../funcs/customersGetCustomersIdEntitlements.js";
import { GetCustomersIdEntitlementsRequest$zodSchema } from "../../models/getcustomersidentitlementsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomersIdEntitlementsRequest$zodSchema,
};

export const tool$customersGetCustomersIdEntitlements: ToolDefinition<
  typeof args
> = {
  name: "customers-get-customers-id-entitlements",
  description: `Get customer entitlements

Get customer entitlements`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersGetCustomersIdEntitlements(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
