/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetCustomersExternalExternalId } from "../../funcs/customersGetCustomersExternalExternalId.js";
import { GetCustomersExternalExternalIdRequest$zodSchema } from "../../models/getcustomersexternalexternalidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomersExternalExternalIdRequest$zodSchema,
};

export const tool$customersGetCustomersExternalExternalId: ToolDefinition<
  typeof args
> = {
  name: "customers-get-customers-external-external-id",
  description: `Get a customer by external id

Get a customer by external id`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersGetCustomersExternalExternalId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
