/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersDeleteCustomersId } from "../../funcs/customersDeleteCustomersId.js";
import { DeleteCustomersIdRequest$zodSchema } from "../../models/deletecustomersidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteCustomersIdRequest$zodSchema,
};

export const tool$customersDeleteCustomersId: ToolDefinition<typeof args> = {
  name: "customers-delete-customers-id",
  description: `Delete a customer

Delete a customer`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersDeleteCustomersId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
