/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetCustomers } from "../../funcs/customersGetCustomers.js";
import { GetCustomersRequest$zodSchema } from "../../models/getcustomersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomersRequest$zodSchema.optional(),
};

export const tool$customersGetCustomers: ToolDefinition<typeof args> = {
  name: "customers-get-customers",
  description: `Get customers

Get customers`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersGetCustomers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
