/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetCustomersIdGrantsUpcoming } from "../../funcs/customersGetCustomersIdGrantsUpcoming.js";
import { GetCustomersIdGrantsUpcomingRequest$zodSchema } from "../../models/getcustomersidgrantsupcomingop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomersIdGrantsUpcomingRequest$zodSchema,
};

export const tool$customersGetCustomersIdGrantsUpcoming: ToolDefinition<
  typeof args
> = {
  name: "customers-get-customers-id-grants-upcoming",
  description: `Get upcoming credit grant applications

Get upcoming credit grant applications for a customer`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersGetCustomersIdGrantsUpcoming(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
