/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customerPortalGetPortalExternalId } from "../../funcs/customerPortalGetPortalExternalId.js";
import { GetPortalExternalIdRequest$zodSchema } from "../../models/getportalexternalidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPortalExternalIdRequest$zodSchema,
};

export const tool$customerPortalGetPortalExternalId: ToolDefinition<
  typeof args
> = {
  name: "customer-portal-get-portal-external-id",
  description: `Create a customer portal session

Generate a dashboard URL/token for a customer to access their billing information`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customerPortalGetPortalExternalId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
