/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetCustomersUsage } from "../../funcs/customersGetCustomersUsage.js";
import { GetCustomersUsageRequest$zodSchema } from "../../models/getcustomersusageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomersUsageRequest$zodSchema.optional(),
};

export const tool$customersGetCustomersUsage: ToolDefinition<typeof args> = {
  name: "customers-get-customers-usage",
  description: `Get customer usage summary

Get customer usage summary by customer_id or customer_lookup_key (external_customer_id)`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersGetCustomersUsage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
