/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsDeleteEntitlementsId } from "../../funcs/entitlementsDeleteEntitlementsId.js";
import { DeleteEntitlementsIdRequest$zodSchema } from "../../models/deleteentitlementsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteEntitlementsIdRequest$zodSchema,
};

export const tool$entitlementsDeleteEntitlementsId: ToolDefinition<
  typeof args
> = {
  name: "entitlements-delete-entitlements-id",
  description: `Delete an entitlement

Delete an entitlement`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await entitlementsDeleteEntitlementsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
