/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsGetAddonsIdEntitlements } from "../../funcs/entitlementsGetAddonsIdEntitlements.js";
import { GetAddonsIdEntitlementsRequest$zodSchema } from "../../models/getaddonsidentitlementsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAddonsIdEntitlementsRequest$zodSchema,
};

export const tool$entitlementsGetAddonsIdEntitlements: ToolDefinition<
  typeof args
> = {
  name: "entitlements-get-addons-id-entitlements",
  description: `Get addon entitlements

Get all entitlements for an addon`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await entitlementsGetAddonsIdEntitlements(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
