/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entityIntegrationMappingsPostEntityIntegrationMappings } from "../../funcs/entityIntegrationMappingsPostEntityIntegrationMappings.js";
import { DtoCreateEntityIntegrationMappingRequest$zodSchema } from "../../models/dtocreateentityintegrationmappingrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateEntityIntegrationMappingRequest$zodSchema,
};

export const tool$entityIntegrationMappingsPostEntityIntegrationMappings:
  ToolDefinition<typeof args> = {
    name: "entity-integration-mappings-post-entity-bde",
    description: `Create entity integration mapping

Create a new entity integration mapping`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await entityIntegrationMappingsPostEntityIntegrationMappings(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
