/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsPostEntitlementsBulk } from "../../funcs/entitlementsPostEntitlementsBulk.js";
import { DtoCreateBulkEntitlementRequest$zodSchema } from "../../models/dtocreatebulkentitlementrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateBulkEntitlementRequest$zodSchema,
};

export const tool$entitlementsPostEntitlementsBulk: ToolDefinition<
  typeof args
> = {
  name: "entitlements-post-entitlements-bulk",
  description: `Create multiple entitlements in bulk

Create multiple entitlements with the specified configurations`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await entitlementsPostEntitlementsBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
