/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsPostEntitlementsSearch } from "../../funcs/entitlementsPostEntitlementsSearch.js";
import { TypesEntitlementFilter$zodSchema } from "../../models/typesentitlementfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesEntitlementFilter$zodSchema,
};

export const tool$entitlementsPostEntitlementsSearch: ToolDefinition<
  typeof args
> = {
  name: "entitlements-post-entitlements-search",
  description: `List entitlements by filter

List entitlements by filter`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await entitlementsPostEntitlementsSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
