/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsGetPlansIdEntitlements } from "../../funcs/entitlementsGetPlansIdEntitlements.js";
import { GetPlansIdEntitlementsRequest$zodSchema } from "../../models/getplansidentitlementsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPlansIdEntitlementsRequest$zodSchema,
};

export const tool$entitlementsGetPlansIdEntitlements: ToolDefinition<
  typeof args
> = {
  name: "entitlements-get-plans-id-entitlements",
  description: `Get plan entitlements

Get all entitlements for a plan`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await entitlementsGetPlansIdEntitlements(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
