/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entityIntegrationMappingsDeleteEntityIntegrationMappingsId } from "../../funcs/entityIntegrationMappingsDeleteEntityIntegrationMappingsId.js";
import { DeleteEntityIntegrationMappingsIdRequest$zodSchema } from "../../models/deleteentityintegrationmappingsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteEntityIntegrationMappingsIdRequest$zodSchema,
};

export const tool$entityIntegrationMappingsDeleteEntityIntegrationMappingsId:
  ToolDefinition<typeof args> = {
    name: "entity-integration-mappings-delete-entity-2b7",
    description: `Delete entity integration mapping

Delete an entity integration mapping`,
    annotations: {
      "title": "",
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await entityIntegrationMappingsDeleteEntityIntegrationMappingsId(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
