/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsPostEntitlements } from "../../funcs/entitlementsPostEntitlements.js";
import { DtoCreateEntitlementRequest$zodSchema } from "../../models/dtocreateentitlementrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateEntitlementRequest$zodSchema,
};

export const tool$entitlementsPostEntitlements: ToolDefinition<typeof args> = {
  name: "entitlements-post-entitlements",
  description: `Create a new entitlement

Create a new entitlement with the specified configuration`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await entitlementsPostEntitlements(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
