/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsPutEnvironmentsId } from "../../funcs/environmentsPutEnvironmentsId.js";
import { PutEnvironmentsIdRequest$zodSchema } from "../../models/putenvironmentsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutEnvironmentsIdRequest$zodSchema,
};

export const tool$environmentsPutEnvironmentsId: ToolDefinition<typeof args> = {
  name: "environments-put-environments-id",
  description: `Update an environment

Update an environment`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await environmentsPutEnvironmentsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
