/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsGetEnvironmentsId } from "../../funcs/environmentsGetEnvironmentsId.js";
import { GetEnvironmentsIdRequest$zodSchema } from "../../models/getenvironmentsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEnvironmentsIdRequest$zodSchema,
};

export const tool$environmentsGetEnvironmentsId: ToolDefinition<typeof args> = {
  name: "environments-get-environments-id",
  description: `Get an environment

Get an environment`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await environmentsGetEnvironmentsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
