/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsPostEventsBulk } from "../../funcs/eventsPostEventsBulk.js";
import { DtoBulkIngestEventRequest$zodSchema } from "../../models/dtobulkingesteventrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoBulkIngestEventRequest$zodSchema,
};

export const tool$eventsPostEventsBulk: ToolDefinition<typeof args> = {
  name: "events-post-events-bulk",
  description: `Bulk Ingest events

Ingest bulk events into the system`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsPostEventsBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
