/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetEventsMonitoring } from "../../funcs/eventsGetEventsMonitoring.js";
import { GetEventsMonitoringRequest$zodSchema } from "../../models/geteventsmonitoringop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEventsMonitoringRequest$zodSchema.optional(),
};

export const tool$eventsGetEventsMonitoring: ToolDefinition<typeof args> = {
  name: "events-get-events-monitoring",
  description: `Get monitoring data

Retrieve monitoring data for events including consumer lag and event metrics (last 24 hours by default)`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsGetEventsMonitoring(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
