/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsPostEvents } from "../../funcs/eventsPostEvents.js";
import { DtoIngestEventRequest$zodSchema } from "../../models/dtoingesteventrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoIngestEventRequest$zodSchema,
};

export const tool$eventsPostEvents: ToolDefinition<typeof args> = {
  name: "events-post-events",
  description: `Ingest event

Ingest a new event into the system`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsPostEvents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
