/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsPostEventsHuggingfaceInference } from "../../funcs/eventsPostEventsHuggingfaceInference.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$eventsPostEventsHuggingfaceInference: ToolDefinition = {
  name: "events-post-events-huggingface-inference",
  description: `Get hugging face inference data

Retrieve hugging face inference data for events`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result] = await eventsPostEventsHuggingfaceInference(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
