/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { eventsPostEventsUsage } from "../../funcs/eventsPostEventsUsage.js";
import * as b64$ from "../../lib/base64.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
};

export const tool$eventsPostEventsUsage: ToolDefinition<typeof args> = {
  name: "events-post-events-usage",
  description: `Get usage statistics

Retrieve aggregated usage statistics for events`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsPostEventsUsage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
