/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresPostFeatures } from "../../funcs/featuresPostFeatures.js";
import { DtoCreateFeatureRequest$zodSchema } from "../../models/dtocreatefeaturerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateFeatureRequest$zodSchema,
};

export const tool$featuresPostFeatures: ToolDefinition<typeof args> = {
  name: "features-post-features",
  description: `Create a new feature

Create a new feature`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await featuresPostFeatures(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
