/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresGetFeaturesId } from "../../funcs/featuresGetFeaturesId.js";
import { GetFeaturesIdRequest$zodSchema } from "../../models/getfeaturesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetFeaturesIdRequest$zodSchema,
};

export const tool$featuresGetFeaturesId: ToolDefinition<typeof args> = {
  name: "features-get-features-id",
  description: `Get a feature by ID

Get a feature by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await featuresGetFeaturesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
