/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresDeleteFeaturesId } from "../../funcs/featuresDeleteFeaturesId.js";
import { DeleteFeaturesIdRequest$zodSchema } from "../../models/deletefeaturesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteFeaturesIdRequest$zodSchema,
};

export const tool$featuresDeleteFeaturesId: ToolDefinition<typeof args> = {
  name: "features-delete-features-id",
  description: `Delete a feature

Delete a feature by ID`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await featuresDeleteFeaturesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
