/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresGetFeatures } from "../../funcs/featuresGetFeatures.js";
import { GetFeaturesRequest$zodSchema } from "../../models/getfeaturesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetFeaturesRequest$zodSchema.optional(),
};

export const tool$featuresGetFeatures: ToolDefinition<typeof args> = {
  name: "features-get-features",
  description: `List features

List features with optional filtering`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await featuresGetFeatures(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
