/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsPostGroups } from "../../funcs/groupsPostGroups.js";
import { DtoCreateGroupRequest$zodSchema } from "../../models/dtocreategrouprequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateGroupRequest$zodSchema,
};

export const tool$groupsPostGroups: ToolDefinition<typeof args> = {
  name: "groups-post-groups",
  description: `Create a group

Create a new group for organizing entities (prices, plans, customers, etc.)`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await groupsPostGroups(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
