/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsPostGroupsSearch } from "../../funcs/groupsPostGroupsSearch.js";
import { PostGroupsSearchRequest$zodSchema } from "../../models/postgroupssearchop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostGroupsSearchRequest$zodSchema.optional(),
};

export const tool$groupsPostGroupsSearch: ToolDefinition<typeof args> = {
  name: "groups-post-groups-search",
  description: `Get groups

Get groups with optional filtering via query parameters`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await groupsPostGroupsSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
