/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsGetGroupsId } from "../../funcs/groupsGetGroupsId.js";
import { GetGroupsIdRequest$zodSchema } from "../../models/getgroupsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetGroupsIdRequest$zodSchema,
};

export const tool$groupsGetGroupsId: ToolDefinition<typeof args> = {
  name: "groups-get-groups-id",
  description: `Get a group

Get a group by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await groupsGetGroupsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
