/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsGetSecretsIntegrationsLinked } from "../../funcs/integrationsGetSecretsIntegrationsLinked.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$integrationsGetSecretsIntegrationsLinked: ToolDefinition = {
  name: "integrations-get-secrets-integrations-linked",
  description: `List linked integrations

Get a list of unique providers which have a valid linked integration secret`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await integrationsGetSecretsIntegrationsLinked(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
