/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsDeleteSecretsIntegrationsId } from "../../funcs/integrationsDeleteSecretsIntegrationsId.js";
import { DeleteSecretsIntegrationsIdRequest$zodSchema } from "../../models/deletesecretsintegrationsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteSecretsIntegrationsIdRequest$zodSchema,
};

export const tool$integrationsDeleteSecretsIntegrationsId: ToolDefinition<
  typeof args
> = {
  name: "integrations-delete-secrets-integrations-id",
  description: `Delete an integration

Delete integration credentials`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await integrationsDeleteSecretsIntegrationsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
