/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesPostInvoicesIdPaymentAttempt } from "../../funcs/invoicesPostInvoicesIdPaymentAttempt.js";
import { PostInvoicesIdPaymentAttemptRequest$zodSchema } from "../../models/postinvoicesidpaymentattemptop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostInvoicesIdPaymentAttemptRequest$zodSchema,
};

export const tool$invoicesPostInvoicesIdPaymentAttempt: ToolDefinition<
  typeof args
> = {
  name: "invoices-post-invoices-id-payment-attempt",
  description: `Attempt payment for an invoice

Attempt to pay an invoice using customer's available wallets`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesPostInvoicesIdPaymentAttempt(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
