/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesPutInvoicesId } from "../../funcs/invoicesPutInvoicesId.js";
import { PutInvoicesIdRequest$zodSchema } from "../../models/putinvoicesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutInvoicesIdRequest$zodSchema,
};

export const tool$invoicesPutInvoicesId: ToolDefinition<typeof args> = {
  name: "invoices-put-invoices-id",
  description: `Update an invoice

Update invoice details like PDF URL and due date.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesPutInvoicesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
