/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesPutInvoicesIdPayment } from "../../funcs/invoicesPutInvoicesIdPayment.js";
import { PutInvoicesIdPaymentRequest$zodSchema } from "../../models/putinvoicesidpaymentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutInvoicesIdPaymentRequest$zodSchema,
};

export const tool$invoicesPutInvoicesIdPayment: ToolDefinition<typeof args> = {
  name: "invoices-put-invoices-id-payment",
  description: `Update invoice payment status

Update the payment status of an invoice`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesPutInvoicesIdPayment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
