/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesGetInvoicesId } from "../../funcs/invoicesGetInvoicesId.js";
import { GetInvoicesIdRequest$zodSchema } from "../../models/getinvoicesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInvoicesIdRequest$zodSchema,
};

export const tool$invoicesGetInvoicesId: ToolDefinition<typeof args> = {
  name: "invoices-get-invoices-id",
  description: `Get an invoice by ID

Get detailed information about an invoice`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesGetInvoicesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
