/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesPostInvoicesIdCommsTrigger } from "../../funcs/invoicesPostInvoicesIdCommsTrigger.js";
import { PostInvoicesIdCommsTriggerRequest$zodSchema } from "../../models/postinvoicesidcommstriggerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostInvoicesIdCommsTriggerRequest$zodSchema,
};

export const tool$invoicesPostInvoicesIdCommsTrigger: ToolDefinition<
  typeof args
> = {
  name: "invoices-post-invoices-id-comms-trigger",
  description: `Trigger communication webhook for an invoice

Triggers a communication webhook event containing all information about the invoice`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesPostInvoicesIdCommsTrigger(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
