/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesGetCustomersIdInvoicesSummary } from "../../funcs/invoicesGetCustomersIdInvoicesSummary.js";
import { GetCustomersIdInvoicesSummaryRequest$zodSchema } from "../../models/getcustomersidinvoicessummaryop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomersIdInvoicesSummaryRequest$zodSchema,
};

export const tool$invoicesGetCustomersIdInvoicesSummary: ToolDefinition<
  typeof args
> = {
  name: "invoices-get-customers-id-invoices-summary",
  description: `Get a customer invoice summary

Get a customer invoice summary`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesGetCustomersIdInvoicesSummary(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
