/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesPostInvoices } from "../../funcs/invoicesPostInvoices.js";
import { DtoCreateInvoiceRequest$zodSchema } from "../../models/dtocreateinvoicerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateInvoiceRequest$zodSchema,
};

export const tool$invoicesPostInvoices: ToolDefinition<typeof args> = {
  name: "invoices-post-invoices",
  description: `Create a new one off invoice

Create a new one off invoice with the provided details`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesPostInvoices(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
