/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesPostInvoicesPreview } from "../../funcs/invoicesPostInvoicesPreview.js";
import { DtoGetPreviewInvoiceRequest$zodSchema } from "../../models/dtogetpreviewinvoicerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoGetPreviewInvoiceRequest$zodSchema,
};

export const tool$invoicesPostInvoicesPreview: ToolDefinition<typeof args> = {
  name: "invoices-post-invoices-preview",
  description: `Get a preview invoice

Get a preview invoice`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesPostInvoicesPreview(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
