/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesGetInvoicesIdPdf } from "../../funcs/invoicesGetInvoicesIdPdf.js";
import { GetInvoicesIdPdfRequest$zodSchema } from "../../models/getinvoicesidpdfop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInvoicesIdPdfRequest$zodSchema,
};

export const tool$invoicesGetInvoicesIdPdf: ToolDefinition<typeof args> = {
  name: "invoices-get-invoices-id-pdf",
  description: `Get PDF for an invoice

Retrieve the PDF document for a specific invoice by its ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesGetInvoicesIdPdf(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
