/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesGetInvoices } from "../../funcs/invoicesGetInvoices.js";
import { GetInvoicesRequest$zodSchema } from "../../models/getinvoicesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInvoicesRequest$zodSchema.optional(),
};

export const tool$invoicesGetInvoices: ToolDefinition<typeof args> = {
  name: "invoices-get-invoices",
  description: `List invoices

List invoices with optional filtering`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesGetInvoices(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
