/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsGetPayments } from "../../funcs/paymentsGetPayments.js";
import { GetPaymentsRequest$zodSchema } from "../../models/getpaymentsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPaymentsRequest$zodSchema.optional(),
};

export const tool$paymentsGetPayments: ToolDefinition<typeof args> = {
  name: "payments-get-payments",
  description: `List payments

List payments with the specified filter`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await paymentsGetPayments(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
