/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsPostPayments } from "../../funcs/paymentsPostPayments.js";
import { DtoCreatePaymentRequest$zodSchema } from "../../models/dtocreatepaymentrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreatePaymentRequest$zodSchema,
};

export const tool$paymentsPostPayments: ToolDefinition<typeof args> = {
  name: "payments-post-payments",
  description: `Create a new payment

Create a new payment with the specified configuration`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await paymentsPostPayments(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
