/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansPostPlans } from "../../funcs/plansPostPlans.js";
import { DtoCreatePlanRequest$zodSchema } from "../../models/dtocreateplanrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreatePlanRequest$zodSchema,
};

export const tool$plansPostPlans: ToolDefinition<typeof args> = {
  name: "plans-post-plans",
  description: `Create a new plan

Create a new plan with the specified configuration`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansPostPlans(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
