/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansPutPlansId } from "../../funcs/plansPutPlansId.js";
import { PutPlansIdRequest$zodSchema } from "../../models/putplansidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutPlansIdRequest$zodSchema,
};

export const tool$plansPutPlansId: ToolDefinition<typeof args> = {
  name: "plans-put-plans-id",
  description: `Update a plan

Update a plan by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansPutPlansId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
