/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansGetPlansId } from "../../funcs/plansGetPlansId.js";
import { GetPlansIdRequest$zodSchema } from "../../models/getplansidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPlansIdRequest$zodSchema,
};

export const tool$plansGetPlansId: ToolDefinition<typeof args> = {
  name: "plans-get-plans-id",
  description: `Get a plan

Get a plan by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansGetPlansId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
