/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansGetPlans } from "../../funcs/plansGetPlans.js";
import { GetPlansRequest$zodSchema } from "../../models/getplansop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPlansRequest$zodSchema.optional(),
};

export const tool$plansGetPlans: ToolDefinition<typeof args> = {
  name: "plans-get-plans",
  description: `Get plans

Get plans with optional filtering`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansGetPlans(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
