/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansDeletePlansId } from "../../funcs/plansDeletePlansId.js";
import { DeletePlansIdRequest$zodSchema } from "../../models/deleteplansidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeletePlansIdRequest$zodSchema,
};

export const tool$plansDeletePlansId: ToolDefinition<typeof args> = {
  name: "plans-delete-plans-id",
  description: `Delete a plan

Delete a plan by ID`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansDeletePlansId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
