/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansPostPlansIdSyncSubscriptions } from "../../funcs/plansPostPlansIdSyncSubscriptions.js";
import { PostPlansIdSyncSubscriptionsRequest$zodSchema } from "../../models/postplansidsyncsubscriptionsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostPlansIdSyncSubscriptionsRequest$zodSchema,
};

export const tool$plansPostPlansIdSyncSubscriptions: ToolDefinition<
  typeof args
> = {
  name: "plans-post-plans-id-sync-subscriptions",
  description: `Synchronize plan prices

Synchronize current plan prices with all existing active subscriptions`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansPostPlansIdSyncSubscriptions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
