/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansPostPlansSearch } from "../../funcs/plansPostPlansSearch.js";
import { TypesPlanFilter$zodSchema } from "../../models/typesplanfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesPlanFilter$zodSchema,
};

export const tool$plansPostPlansSearch: ToolDefinition<typeof args> = {
  name: "plans-post-plans-search",
  description: `List plans by filter

List plans by filter`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansPostPlansSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
