/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pricesDeletePricesId } from "../../funcs/pricesDeletePricesId.js";
import { DeletePricesIdRequest$zodSchema } from "../../models/deletepricesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeletePricesIdRequest$zodSchema,
};

export const tool$pricesDeletePricesId: ToolDefinition<typeof args> = {
  name: "prices-delete-prices-id",
  description: `Delete a price

Delete a price`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await pricesDeletePricesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
