/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pricesPutPricesId } from "../../funcs/pricesPutPricesId.js";
import { PutPricesIdRequest$zodSchema } from "../../models/putpricesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutPricesIdRequest$zodSchema,
};

export const tool$pricesPutPricesId: ToolDefinition<typeof args> = {
  name: "prices-put-prices-id",
  description: `Update a price

Update a price with the specified configuration`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await pricesPutPricesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
