/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { priceUnitsGetPricesUnits } from "../../funcs/priceUnitsGetPricesUnits.js";
import { GetPricesUnitsRequest$zodSchema } from "../../models/getpricesunitsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPricesUnitsRequest$zodSchema.optional(),
};

export const tool$priceUnitsGetPricesUnits: ToolDefinition<typeof args> = {
  name: "price-units-get-prices-units",
  description: `List price units

Get a paginated list of price units with optional filtering`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await priceUnitsGetPricesUnits(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
