/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { priceUnitsPostPricesUnits } from "../../funcs/priceUnitsPostPricesUnits.js";
import { DtoCreatePriceUnitRequest$zodSchema } from "../../models/dtocreatepriceunitrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreatePriceUnitRequest$zodSchema,
};

export const tool$priceUnitsPostPricesUnits: ToolDefinition<typeof args> = {
  name: "price-units-post-prices-units",
  description: `Create a new price unit

Create a new price unit with the provided details`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await priceUnitsPostPricesUnits(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
