/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { priceUnitsGetPricesUnitsCodeCode } from "../../funcs/priceUnitsGetPricesUnitsCodeCode.js";
import { GetPricesUnitsCodeCodeRequest$zodSchema } from "../../models/getpricesunitscodecodeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPricesUnitsCodeCodeRequest$zodSchema,
};

export const tool$priceUnitsGetPricesUnitsCodeCode: ToolDefinition<
  typeof args
> = {
  name: "price-units-get-prices-units-code-code",
  description: `Get a price unit by code

Get a price unit by code`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await priceUnitsGetPricesUnitsCodeCode(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
