/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { priceUnitsGetPricesUnitsId } from "../../funcs/priceUnitsGetPricesUnitsId.js";
import { GetPricesUnitsIdRequest$zodSchema } from "../../models/getpricesunitsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPricesUnitsIdRequest$zodSchema,
};

export const tool$priceUnitsGetPricesUnitsId: ToolDefinition<typeof args> = {
  name: "price-units-get-prices-units-id",
  description: `Get a price unit by ID

Get a price unit by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await priceUnitsGetPricesUnitsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
