/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pricesPostPrices } from "../../funcs/pricesPostPrices.js";
import { DtoCreatePriceRequest$zodSchema } from "../../models/dtocreatepricerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreatePriceRequest$zodSchema,
};

export const tool$pricesPostPrices: ToolDefinition<typeof args> = {
  name: "prices-post-prices",
  description: `Create a new price

Create a new price with the specified configuration. Supports both regular and price unit configurations.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await pricesPostPrices(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
