/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pricesGetPricesId } from "../../funcs/pricesGetPricesId.js";
import { GetPricesIdRequest$zodSchema } from "../../models/getpricesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPricesIdRequest$zodSchema,
};

export const tool$pricesGetPricesId: ToolDefinition<typeof args> = {
  name: "prices-get-prices-id",
  description: `Get a price by ID

Get a price by ID with expanded meter and price unit information`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await pricesGetPricesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
