/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { priceUnitsPutPricesUnitsId } from "../../funcs/priceUnitsPutPricesUnitsId.js";
import { PutPricesUnitsIdRequest$zodSchema } from "../../models/putpricesunitsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutPricesUnitsIdRequest$zodSchema,
};

export const tool$priceUnitsPutPricesUnitsId: ToolDefinition<typeof args> = {
  name: "price-units-put-prices-units-id",
  description: `Update a price unit

Update an existing price unit with the provided details. Only name and metadata can be updated.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await priceUnitsPutPricesUnitsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
