/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pricesPostPricesBulk } from "../../funcs/pricesPostPricesBulk.js";
import { DtoCreateBulkPriceRequest$zodSchema } from "../../models/dtocreatebulkpricerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateBulkPriceRequest$zodSchema,
};

export const tool$pricesPostPricesBulk: ToolDefinition<typeof args> = {
  name: "prices-post-prices-bulk",
  description: `Create multiple prices in bulk

Create multiple prices with the specified configurations. Supports both regular and price unit configurations.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await pricesPostPricesBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
