/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { priceUnitsDeletePricesUnitsId } from "../../funcs/priceUnitsDeletePricesUnitsId.js";
import { DeletePricesUnitsIdRequest$zodSchema } from "../../models/deletepricesunitsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeletePricesUnitsIdRequest$zodSchema,
};

export const tool$priceUnitsDeletePricesUnitsId: ToolDefinition<typeof args> = {
  name: "price-units-delete-prices-units-id",
  description: `Delete a price unit

Delete an existing price unit.`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await priceUnitsDeletePricesUnitsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
