/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rbacGetRBACRolesId } from "../../funcs/rbacGetRBACRolesId.js";
import { GetRbacRolesIdRequest$zodSchema } from "../../models/getrbacrolesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetRbacRolesIdRequest$zodSchema,
};

export const tool$rbacGetRBACRolesId: ToolDefinition<typeof args> = {
  name: "rbac-get-rbac-roles-id",
  description: `Get a specific RBAC role

Returns details of a specific role including permissions, name, and description`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await rbacGetRBACRolesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
