/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rbacGetRBACRoles } from "../../funcs/rbacGetRBACRoles.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$rbacGetRBACRoles: ToolDefinition = {
  name: "rbac-get-rbac-roles",
  description: `List all RBAC roles

Returns all available roles with their permissions, names, and descriptions`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await rbacGetRBACRoles(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
