/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledTasksDeleteTasksScheduledId } from "../../funcs/scheduledTasksDeleteTasksScheduledId.js";
import { DeleteTasksScheduledIdRequest$zodSchema } from "../../models/deletetasksscheduledidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteTasksScheduledIdRequest$zodSchema,
};

export const tool$scheduledTasksDeleteTasksScheduledId: ToolDefinition<
  typeof args
> = {
  name: "scheduled-tasks-delete-tasks-scheduled-id",
  description: `Delete a scheduled task

Archive a scheduled task by ID (soft delete) - Sets status to archived and deletes from Temporal`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await scheduledTasksDeleteTasksScheduledId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
