/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledTasksPostTasksScheduledIdRun } from "../../funcs/scheduledTasksPostTasksScheduledIdRun.js";
import { PostTasksScheduledIdRunRequest$zodSchema } from "../../models/posttasksscheduledidrunop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostTasksScheduledIdRunRequest$zodSchema,
};

export const tool$scheduledTasksPostTasksScheduledIdRun: ToolDefinition<
  typeof args
> = {
  name: "scheduled-tasks-post-tasks-scheduled-id-run",
  description: `Trigger force run

Trigger a force run export immediately for a scheduled task with optional custom time range`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await scheduledTasksPostTasksScheduledIdRun(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
