/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledTasksPostTasksScheduledScheduleUpdateBillingPeriod } from "../../funcs/scheduledTasksPostTasksScheduledScheduleUpdateBillingPeriod.js";
import { PostTasksScheduledScheduleUpdateBillingPeriodRequest$zodSchema } from "../../models/posttasksscheduledscheduleupdatebillingperiodop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostTasksScheduledScheduleUpdateBillingPeriodRequest$zodSchema,
};

export const tool$scheduledTasksPostTasksScheduledScheduleUpdateBillingPeriod:
  ToolDefinition<typeof args> = {
    name: "scheduled-tasks-post-tasks-scheduled-schedule-e95",
    description: `Schedule update billing period

Schedule an update billing period workflow`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await scheduledTasksPostTasksScheduledScheduleUpdateBillingPeriod(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
