/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledTasksGetTasksScheduledId } from "../../funcs/scheduledTasksGetTasksScheduledId.js";
import { GetTasksScheduledIdRequest$zodSchema } from "../../models/gettasksscheduledidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTasksScheduledIdRequest$zodSchema,
};

export const tool$scheduledTasksGetTasksScheduledId: ToolDefinition<
  typeof args
> = {
  name: "scheduled-tasks-get-tasks-scheduled-id",
  description: `Get a scheduled task

Get a scheduled task by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await scheduledTasksGetTasksScheduledId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
