/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { secretsPostSecretsApiKeys } from "../../funcs/secretsPostSecretsApiKeys.js";
import { DtoCreateAPIKeyRequest$zodSchema } from "../../models/dtocreateapikeyrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateAPIKeyRequest$zodSchema,
};

export const tool$secretsPostSecretsApiKeys: ToolDefinition<typeof args> = {
  name: "secrets-post-secrets-api-keys",
  description: `Create a new API key

Create a new API key. Provide 'service_account_id' in body to create API key for a service account, otherwise creates for authenticated user.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await secretsPostSecretsApiKeys(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
