/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetSubscriptionsIdAddonsAssociations } from "../../funcs/subscriptionsGetSubscriptionsIdAddonsAssociations.js";
import { GetSubscriptionsIdAddonsAssociationsRequest$zodSchema } from "../../models/getsubscriptionsidaddonsassociationsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSubscriptionsIdAddonsAssociationsRequest$zodSchema,
};

export const tool$subscriptionsGetSubscriptionsIdAddonsAssociations:
  ToolDefinition<typeof args> = {
    name: "subscriptions-get-subscriptions-id-addons-75b",
    description: `Get active addon associations

Get active addon associations for a subscription`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await subscriptionsGetSubscriptionsIdAddonsAssociations(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
