/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsPostSubscriptionsIdActivate } from "../../funcs/subscriptionsPostSubscriptionsIdActivate.js";
import { PostSubscriptionsIdActivateRequest$zodSchema } from "../../models/postsubscriptionsidactivateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostSubscriptionsIdActivateRequest$zodSchema,
};

export const tool$subscriptionsPostSubscriptionsIdActivate: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-post-subscriptions-id-activate",
  description: `Activate draft subscription

Activate a draft subscription with a new start date`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsPostSubscriptionsIdActivate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
