/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsPostSubscriptionsAddon } from "../../funcs/subscriptionsPostSubscriptionsAddon.js";
import { DtoAddAddonRequest$zodSchema } from "../../models/dtoaddaddonrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoAddAddonRequest$zodSchema,
};

export const tool$subscriptionsPostSubscriptionsAddon: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-post-subscriptions-addon",
  description: `Add addon to subscription

Add an addon to a subscription`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsPostSubscriptionsAddon(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
