/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetV1SubscriptionSchedules } from "../../funcs/subscriptionsGetV1SubscriptionSchedules.js";
import { GetV1SubscriptionSchedulesRequest$zodSchema } from "../../models/getv1subscriptionschedulesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1SubscriptionSchedulesRequest$zodSchema.optional(),
};

export const tool$subscriptionsGetV1SubscriptionSchedules: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-get-v1-subscription-schedules",
  description: `List all subscription schedules

Retrieves subscription schedules with optional filtering`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsGetV1SubscriptionSchedules(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
