/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetV1SubscriptionsSubscriptionIdSchedules } from "../../funcs/subscriptionsGetV1SubscriptionsSubscriptionIdSchedules.js";
import { GetV1SubscriptionsSubscriptionIdSchedulesRequest$zodSchema } from "../../models/getv1subscriptionssubscriptionidschedulesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1SubscriptionsSubscriptionIdSchedulesRequest$zodSchema,
};

export const tool$subscriptionsGetV1SubscriptionsSubscriptionIdSchedules:
  ToolDefinition<typeof args> = {
    name: "subscriptions-get-v1-subscriptions-subscription-a4b",
    description: `List subscription schedules

Retrieves all schedules for a specific subscription`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await subscriptionsGetV1SubscriptionsSubscriptionIdSchedules(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
