/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsPostSubscriptionsIdChangeExecute } from "../../funcs/subscriptionsPostSubscriptionsIdChangeExecute.js";
import { PostSubscriptionsIdChangeExecuteRequest$zodSchema } from "../../models/postsubscriptionsidchangeexecuteop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostSubscriptionsIdChangeExecuteRequest$zodSchema,
};

export const tool$subscriptionsPostSubscriptionsIdChangeExecute: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-post-subscriptions-id-change-execute",
  description: `Execute subscription plan change

Execute a subscription plan change, including proration and invoice generation`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsPostSubscriptionsIdChangeExecute(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
