/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetSubscriptionsIdV2 } from "../../funcs/subscriptionsGetSubscriptionsIdV2.js";
import { GetSubscriptionsIdV2Request$zodSchema } from "../../models/getsubscriptionsidv2op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSubscriptionsIdV2Request$zodSchema,
};

export const tool$subscriptionsGetSubscriptionsIdV2: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-get-subscriptions-id-v2",
  description: `Get subscription V2

Get a subscription by ID with optional expand parameters`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsGetSubscriptionsIdV2(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
