/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsDeleteSubscriptionsLineitemsId } from "../../funcs/subscriptionsDeleteSubscriptionsLineitemsId.js";
import { DeleteSubscriptionsLineitemsIdRequest$zodSchema } from "../../models/deletesubscriptionslineitemsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteSubscriptionsLineitemsIdRequest$zodSchema,
};

export const tool$subscriptionsDeleteSubscriptionsLineitemsId: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-delete-subscriptions-lineitems-id",
  description: `Delete subscription line item

Delete a subscription line item by setting its end date`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsDeleteSubscriptionsLineitemsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
