/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsPostV1SubscriptionsSchedulesScheduleIdCancel } from "../../funcs/subscriptionsPostV1SubscriptionsSchedulesScheduleIdCancel.js";
import { PostV1SubscriptionsSchedulesScheduleIdCancelRequest$zodSchema } from "../../models/postv1subscriptionsschedulesscheduleidcancelop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostV1SubscriptionsSchedulesScheduleIdCancelRequest$zodSchema,
};

export const tool$subscriptionsPostV1SubscriptionsSchedulesScheduleIdCancel:
  ToolDefinition<typeof args> = {
    name: "subscriptions-post-v1-subscriptions-schedules-534",
    description: `Cancel subscription schedule

Cancels a pending subscription schedule. Supports two modes: 1) By schedule ID in path, or 2) By subscription ID + schedule type in request body`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await subscriptionsPostV1SubscriptionsSchedulesScheduleIdCancel(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
