/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetSubscriptionsIdGrantsUpcoming } from "../../funcs/subscriptionsGetSubscriptionsIdGrantsUpcoming.js";
import { GetSubscriptionsIdGrantsUpcomingRequest$zodSchema } from "../../models/getsubscriptionsidgrantsupcomingop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSubscriptionsIdGrantsUpcomingRequest$zodSchema,
};

export const tool$subscriptionsGetSubscriptionsIdGrantsUpcoming: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-get-subscriptions-id-grants-upcoming",
  description: `Get upcoming credit grant applications

Get upcoming credit grant applications for a subscription`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsGetSubscriptionsIdGrantsUpcoming(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
