/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetSubscriptionsIdEntitlements } from "../../funcs/subscriptionsGetSubscriptionsIdEntitlements.js";
import { GetSubscriptionsIdEntitlementsRequest$zodSchema } from "../../models/getsubscriptionsidentitlementsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSubscriptionsIdEntitlementsRequest$zodSchema,
};

export const tool$subscriptionsGetSubscriptionsIdEntitlements: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-get-subscriptions-id-entitlements",
  description: `Get subscription entitlements

Get all entitlements for a subscription`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsGetSubscriptionsIdEntitlements(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
