/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsPutSubscriptionsLineitemsId } from "../../funcs/subscriptionsPutSubscriptionsLineitemsId.js";
import { PutSubscriptionsLineitemsIdRequest$zodSchema } from "../../models/putsubscriptionslineitemsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutSubscriptionsLineitemsIdRequest$zodSchema,
};

export const tool$subscriptionsPutSubscriptionsLineitemsId: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-put-subscriptions-lineitems-id",
  description: `Update subscription line item

Update a subscription line item by terminating the existing one and creating a new one`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsPutSubscriptionsLineitemsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
