/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsExecuteSubscriptionModify } from "../../funcs/subscriptionsExecuteSubscriptionModify.js";
import { ExecuteSubscriptionModifyRequest$zodSchema } from "../../models/executesubscriptionmodifyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ExecuteSubscriptionModifyRequest$zodSchema,
};

export const tool$subscriptionsExecuteSubscriptionModify: ToolDefinition<
  typeof args
> = {
  name: "execute-subscription-modify",
  description: `Add customers to subscription inheritance

Attach additional child customers (by external ID) to an active standalone or parent subscription; creates inherited skeleton subscriptions for each. The subscription must be active.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsExecuteSubscriptionModify(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
