/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsPostSubscriptionsUsage } from "../../funcs/subscriptionsPostSubscriptionsUsage.js";
import { DtoGetUsageBySubscriptionRequest$zodSchema } from "../../models/dtogetusagebysubscriptionrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoGetUsageBySubscriptionRequest$zodSchema,
};

export const tool$subscriptionsPostSubscriptionsUsage: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-post-subscriptions-usage",
  description: `Get usage by subscription

Get usage for a subscription`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsPostSubscriptionsUsage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
