/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksGetTasksResult } from "../../funcs/tasksGetTasksResult.js";
import { GetTasksResultRequest$zodSchema } from "../../models/gettasksresultop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTasksResultRequest$zodSchema,
};

export const tool$tasksGetTasksResult: ToolDefinition<typeof args> = {
  name: "tasks-get-tasks-result",
  description: `Get task processing result

Get the result of a task processing workflow`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tasksGetTasksResult(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
