/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksPostTasks } from "../../funcs/tasksPostTasks.js";
import { DtoCreateTaskRequest$zodSchema } from "../../models/dtocreatetaskrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateTaskRequest$zodSchema,
};

export const tool$tasksPostTasks: ToolDefinition<typeof args> = {
  name: "tasks-post-tasks",
  description: `Create a new task

Create a new task for processing files asynchronously`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tasksPostTasks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
