/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksGetTasks } from "../../funcs/tasksGetTasks.js";
import { GetTasksRequest$zodSchema } from "../../models/gettasksop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTasksRequest$zodSchema.optional(),
};

export const tool$tasksGetTasks: ToolDefinition<typeof args> = {
  name: "tasks-get-tasks",
  description: `List tasks

List tasks with optional filtering`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tasksGetTasks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
