/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksGetTasksId } from "../../funcs/tasksGetTasksId.js";
import { GetTasksIdRequest$zodSchema } from "../../models/gettasksidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTasksIdRequest$zodSchema,
};

export const tool$tasksGetTasksId: ToolDefinition<typeof args> = {
  name: "tasks-get-tasks-id",
  description: `Get a task

Get a task by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tasksGetTasksId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
