/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksGetTasksIdDownload } from "../../funcs/tasksGetTasksIdDownload.js";
import { GetTasksIdDownloadRequest$zodSchema } from "../../models/gettasksiddownloadop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTasksIdDownloadRequest$zodSchema,
};

export const tool$tasksGetTasksIdDownload: ToolDefinition<typeof args> = {
  name: "tasks-get-tasks-id-download",
  description: `Download task export file

Generate a presigned URL for downloading an exported file (supports both Flexprice-managed and customer-owned S3)`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tasksGetTasksIdDownload(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
