/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxAssociationsDeleteTaxesAssociationsId } from "../../funcs/taxAssociationsDeleteTaxesAssociationsId.js";
import { DeleteTaxesAssociationsIdRequest$zodSchema } from "../../models/deletetaxesassociationsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteTaxesAssociationsIdRequest$zodSchema,
};

export const tool$taxAssociationsDeleteTaxesAssociationsId: ToolDefinition<
  typeof args
> = {
  name: "tax-associations-delete-taxes-associations-id",
  description: `Delete tax association

Delete a tax association by ID`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxAssociationsDeleteTaxesAssociationsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
