/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxAssociationsGetTaxesAssociations } from "../../funcs/taxAssociationsGetTaxesAssociations.js";
import { GetTaxesAssociationsRequest$zodSchema } from "../../models/gettaxesassociationsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTaxesAssociationsRequest$zodSchema.optional(),
};

export const tool$taxAssociationsGetTaxesAssociations: ToolDefinition<
  typeof args
> = {
  name: "tax-associations-get-taxes-associations",
  description: `List tax associations

List tax associations`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxAssociationsGetTaxesAssociations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
