/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxAssociationsGetTaxesAssociationsId } from "../../funcs/taxAssociationsGetTaxesAssociationsId.js";
import { GetTaxesAssociationsIdRequest$zodSchema } from "../../models/gettaxesassociationsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTaxesAssociationsIdRequest$zodSchema,
};

export const tool$taxAssociationsGetTaxesAssociationsId: ToolDefinition<
  typeof args
> = {
  name: "tax-associations-get-taxes-associations-id",
  description: `Get Tax Association

Get a tax association by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxAssociationsGetTaxesAssociationsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
