/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxAssociationsPutTaxesAssociationsId } from "../../funcs/taxAssociationsPutTaxesAssociationsId.js";
import { PutTaxesAssociationsIdRequest$zodSchema } from "../../models/puttaxesassociationsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutTaxesAssociationsIdRequest$zodSchema,
};

export const tool$taxAssociationsPutTaxesAssociationsId: ToolDefinition<
  typeof args
> = {
  name: "tax-associations-put-taxes-associations-id",
  description: `Update tax association

Update a tax association by ID`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxAssociationsPutTaxesAssociationsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
