/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxAssociationsPostTaxesAssociations } from "../../funcs/taxAssociationsPostTaxesAssociations.js";
import { DtoCreateTaxAssociationRequest$zodSchema } from "../../models/dtocreatetaxassociationrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateTaxAssociationRequest$zodSchema,
};

export const tool$taxAssociationsPostTaxesAssociations: ToolDefinition<
  typeof args
> = {
  name: "tax-associations-post-taxes-associations",
  description: `Create Tax Association

Create a new tax association`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxAssociationsPostTaxesAssociations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
