/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxRatesGetTaxesRatesId } from "../../funcs/taxRatesGetTaxesRatesId.js";
import { GetTaxesRatesIdRequest$zodSchema } from "../../models/gettaxesratesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTaxesRatesIdRequest$zodSchema,
};

export const tool$taxRatesGetTaxesRatesId: ToolDefinition<typeof args> = {
  name: "tax-rates-get-taxes-rates-id",
  description: `Get a tax rate

Get a tax rate`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxRatesGetTaxesRatesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
