/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxRatesDeleteTaxesRatesId } from "../../funcs/taxRatesDeleteTaxesRatesId.js";
import { DeleteTaxesRatesIdRequest$zodSchema } from "../../models/deletetaxesratesidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteTaxesRatesIdRequest$zodSchema,
};

export const tool$taxRatesDeleteTaxesRatesId: ToolDefinition<typeof args> = {
  name: "tax-rates-delete-taxes-rates-id",
  description: `Delete a tax rate

Delete a tax rate`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxRatesDeleteTaxesRatesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
