/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxRatesGetTaxesRates } from "../../funcs/taxRatesGetTaxesRates.js";
import { GetTaxesRatesRequest$zodSchema } from "../../models/gettaxesratesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTaxesRatesRequest$zodSchema.optional(),
};

export const tool$taxRatesGetTaxesRates: ToolDefinition<typeof args> = {
  name: "tax-rates-get-taxes-rates",
  description: `Get tax rates

Get tax rates`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxRatesGetTaxesRates(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
