/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxRatesPostTaxesRates } from "../../funcs/taxRatesPostTaxesRates.js";
import { DtoCreateTaxRateRequest$zodSchema } from "../../models/dtocreatetaxraterequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateTaxRateRequest$zodSchema,
};

export const tool$taxRatesPostTaxesRates: ToolDefinition<typeof args> = {
  name: "tax-rates-post-taxes-rates",
  description: `Create a tax rate

Create a tax rate`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxRatesPostTaxesRates(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
