/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tenantsPostTenants } from "../../funcs/tenantsPostTenants.js";
import { DtoCreateTenantRequest$zodSchema } from "../../models/dtocreatetenantrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateTenantRequest$zodSchema,
};

export const tool$tenantsPostTenants: ToolDefinition<typeof args> = {
  name: "tenants-post-tenants",
  description: `Create a new tenant

Create a new tenant`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tenantsPostTenants(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
