/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tenantsGetTenantBilling } from "../../funcs/tenantsGetTenantBilling.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$tenantsGetTenantBilling: ToolDefinition = {
  name: "tenants-get-tenant-billing",
  description: `Get billing usage for the current tenant

Get the subscription and usage details for the current tenant`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await tenantsGetTenantBilling(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
