/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tenantsPutTenantsUpdate } from "../../funcs/tenantsPutTenantsUpdate.js";
import { DtoUpdateTenantRequest$zodSchema } from "../../models/dtoupdatetenantrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoUpdateTenantRequest$zodSchema,
};

export const tool$tenantsPutTenantsUpdate: ToolDefinition<typeof args> = {
  name: "tenants-put-tenants-update",
  description: `Update a tenant

Update a tenant's details including name and billing information`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tenantsPutTenantsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
