/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersPostUsersSearch } from "../../funcs/usersPostUsersSearch.js";
import { TypesUserFilter$zodSchema } from "../../models/typesuserfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesUserFilter$zodSchema,
};

export const tool$usersPostUsersSearch: ToolDefinition<typeof args> = {
  name: "users-post-users-search",
  description: `List users with filters

Search and filter users by type (user/service_account), roles, etc.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await usersPostUsersSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
