/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersGetUsersMe } from "../../funcs/usersGetUsersMe.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$usersGetUsersMe: ToolDefinition = {
  name: "users-get-users-me",
  description: `Get user info

Get the current user's information`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await usersGetUsersMe(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
