/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsPutWalletsId } from "../../funcs/walletsPutWalletsId.js";
import { PutWalletsIdRequest$zodSchema } from "../../models/putwalletsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PutWalletsIdRequest$zodSchema,
};

export const tool$walletsPutWalletsId: ToolDefinition<typeof args> = {
  name: "wallets-put-wallets-id",
  description: `Update a wallet

Update a wallet's details including auto top-up configuration`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsPutWalletsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
