/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsPostWallets } from "../../funcs/walletsPostWallets.js";
import { DtoCreateWalletRequest$zodSchema } from "../../models/dtocreatewalletrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateWalletRequest$zodSchema,
};

export const tool$walletsPostWallets: ToolDefinition<typeof args> = {
  name: "wallets-post-wallets",
  description: `Create a new wallet

Create a new wallet for a customer`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsPostWallets(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
