/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsGetCustomersWallets } from "../../funcs/walletsGetCustomersWallets.js";
import { GetCustomersWalletsRequest$zodSchema } from "../../models/getcustomerswalletsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomersWalletsRequest$zodSchema.optional(),
};

export const tool$walletsGetCustomersWallets: ToolDefinition<typeof args> = {
  name: "wallets-get-customers-wallets",
  description: `Get Customer Wallets

Get all wallets for a customer by lookup key or id`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsGetCustomersWallets(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
