/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsPostWalletsIdTerminate } from "../../funcs/walletsPostWalletsIdTerminate.js";
import { PostWalletsIdTerminateRequest$zodSchema } from "../../models/postwalletsidterminateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostWalletsIdTerminateRequest$zodSchema,
};

export const tool$walletsPostWalletsIdTerminate: ToolDefinition<typeof args> = {
  name: "wallets-post-wallets-id-terminate",
  description: `Terminate a wallet

Terminates a wallet by closing it and debiting remaining balance`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsPostWalletsIdTerminate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
