/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsGetCustomersIdWallets } from "../../funcs/walletsGetCustomersIdWallets.js";
import { GetCustomersIdWalletsRequest$zodSchema } from "../../models/getcustomersidwalletsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomersIdWalletsRequest$zodSchema,
};

export const tool$walletsGetCustomersIdWallets: ToolDefinition<typeof args> = {
  name: "wallets-get-customers-id-wallets",
  description: `Get wallets by customer ID

Get all wallets for a customer`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsGetCustomersIdWallets(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
