/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsGetWallets } from "../../funcs/walletsGetWallets.js";
import { GetWalletsRequest$zodSchema } from "../../models/getwalletsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetWalletsRequest$zodSchema.optional(),
};

export const tool$walletsGetWallets: ToolDefinition<typeof args> = {
  name: "wallets-get-wallets",
  description: `List wallets

List wallets with optional filtering`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsGetWallets(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
