/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsPostWalletsIdTopUp } from "../../funcs/walletsPostWalletsIdTopUp.js";
import { PostWalletsIdTopUpRequest$zodSchema } from "../../models/postwalletsidtopupop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostWalletsIdTopUpRequest$zodSchema,
};

export const tool$walletsPostWalletsIdTopUp: ToolDefinition<typeof args> = {
  name: "wallets-post-wallets-id-top-up",
  description: `Top up wallet

Add credits to a wallet`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsPostWalletsIdTopUp(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
