/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsPostWalletsTransactionsSearch } from "../../funcs/walletsPostWalletsTransactionsSearch.js";
import { PostWalletsTransactionsSearchRequest$zodSchema } from "../../models/postwalletstransactionssearchop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostWalletsTransactionsSearchRequest$zodSchema.optional(),
};

export const tool$walletsPostWalletsTransactionsSearch: ToolDefinition<
  typeof args
> = {
  name: "wallets-post-wallets-transactions-search",
  description: `List wallet transactions by filter

List wallet transactions by filter`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsPostWalletsTransactionsSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
