/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksPostWebhooksChargebeeTenantIdEnvironmentId } from "../../funcs/webhooksPostWebhooksChargebeeTenantIdEnvironmentId.js";
import { PostWebhooksChargebeeTenantIdEnvironmentIdRequest$zodSchema } from "../../models/postwebhookschargebeetenantidenvironmentidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostWebhooksChargebeeTenantIdEnvironmentIdRequest$zodSchema,
};

export const tool$webhooksPostWebhooksChargebeeTenantIdEnvironmentId:
  ToolDefinition<typeof args> = {
    name: "webhooks-post-webhooks-chargebee-tenant-id-ba7",
    description: `Handle Chargebee webhook events

Process incoming Chargebee webhook events for payment status updates`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await webhooksPostWebhooksChargebeeTenantIdEnvironmentId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
