/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksPostWebhooksHubspotTenantIdEnvironmentId } from "../../funcs/webhooksPostWebhooksHubspotTenantIdEnvironmentId.js";
import { PostWebhooksHubspotTenantIdEnvironmentIdRequest$zodSchema } from "../../models/postwebhookshubspottenantidenvironmentidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostWebhooksHubspotTenantIdEnvironmentIdRequest$zodSchema,
};

export const tool$webhooksPostWebhooksHubspotTenantIdEnvironmentId:
  ToolDefinition<typeof args> = {
    name: "webhooks-post-webhooks-hubspot-tenant-id-ecf",
    description: `Handle HubSpot webhook events

Process incoming HubSpot webhook events for deal closed won and customer creation`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await webhooksPostWebhooksHubspotTenantIdEnvironmentId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
