/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksPostWebhooksStripeTenantIdEnvironmentId } from "../../funcs/webhooksPostWebhooksStripeTenantIdEnvironmentId.js";
import { PostWebhooksStripeTenantIdEnvironmentIdRequest$zodSchema } from "../../models/postwebhooksstripetenantidenvironmentidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostWebhooksStripeTenantIdEnvironmentIdRequest$zodSchema,
};

export const tool$webhooksPostWebhooksStripeTenantIdEnvironmentId:
  ToolDefinition<typeof args> = {
    name: "webhooks-post-webhooks-stripe-tenant-id-599",
    description: `Handle Stripe webhook events

Process incoming Stripe webhook events for payment status updates and customer creation`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await webhooksPostWebhooksStripeTenantIdEnvironmentId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
