/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksPostWebhooksQuickbooksTenantIdEnvironmentId } from "../../funcs/webhooksPostWebhooksQuickbooksTenantIdEnvironmentId.js";
import { PostWebhooksQuickbooksTenantIdEnvironmentIdRequest$zodSchema } from "../../models/postwebhooksquickbookstenantidenvironmentidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostWebhooksQuickbooksTenantIdEnvironmentIdRequest$zodSchema,
};

export const tool$webhooksPostWebhooksQuickbooksTenantIdEnvironmentId:
  ToolDefinition<typeof args> = {
    name: "webhooks-post-webhooks-quickbooks-tenant-id-96c",
    description: `Handle QuickBooks webhook events

Process incoming QuickBooks webhook events for payment sync`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await webhooksPostWebhooksQuickbooksTenantIdEnvironmentId(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
