/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksPostWebhooksNomodTenantIdEnvironmentId } from "../../funcs/webhooksPostWebhooksNomodTenantIdEnvironmentId.js";
import { PostWebhooksNomodTenantIdEnvironmentIdRequest$zodSchema } from "../../models/postwebhooksnomodtenantidenvironmentidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostWebhooksNomodTenantIdEnvironmentIdRequest$zodSchema,
};

export const tool$webhooksPostWebhooksNomodTenantIdEnvironmentId:
  ToolDefinition<typeof args> = {
    name: "webhooks-post-webhooks-nomod-tenant-id-540",
    description: `Handle Nomod webhook events

Process incoming Nomod webhook events for payment and invoice payments`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await webhooksPostWebhooksNomodTenantIdEnvironmentId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
