/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  LineItemCommitmentConfig,
  LineItemCommitmentConfig$zodSchema,
} from "./lineitemcommitmentconfig.js";

export type AddAddonToSubscriptionRequest = {
  addon_id: string;
  line_item_commitments?: { [k: string]: LineItemCommitmentConfig } | undefined;
  metadata?: { [k: string]: any } | undefined;
  start_date?: string | undefined;
};

export const AddAddonToSubscriptionRequest$zodSchema: z.ZodType<
  AddAddonToSubscriptionRequest
> = z.object({
  addon_id: z.string(),
  line_item_commitments: z.record(
    z.string(),
    LineItemCommitmentConfig$zodSchema,
  ).optional().describe(
    "LineItemCommitments allows setting commitment configuration per addon line item (keyed by price_id)",
  ),
  metadata: z.record(z.string(), z.any()).optional(),
  start_date: z.iso.datetime({ offset: true }).optional(),
});
