/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  AlertEntityType,
  AlertEntityType$zodSchema,
} from "./alertentitytype.js";
import { AlertState, AlertState$zodSchema } from "./alertstate.js";
import { AlertType, AlertType$zodSchema } from "./alerttype.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";

export const AlertLogFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type AlertLogFilterOrder = ClosedEnum<typeof AlertLogFilterOrder>;

export const AlertLogFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type AlertLogFilter = {
  alert_status?: AlertState | undefined;
  alert_type?: AlertType | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: AlertEntityType | undefined;
  expand?: string | undefined;
  filters?: Array<FilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: AlertLogFilterOrder | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
};

export const AlertLogFilter$zodSchema: z.ZodType<AlertLogFilter> = z.object({
  alert_status: AlertState$zodSchema.optional(),
  alert_type: AlertType$zodSchema.optional(),
  customer_id: z.string().optional(),
  end_time: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: AlertEntityType$zodSchema.optional(),
  expand: z.string().optional(),
  filters: z.array(FilterCondition$zodSchema).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: AlertLogFilterOrder$zodSchema.optional(),
  sort: z.array(SortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: Status$zodSchema.optional(),
});
