/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AlertSettings, AlertSettings$zodSchema } from "./alertsettings.js";

export type AlertInfo = {
  alert_settings?: AlertSettings | undefined;
  timestamp?: string | undefined;
  value_at_time?: number | undefined;
};

export const AlertInfo$zodSchema: z.ZodType<AlertInfo> = z.object({
  alert_settings: AlertSettings$zodSchema.optional(),
  timestamp: z.string().optional(),
  value_at_time: z.number().optional(),
});
