/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CancellationType = {
  Immediate: "immediate",
  EndOfPeriod: "end_of_period",
} as const;
export type CancellationType = ClosedEnum<typeof CancellationType>;

export const CancellationType$zodSchema = z.enum([
  "immediate",
  "end_of_period",
]);
