/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChangedSubscriptionAction,
  ChangedSubscriptionAction$zodSchema,
} from "./changedsubscriptionaction.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";

export type ChangedSubscription = {
  action?: ChangedSubscriptionAction | undefined;
  id?: string | undefined;
  status?: SubscriptionStatus | undefined;
};

export const ChangedSubscription$zodSchema: z.ZodType<ChangedSubscription> = z
  .object({
    action: ChangedSubscriptionAction$zodSchema.optional().describe(
      "created | updated",
    ),
    id: z.string().optional(),
    status: SubscriptionStatus$zodSchema.optional(),
  });
