/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ChangedInvoice = {
  action?: string | undefined;
  id?: string | undefined;
  status?: string | undefined;
};

export const ChangedInvoice$zodSchema: z.ZodType<ChangedInvoice> = z.object({
  action: z.string().optional().describe("\"created\" | \"wallet_credit\""),
  id: z.string().optional(),
  status: z.string().optional(),
});
