/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { QueryFilter, QueryFilter$zodSchema } from "./queryfilter.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";
import {
  TimeRangeFilter,
  TimeRangeFilter$zodSchema,
} from "./timerangefilter.js";

export type CostsheetFilter = {
  costsheetIDs?: Array<string> | undefined;
  environmentID?: string | undefined;
  filters?: Array<FilterCondition> | undefined;
  lookupKey?: string | undefined;
  name?: string | undefined;
  queryFilter?: QueryFilter | undefined;
  sort?: Array<SortCondition> | undefined;
  status?: Status | undefined;
  tenantID?: string | undefined;
  timeRangeFilter?: TimeRangeFilter | undefined;
};

export const CostsheetFilter$zodSchema: z.ZodType<CostsheetFilter> = z.object({
  costsheetIDs: z.array(z.string()).optional(),
  environmentID: z.string().optional(),
  filters: z.array(FilterCondition$zodSchema).optional(),
  lookupKey: z.string().optional(),
  name: z.string().optional(),
  queryFilter: QueryFilter$zodSchema.optional(),
  sort: z.array(SortCondition$zodSchema).optional(),
  status: Status$zodSchema.optional(),
  tenantID: z.string().optional(),
  timeRangeFilter: TimeRangeFilter$zodSchema.optional(),
});
