/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreateUserResponse,
  DtoCreateUserResponse$zodSchema,
} from "./dtocreateuserresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type CreateUserResponse = DtoCreateUserResponse | ErrorsErrorResponse;

export const CreateUserResponse$zodSchema: z.ZodType<CreateUserResponse> = z
  .union([
    DtoCreateUserResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
