/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CreditNoteType = {
  Adjustment: "ADJUSTMENT",
  Refund: "REFUND",
} as const;
export type CreditNoteType = ClosedEnum<typeof CreditNoteType>;

export const CreditNoteType$zodSchema = z.enum([
  "ADJUSTMENT",
  "REFUND",
]);
