/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeletePricesUnitsIdRequest = { id: string };

export const DeletePricesUnitsIdRequest$zodSchema: z.ZodType<
  DeletePricesUnitsIdRequest
> = z.object({
  id: z.string().describe("Price unit ID"),
});

export type DeletePricesUnitsIdResponse =
  | DtoSuccessResponse
  | ErrorsErrorResponse;

export const DeletePricesUnitsIdResponse$zodSchema: z.ZodType<
  DeletePricesUnitsIdResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
