/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteEntityIntegrationMappingsIdRequest = { id: string };

export const DeleteEntityIntegrationMappingsIdRequest$zodSchema: z.ZodType<
  DeleteEntityIntegrationMappingsIdRequest
> = z.object({
  id: z.string().describe("Entity integration mapping ID"),
});
