/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteCustomersIdRequest = { id: string };

export const DeleteCustomersIdRequest$zodSchema: z.ZodType<
  DeleteCustomersIdRequest
> = z.object({
  id: z.string().describe("Customer ID"),
});
