/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteTaxesRatesIdRequest = { id: string };

export const DeleteTaxesRatesIdRequest$zodSchema: z.ZodType<
  DeleteTaxesRatesIdRequest
> = z.object({
  id: z.string().describe("Tax rate ID"),
});
