/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteSubscriptionLineItemRequest = {
  effective_from?: string | undefined;
};

export const DeleteSubscriptionLineItemRequest$zodSchema: z.ZodType<
  DeleteSubscriptionLineItemRequest
> = z.object({
  effective_from: z.string().optional(),
});
