/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteAddonsIdRequest = { id: string };

export const DeleteAddonsIdRequest$zodSchema: z.ZodType<DeleteAddonsIdRequest> =
  z.object({
    id: z.string().describe("Addon ID"),
  });

export type DeleteAddonsIdResponse = DtoSuccessResponse | ErrorsErrorResponse;

export const DeleteAddonsIdResponse$zodSchema: z.ZodType<
  DeleteAddonsIdResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
