/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoDeletePriceRequest,
  DtoDeletePriceRequest$zodSchema,
} from "./dtodeletepricerequest.js";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeletePricesIdRequest = { id: string; body: DtoDeletePriceRequest };

export const DeletePricesIdRequest$zodSchema: z.ZodType<DeletePricesIdRequest> =
  z.object({
    body: DtoDeletePriceRequest$zodSchema,
    id: z.string().describe("Price ID"),
  });

export type DeletePricesIdResponse = DtoSuccessResponse | ErrorsErrorResponse;

export const DeletePricesIdResponse$zodSchema: z.ZodType<
  DeletePricesIdResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
