/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteCreditgrantsIdRequest = { id: string };

export const DeleteCreditgrantsIdRequest$zodSchema: z.ZodType<
  DeleteCreditgrantsIdRequest
> = z.object({
  id: z.string().describe("Credit Grant ID"),
});

export type DeleteCreditgrantsIdResponse =
  | DtoSuccessResponse
  | ErrorsErrorResponse;

export const DeleteCreditgrantsIdResponse$zodSchema: z.ZodType<
  DeleteCreditgrantsIdResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
