/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteFeaturesIdRequest = { id: string };

export const DeleteFeaturesIdRequest$zodSchema: z.ZodType<
  DeleteFeaturesIdRequest
> = z.object({
  id: z.string().describe("Feature ID"),
});

export type DeleteFeaturesIdResponse = DtoSuccessResponse | ErrorsErrorResponse;

export const DeleteFeaturesIdResponse$zodSchema: z.ZodType<
  DeleteFeaturesIdResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
