/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteCouponsIdRequest = { id: string };

export const DeleteCouponsIdRequest$zodSchema: z.ZodType<
  DeleteCouponsIdRequest
> = z.object({
  id: z.string().describe("Coupon ID"),
});

export type DeleteCouponsIdResponse =
  | { [k: string]: string }
  | ErrorsErrorResponse;

export const DeleteCouponsIdResponse$zodSchema: z.ZodType<
  DeleteCouponsIdResponse
> = z.union([
  z.record(z.string(), z.string()).describe("OK"),
  ErrorsErrorResponse$zodSchema,
]);
