/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteEntitlementsIdRequest = { id: string };

export const DeleteEntitlementsIdRequest$zodSchema: z.ZodType<
  DeleteEntitlementsIdRequest
> = z.object({
  id: z.string().describe("Entitlement ID"),
});

export type DeleteEntitlementsIdResponse =
  | DtoSuccessResponse
  | ErrorsErrorResponse;

export const DeleteEntitlementsIdResponse$zodSchema: z.ZodType<
  DeleteEntitlementsIdResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
