/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaxAssociationResponse,
  DtoTaxAssociationResponse$zodSchema,
} from "./dtotaxassociationresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteTaxesAssociationsIdRequest = { id: string };

export const DeleteTaxesAssociationsIdRequest$zodSchema: z.ZodType<
  DeleteTaxesAssociationsIdRequest
> = z.object({
  id: z.string().describe("Tax Config ID"),
});

export type DeleteTaxesAssociationsIdResponse =
  | DtoTaxAssociationResponse
  | ErrorsErrorResponse;

export const DeleteTaxesAssociationsIdResponse$zodSchema: z.ZodType<
  DeleteTaxesAssociationsIdResponse
> = z.union([
  DtoTaxAssociationResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
