/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DtoThreshold, DtoThreshold$zodSchema } from "./dtothreshold.js";

export type DtoAlertConfig = { threshold?: DtoThreshold | undefined };

export const DtoAlertConfig$zodSchema: z.ZodType<DtoAlertConfig> = z.object({
  threshold: DtoThreshold$zodSchema.optional(),
});
