/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoAuthResponse = {
  tenant_id?: string | undefined;
  token?: string | undefined;
  user_id?: string | undefined;
};

export const DtoAuthResponse$zodSchema: z.ZodType<DtoAuthResponse> = z.object({
  tenant_id: z.string().optional(),
  token: z.string().optional(),
  user_id: z.string().optional(),
});
