/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddonAssociationEntityType,
  AddonAssociationEntityType$zodSchema,
} from "./addonassociationentitytype.js";
import { AddonStatus, AddonStatus$zodSchema } from "./addonstatus.js";
import {
  DtoAddonResponse,
  DtoAddonResponse$zodSchema,
} from "./dtoaddonresponse.js";
import {
  DtoSubscriptionResponse,
  DtoSubscriptionResponse$zodSchema,
} from "./dtosubscriptionresponse.js";
import { Status, Status$zodSchema } from "./status.js";

export type DtoAddonAssociationResponse = {
  addon?: DtoAddonResponse | undefined;
  addon_id?: string | undefined;
  addon_status?: AddonStatus | undefined;
  cancellation_reason?: string | undefined;
  cancelled_at?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  end_date?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: AddonAssociationEntityType | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  start_date?: string | undefined;
  status?: Status | undefined;
  subscription?: DtoSubscriptionResponse | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoAddonAssociationResponse$zodSchema: z.ZodType<
  DtoAddonAssociationResponse
> = z.object({
  addon: DtoAddonResponse$zodSchema.optional(),
  addon_id: z.string().optional(),
  addon_status: AddonStatus$zodSchema.optional(),
  cancellation_reason: z.string().optional(),
  cancelled_at: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  end_date: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: AddonAssociationEntityType$zodSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.any()).optional(),
  start_date: z.string().optional(),
  status: Status$zodSchema.optional(),
  subscription: DtoSubscriptionResponse$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
