/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BillingCadence, BillingCadence$zodSchema } from "./billingcadence.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";

export type DtoBillingCycleInfo = {
  billing_anchor?: string | undefined;
  billing_cadence?: BillingCadence | undefined;
  billing_period?: BillingPeriod | undefined;
  billing_period_count?: number | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
};

export const DtoBillingCycleInfo$zodSchema: z.ZodType<DtoBillingCycleInfo> = z
  .object({
    billing_anchor: z.string().optional(),
    billing_cadence: BillingCadence$zodSchema.optional(),
    billing_period: BillingPeriod$zodSchema.optional(),
    billing_period_count: z.int().optional(),
    period_end: z.string().optional(),
    period_start: z.string().optional(),
  });
