/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreditGrantCadence,
  CreditGrantCadence$zodSchema,
} from "./creditgrantcadence.js";
import {
  CreditGrantExpiryDurationUnit,
  CreditGrantExpiryDurationUnit$zodSchema,
} from "./creditgrantexpirydurationunit.js";
import {
  CreditGrantExpiryType,
  CreditGrantExpiryType$zodSchema,
} from "./creditgrantexpirytype.js";
import {
  CreditGrantPeriod,
  CreditGrantPeriod$zodSchema,
} from "./creditgrantperiod.js";
import {
  CreditGrantScope,
  CreditGrantScope$zodSchema,
} from "./creditgrantscope.js";

export type DtoCreateCreditGrantRequest = {
  cadence: CreditGrantCadence;
  conversion_rate?: string | undefined;
  credits: string;
  end_date?: string | undefined;
  expiration_duration?: number | undefined;
  expiration_duration_unit?: CreditGrantExpiryDurationUnit | undefined;
  expiration_type?: CreditGrantExpiryType | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
  period?: CreditGrantPeriod | undefined;
  period_count?: number | undefined;
  plan_id?: string | undefined;
  priority?: number | undefined;
  scope: CreditGrantScope;
  start_date?: string | undefined;
  subscription_id?: string | undefined;
  topup_conversion_rate?: string | undefined;
};

export const DtoCreateCreditGrantRequest$zodSchema: z.ZodType<
  DtoCreateCreditGrantRequest
> = z.object({
  cadence: CreditGrantCadence$zodSchema,
  conversion_rate: z.string().optional(),
  credits: z.string(),
  end_date: z.string().optional(),
  expiration_duration: z.int().optional(),
  expiration_duration_unit: CreditGrantExpiryDurationUnit$zodSchema.optional(),
  expiration_type: CreditGrantExpiryType$zodSchema.optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string(),
  period: CreditGrantPeriod$zodSchema.optional(),
  period_count: z.int().optional(),
  plan_id: z.string().optional(),
  priority: z.int().optional(),
  scope: CreditGrantScope$zodSchema,
  start_date: z.string().optional(),
  subscription_id: z.string().optional(),
  topup_conversion_rate: z.string().optional(),
});
