/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TaxRateEntityType,
  TaxRateEntityType$zodSchema,
} from "./taxrateentitytype.js";

export type DtoCreateTaxAssociationRequest = {
  auto_apply?: boolean | undefined;
  currency?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: TaxRateEntityType | undefined;
  external_customer_id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  tax_rate_code: string;
};

export const DtoCreateTaxAssociationRequest$zodSchema: z.ZodType<
  DtoCreateTaxAssociationRequest
> = z.object({
  auto_apply: z.boolean().optional(),
  currency: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: TaxRateEntityType$zodSchema.optional(),
  external_customer_id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  priority: z.int().optional(),
  tax_rate_code: z.string(),
});
