/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AlertSettings, AlertSettings$zodSchema } from "./alertsettings.js";
import {
  DtoCreateMeterRequest,
  DtoCreateMeterRequest$zodSchema,
} from "./dtocreatemeterrequest.js";
import { FeatureType, FeatureType$zodSchema } from "./featuretype.js";
import { ReportingUnit, ReportingUnit$zodSchema } from "./reportingunit.js";

export type DtoCreateFeatureRequest = {
  alert_settings?: AlertSettings | undefined;
  description?: string | undefined;
  group_id?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: DtoCreateMeterRequest | undefined;
  meter_id?: string | undefined;
  name: string;
  reporting_unit?: ReportingUnit | undefined;
  type: FeatureType;
  unit_plural?: string | undefined;
  unit_singular?: string | undefined;
};

export const DtoCreateFeatureRequest$zodSchema: z.ZodType<
  DtoCreateFeatureRequest
> = z.object({
  alert_settings: AlertSettings$zodSchema.optional(),
  description: z.string().optional(),
  group_id: z.string().optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  meter: DtoCreateMeterRequest$zodSchema.optional(),
  meter_id: z.string().optional(),
  name: z.string(),
  reporting_unit: ReportingUnit$zodSchema.optional(),
  type: FeatureType$zodSchema,
  unit_plural: z.string().optional(),
  unit_singular: z.string().optional(),
});
