/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EntitlementEntityType,
  EntitlementEntityType$zodSchema,
} from "./entitlemententitytype.js";
import {
  EntitlementUsageResetPeriod,
  EntitlementUsageResetPeriod$zodSchema,
} from "./entitlementusageresetperiod.js";
import { FeatureType, FeatureType$zodSchema } from "./featuretype.js";

export type DtoCreateEntitlementRequest = {
  end_date?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: EntitlementEntityType | undefined;
  feature_id: string;
  feature_type: FeatureType;
  is_enabled?: boolean | undefined;
  is_soft_limit?: boolean | undefined;
  parent_entitlement_id?: string | undefined;
  plan_id?: string | undefined;
  start_date?: string | undefined;
  static_value?: string | undefined;
  usage_limit?: number | undefined;
  usage_reset_period?: EntitlementUsageResetPeriod | undefined;
};

export const DtoCreateEntitlementRequest$zodSchema: z.ZodType<
  DtoCreateEntitlementRequest
> = z.object({
  end_date: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: EntitlementEntityType$zodSchema.optional(),
  feature_id: z.string(),
  feature_type: FeatureType$zodSchema,
  is_enabled: z.boolean().optional(),
  is_soft_limit: z.boolean().optional(),
  parent_entitlement_id: z.string().optional(),
  plan_id: z.string().optional(),
  start_date: z.string().optional(),
  static_value: z.string().optional(),
  usage_limit: z.int().optional(),
  usage_reset_period: EntitlementUsageResetPeriod$zodSchema.optional(),
});
