/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BillingCadence, BillingCadence$zodSchema } from "./billingcadence.js";
import { BillingCycle, BillingCycle$zodSchema } from "./billingcycle.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import {
  CollectionMethod,
  CollectionMethod$zodSchema,
} from "./collectionmethod.js";
import {
  DtoAddAddonToSubscriptionRequest,
  DtoAddAddonToSubscriptionRequest$zodSchema,
} from "./dtoaddaddontosubscriptionrequest.js";
import {
  DtoCreateCreditGrantRequest,
  DtoCreateCreditGrantRequest$zodSchema,
} from "./dtocreatecreditgrantrequest.js";
import {
  DtoCreateSubscriptionLineItemRequest,
  DtoCreateSubscriptionLineItemRequest$zodSchema,
} from "./dtocreatesubscriptionlineitemrequest.js";
import {
  DtoLineItemCommitmentConfig,
  DtoLineItemCommitmentConfig$zodSchema,
} from "./dtolineitemcommitmentconfig.js";
import {
  DtoOverrideEntitlementRequest,
  DtoOverrideEntitlementRequest$zodSchema,
} from "./dtooverrideentitlementrequest.js";
import {
  DtoOverrideLineItemRequest,
  DtoOverrideLineItemRequest$zodSchema,
} from "./dtooverridelineitemrequest.js";
import {
  DtoSubscriptionPhaseCreateRequest,
  DtoSubscriptionPhaseCreateRequest$zodSchema,
} from "./dtosubscriptionphasecreaterequest.js";
import {
  DtoTaxRateOverride,
  DtoTaxRateOverride$zodSchema,
} from "./dtotaxrateoverride.js";
import { InvoiceBilling, InvoiceBilling$zodSchema } from "./invoicebilling.js";
import {
  PaymentBehavior,
  PaymentBehavior$zodSchema,
} from "./paymentbehavior.js";
import { PaymentTerms, PaymentTerms$zodSchema } from "./paymentterms.js";
import {
  ProrationBehavior,
  ProrationBehavior$zodSchema,
} from "./prorationbehavior.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";

export type DtoCreateSubscriptionRequest = {
  addons?: Array<DtoAddAddonToSubscriptionRequest> | undefined;
  billing_cadence: BillingCadence;
  billing_cycle?: BillingCycle | undefined;
  billing_period: BillingPeriod;
  billing_period_count?: number | undefined;
  collection_method?: CollectionMethod | undefined;
  commitment_amount?: string | undefined;
  commitment_duration?: BillingPeriod | undefined;
  coupons?: Array<string> | undefined;
  credit_grants?: Array<DtoCreateCreditGrantRequest> | undefined;
  currency: string;
  customer_id?: string | undefined;
  customer_timezone?: string | undefined;
  enable_true_up?: boolean | undefined;
  end_date?: string | undefined;
  external_customer_id?: string | undefined;
  gateway_payment_method_id?: string | undefined;
  invoice_billing?: InvoiceBilling | undefined;
  line_item_commitments?:
    | { [k: string]: DtoLineItemCommitmentConfig }
    | undefined;
  line_item_coupons?: { [k: string]: Array<string> } | undefined;
  line_items?: Array<DtoCreateSubscriptionLineItemRequest> | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  overage_factor?: string | undefined;
  override_entitlements?: Array<DtoOverrideEntitlementRequest> | undefined;
  override_line_items?: Array<DtoOverrideLineItemRequest> | undefined;
  parent_subscription_id?: string | undefined;
  payment_behavior?: PaymentBehavior | undefined;
  payment_terms?: PaymentTerms | undefined;
  phases?: Array<DtoSubscriptionPhaseCreateRequest> | undefined;
  plan_id: string;
  proration_behavior?: ProrationBehavior | undefined;
  start_date?: string | undefined;
  subscription_status?: SubscriptionStatus | undefined;
  tax_rate_overrides?: Array<DtoTaxRateOverride> | undefined;
  trial_end?: string | undefined;
  trial_start?: string | undefined;
};

export const DtoCreateSubscriptionRequest$zodSchema: z.ZodType<
  DtoCreateSubscriptionRequest
> = z.object({
  addons: z.array(DtoAddAddonToSubscriptionRequest$zodSchema).optional(),
  billing_cadence: BillingCadence$zodSchema,
  billing_cycle: BillingCycle$zodSchema.optional(),
  billing_period: BillingPeriod$zodSchema,
  billing_period_count: z.int().optional(),
  collection_method: CollectionMethod$zodSchema.optional(),
  commitment_amount: z.string().optional(),
  commitment_duration: BillingPeriod$zodSchema.optional(),
  coupons: z.array(z.string()).optional(),
  credit_grants: z.array(DtoCreateCreditGrantRequest$zodSchema).optional(),
  currency: z.string(),
  customer_id: z.string().optional(),
  customer_timezone: z.string().optional(),
  enable_true_up: z.boolean().optional(),
  end_date: z.string().optional(),
  external_customer_id: z.string().optional(),
  gateway_payment_method_id: z.string().optional(),
  invoice_billing: InvoiceBilling$zodSchema.optional(),
  line_item_commitments: z.record(
    z.string(),
    DtoLineItemCommitmentConfig$zodSchema,
  ).optional(),
  line_item_coupons: z.record(z.string(), z.array(z.string())).optional(),
  line_items: z.array(DtoCreateSubscriptionLineItemRequest$zodSchema)
    .optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  overage_factor: z.string().optional(),
  override_entitlements: z.array(DtoOverrideEntitlementRequest$zodSchema)
    .optional(),
  override_line_items: z.array(DtoOverrideLineItemRequest$zodSchema).optional(),
  parent_subscription_id: z.string().optional(),
  payment_behavior: PaymentBehavior$zodSchema.optional(),
  payment_terms: PaymentTerms$zodSchema.optional(),
  phases: z.array(DtoSubscriptionPhaseCreateRequest$zodSchema).optional(),
  plan_id: z.string(),
  proration_behavior: ProrationBehavior$zodSchema.optional(),
  start_date: z.string().optional(),
  subscription_status: SubscriptionStatus$zodSchema.optional(),
  tax_rate_overrides: z.array(DtoTaxRateOverride$zodSchema).optional(),
  trial_end: z.string().optional(),
  trial_start: z.string().optional(),
});
