/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AlertSettings, AlertSettings$zodSchema } from "./alertsettings.js";
import { AutoTopup, AutoTopup$zodSchema } from "./autotopup.js";
import { WalletType, WalletType$zodSchema } from "./wallettype.js";

export type DtoCreateWalletRequest = {
  alert_settings?: AlertSettings | undefined;
  auto_topup?: AutoTopup | undefined;
  conversion_rate?: string | undefined;
  currency: string;
  customer_id?: string | undefined;
  description?: string | undefined;
  external_customer_id?: string | undefined;
  initial_credits_expiry_date_utc?: string | undefined;
  initial_credits_to_load?: string | undefined;
  initial_credits_to_load_expiry_date?: number | undefined;
  metadata?: { [k: string]: string } | undefined;
  price_unit?: string | undefined;
  topup_conversion_rate?: string | undefined;
  wallet_type?: WalletType | undefined;
};

export const DtoCreateWalletRequest$zodSchema: z.ZodType<
  DtoCreateWalletRequest
> = z.object({
  alert_settings: AlertSettings$zodSchema.optional(),
  auto_topup: AutoTopup$zodSchema.optional(),
  conversion_rate: z.string().default("1"),
  currency: z.string(),
  customer_id: z.string().optional(),
  description: z.string().optional(),
  external_customer_id: z.string().optional(),
  initial_credits_expiry_date_utc: z.string().optional(),
  initial_credits_to_load: z.string().default("0"),
  initial_credits_to_load_expiry_date: z.int().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  price_unit: z.string().optional(),
  topup_conversion_rate: z.string().optional(),
  wallet_type: WalletType$zodSchema.optional(),
});
