/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { UserType, UserType$zodSchema } from "./usertype.js";

export type DtoCreateUserRequest = {
  email?: string | undefined;
  roles?: Array<string> | undefined;
  type: UserType;
};

export const DtoCreateUserRequest$zodSchema: z.ZodType<DtoCreateUserRequest> = z
  .object({
    email: z.string().optional(),
    roles: z.array(z.string()).optional(),
    type: UserType$zodSchema,
  });
