/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DtoAlertConfig, DtoAlertConfig$zodSchema } from "./dtoalertconfig.js";
import { TypesAutoTopup, TypesAutoTopup$zodSchema } from "./typesautotopup.js";
import {
  TypesWalletConfig,
  TypesWalletConfig$zodSchema,
} from "./typeswalletconfig.js";
import {
  TypesWalletType,
  TypesWalletType$zodSchema,
} from "./typeswallettype.js";

export type DtoCreateWalletRequest = {
  alert_config?: DtoAlertConfig | undefined;
  alert_enabled?: boolean | undefined;
  auto_topup?: TypesAutoTopup | undefined;
  config?: TypesWalletConfig | undefined;
  conversion_rate?: string | undefined;
  currency: string;
  customer_id?: string | undefined;
  description?: string | undefined;
  external_customer_id?: string | undefined;
  initial_credits_expiry_date_utc?: string | undefined;
  initial_credits_to_load?: string | undefined;
  initial_credits_to_load_expiry_date?: number | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  price_unit?: string | undefined;
  topup_conversion_rate?: string | undefined;
  wallet_type?: TypesWalletType | undefined;
};

export const DtoCreateWalletRequest$zodSchema: z.ZodType<
  DtoCreateWalletRequest
> = z.object({
  alert_config: DtoAlertConfig$zodSchema.optional(),
  alert_enabled: z.boolean().optional(),
  auto_topup: TypesAutoTopup$zodSchema.optional(),
  config: TypesWalletConfig$zodSchema.optional(),
  conversion_rate: z.string().default("1"),
  currency: z.string(),
  customer_id: z.string().optional(),
  description: z.string().optional(),
  external_customer_id: z.string().optional(),
  initial_credits_expiry_date_utc: z.string().optional(),
  initial_credits_to_load: z.string().default("0"),
  initial_credits_to_load_expiry_date: z.int().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  price_unit: z.string().optional(),
  topup_conversion_rate: z.string().optional(),
  wallet_type: TypesWalletType$zodSchema.optional(),
});
