/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SecretType, SecretType$zodSchema } from "./secrettype.js";

export type DtoCreateAPIKeyRequest = {
  expires_at?: string | undefined;
  name: string;
  service_account_id?: string | undefined;
  type: SecretType;
};

export const DtoCreateAPIKeyRequest$zodSchema: z.ZodType<
  DtoCreateAPIKeyRequest
> = z.object({
  expires_at: z.string().optional(),
  name: z.string(),
  service_account_id: z.string().optional(),
  type: SecretType$zodSchema,
});
