/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CancellationType,
  CancellationType$zodSchema,
} from "./cancellationtype.js";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$zodSchema,
} from "./dtoinvoiceresponse.js";
import {
  DtoProrationDetail,
  DtoProrationDetail$zodSchema,
} from "./dtoprorationdetail.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";

export type DtoCancelSubscriptionResponse = {
  cancellation_type?: CancellationType | undefined;
  effective_date?: string | undefined;
  message?: string | undefined;
  processed_at?: string | undefined;
  proration_details?: Array<DtoProrationDetail> | undefined;
  proration_invoice?: DtoInvoiceResponse | undefined;
  reason?: string | undefined;
  status?: SubscriptionStatus | undefined;
  subscription_id?: string | undefined;
  total_credit_amount?: string | undefined;
};

export const DtoCancelSubscriptionResponse$zodSchema: z.ZodType<
  DtoCancelSubscriptionResponse
> = z.object({
  cancellation_type: CancellationType$zodSchema.optional(),
  effective_date: z.string().optional(),
  message: z.string().optional(),
  processed_at: z.string().optional(),
  proration_details: z.array(DtoProrationDetail$zodSchema).optional(),
  proration_invoice: DtoInvoiceResponse$zodSchema.optional(),
  reason: z.string().optional(),
  status: SubscriptionStatus$zodSchema.optional(),
  subscription_id: z.string().optional(),
  total_credit_amount: z.string().optional(),
});
