/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoIntegrationEntityMapping,
  DtoIntegrationEntityMapping$zodSchema,
} from "./dtointegrationentitymapping.js";
import {
  DtoTaxRateOverride,
  DtoTaxRateOverride$zodSchema,
} from "./dtotaxrateoverride.js";

/**
 * Request object for creating a new customer in the system
 */
export type DtoCreateCustomerRequest = {
  address_city?: string | undefined;
  address_country?: string | undefined;
  address_line1?: string | undefined;
  address_line2?: string | undefined;
  address_postal_code?: string | undefined;
  address_state?: string | undefined;
  email?: string | undefined;
  external_id: string;
  integration_entity_mapping?: Array<DtoIntegrationEntityMapping> | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  parent_customer_external_id?: string | undefined;
  parent_customer_id?: string | undefined;
  skip_onboarding_workflow?: boolean | undefined;
  tax_rate_overrides?: Array<DtoTaxRateOverride> | undefined;
};

export const DtoCreateCustomerRequest$zodSchema: z.ZodType<
  DtoCreateCustomerRequest
> = z.object({
  address_city: z.string().optional().describe(
    "address_city is the city name with maximum 100 characters",
  ),
  address_country: z.string().optional().describe(
    "address_country is the two-letter ISO 3166-1 alpha-2 country code",
  ),
  address_line1: z.string().optional().describe(
    "address_line1 is the primary address line with maximum 255 characters",
  ),
  address_line2: z.string().optional().describe(
    "address_line2 is the secondary address line with maximum 255 characters",
  ),
  address_postal_code: z.string().optional().describe(
    "address_postal_code is the ZIP code or postal code with maximum 20 characters",
  ),
  address_state: z.string().optional().describe(
    "address_state is the state, province, or region name with maximum 100 characters",
  ),
  email: z.string().optional().describe(
    "email is the customer's email address and must be a valid email format if provided",
  ),
  external_id: z.string().describe(
    "external_id is the unique identifier from your system to reference this customer (required)",
  ),
  integration_entity_mapping: z.array(DtoIntegrationEntityMapping$zodSchema)
    .optional().describe(
      "integration_entity_mapping contains provider integration mappings for this customer",
    ),
  metadata: z.record(z.string(), z.string()).optional().describe(
    "metadata contains additional key-value pairs for storing extra information",
  ),
  name: z.string().optional().describe(
    "name is the full name or company name of the customer",
  ),
  parent_customer_external_id: z.string().optional().describe(
    "Deprecated: See ParentCustomerID.\nparent_customer_external_id is the external ID of the parent customer from your system.\nExactly one of parent_customer_id or parent_customer_external_id may be provided.",
  ),
  parent_customer_id: z.string().optional().describe(
    "Deprecated: Customer parent hierarchy is deprecated in favor of subscription-level hierarchy.\nThis field is accepted for backward compatibility but no hierarchy validations are enforced.\nparent_customer_id is the internal FlexPrice ID of the parent customer.",
  ),
  skip_onboarding_workflow: z.boolean().optional().describe(
    "skip_onboarding_workflow when true, prevents the customer onboarding workflow from being triggered\nThis is used internally when a customer is created via a workflow to prevent infinite loops\nDefault: false",
  ),
  tax_rate_overrides: z.array(DtoTaxRateOverride$zodSchema).optional().describe(
    "tax_rate_overrides contains tax rate configurations to be linked to this customer",
  ),
}).describe("Request object for creating a new customer in the system");
