/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CancelImmediatelyInvoicePolicy,
  CancelImmediatelyInvoicePolicy$zodSchema,
} from "./cancelimmediatelyinvoicepolicy.js";
import {
  CancellationType,
  CancellationType$zodSchema,
} from "./cancellationtype.js";
import {
  ProrationBehavior,
  ProrationBehavior$zodSchema,
} from "./prorationbehavior.js";

export type DtoCancelSubscriptionRequest = {
  cancel_at?: string | undefined;
  cancel_immediately_inovice_policy?:
    | CancelImmediatelyInvoicePolicy
    | undefined;
  cancellation_type: CancellationType;
  proration_behavior?: ProrationBehavior | undefined;
  reason?: string | undefined;
};

export const DtoCancelSubscriptionRequest$zodSchema: z.ZodType<
  DtoCancelSubscriptionRequest
> = z.object({
  cancel_at: z.string().optional().describe(
    "CancelAt is the custom date to cancel the subscription.\nRequired when CancellationType is \"scheduled_date\". Must be in the future.",
  ),
  cancel_immediately_inovice_policy: CancelImmediatelyInvoicePolicy$zodSchema
    .optional(),
  cancellation_type: CancellationType$zodSchema,
  proration_behavior: ProrationBehavior$zodSchema.optional(),
  reason: z.string().optional().describe(
    "Reason for cancellation (for audit and business intelligence)",
  ),
});
