/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { S3JobConfig, S3JobConfig$zodSchema } from "./s3jobconfig.js";
import {
  ScheduledTaskEntityType,
  ScheduledTaskEntityType$zodSchema,
} from "./scheduledtaskentitytype.js";
import {
  ScheduledTaskInterval,
  ScheduledTaskInterval$zodSchema,
} from "./scheduledtaskinterval.js";

export type DtoCreateScheduledTaskRequest = {
  connection_id: string;
  enabled?: boolean | undefined;
  entity_type: ScheduledTaskEntityType;
  interval: ScheduledTaskInterval;
  job_config: S3JobConfig;
};

export const DtoCreateScheduledTaskRequest$zodSchema: z.ZodType<
  DtoCreateScheduledTaskRequest
> = z.object({
  connection_id: z.string(),
  enabled: z.boolean().optional(),
  entity_type: ScheduledTaskEntityType$zodSchema,
  interval: ScheduledTaskInterval$zodSchema,
  job_config: S3JobConfig$zodSchema,
});
