/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PaymentDestinationType,
  PaymentDestinationType$zodSchema,
} from "./paymentdestinationtype.js";
import {
  PaymentGatewayType,
  PaymentGatewayType$zodSchema,
} from "./paymentgatewaytype.js";
import {
  PaymentMethodType,
  PaymentMethodType$zodSchema,
} from "./paymentmethodtype.js";

export type DtoCreatePaymentRequest = {
  amount: string;
  cancel_url?: string | undefined;
  currency: string;
  destination_id: string;
  destination_type: PaymentDestinationType;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  payment_gateway?: PaymentGatewayType | undefined;
  payment_method_id?: string | undefined;
  payment_method_type: PaymentMethodType;
  process_payment?: boolean | undefined;
  save_card_and_make_default?: boolean | undefined;
  success_url?: string | undefined;
};

export const DtoCreatePaymentRequest$zodSchema: z.ZodType<
  DtoCreatePaymentRequest
> = z.object({
  amount: z.string(),
  cancel_url: z.string().optional(),
  currency: z.string(),
  destination_id: z.string(),
  destination_type: PaymentDestinationType$zodSchema,
  idempotency_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  payment_gateway: PaymentGatewayType$zodSchema.optional(),
  payment_method_id: z.string().optional(),
  payment_method_type: PaymentMethodType$zodSchema,
  process_payment: z.boolean().default(true),
  save_card_and_make_default: z.boolean().default(false),
  success_url: z.string().optional(),
});
