/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTenantBillingDetails,
  DtoTenantBillingDetails$zodSchema,
} from "./dtotenantbillingdetails.js";

export type DtoCreateTenantRequest = {
  billing_details?: DtoTenantBillingDetails | undefined;
  name: string;
};

export const DtoCreateTenantRequest$zodSchema: z.ZodType<
  DtoCreateTenantRequest
> = z.object({
  billing_details: DtoTenantBillingDetails$zodSchema.optional(),
  name: z.string(),
});
