/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { EntityType, EntityType$zodSchema } from "./entitytype.js";
import { FileType, FileType$zodSchema } from "./filetype.js";
import { TaskType, TaskType$zodSchema } from "./tasktype.js";

export type DtoCreateTaskRequest = {
  entity_type: EntityType;
  file_name?: string | undefined;
  file_type: FileType;
  file_url: string;
  metadata?: { [k: string]: any } | undefined;
  task_type: TaskType;
};

export const DtoCreateTaskRequest$zodSchema: z.ZodType<DtoCreateTaskRequest> = z
  .object({
    entity_type: EntityType$zodSchema,
    file_name: z.string().optional(),
    file_type: FileType$zodSchema,
    file_url: z.string(),
    metadata: z.record(z.string(), z.any()).optional(),
    task_type: TaskType$zodSchema,
  });
