/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SecretProvider, SecretProvider$zodSchema } from "./secretprovider.js";

export type DtoCreateIntegrationRequest = {
  credentials: { [k: string]: string };
  name: string;
  provider: SecretProvider;
};

export const DtoCreateIntegrationRequest$zodSchema: z.ZodType<
  DtoCreateIntegrationRequest
> = z.object({
  credentials: z.record(z.string(), z.string()),
  name: z.string(),
  provider: SecretProvider$zodSchema,
});
