/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesSecretProvider,
  TypesSecretProvider$zodSchema,
} from "./typessecretprovider.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import {
  TypesSyncConfig,
  TypesSyncConfig$zodSchema,
} from "./typessyncconfig.js";

export type DtoConnectionResponse = {
  created_at?: string | undefined;
  created_by?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  name?: string | undefined;
  provider_type?: TypesSecretProvider | undefined;
  status?: TypesStatus | undefined;
  sync_config?: TypesSyncConfig | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoConnectionResponse$zodSchema: z.ZodType<DtoConnectionResponse> =
  z.object({
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    environment_id: z.string().optional(),
    id: z.string().optional(),
    metadata: z.record(z.string(), z.any()).optional(),
    name: z.string().optional(),
    provider_type: TypesSecretProvider$zodSchema.optional(),
    status: TypesStatus$zodSchema.optional(),
    sync_config: TypesSyncConfig$zodSchema.optional(),
    tenant_id: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
  });
