/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoEventCountPoint = {
  event_count?: number | undefined;
  timestamp?: string | undefined;
};

export const DtoEventCountPoint$zodSchema: z.ZodType<DtoEventCountPoint> = z
  .object({
    event_count: z.int().optional(),
    timestamp: z.string().optional(),
  });
