/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WindowSize, WindowSize$zodSchema } from "./windowsize.js";

export type DtoGetUsageAnalyticsRequest = {
  end_time?: string | undefined;
  expand?: Array<string> | undefined;
  external_customer_id: string;
  feature_ids?: Array<string> | undefined;
  group_by?: Array<string> | undefined;
  property_filters?: { [k: string]: Array<string> } | undefined;
  sources?: Array<string> | undefined;
  start_time?: string | undefined;
  window_size?: WindowSize | undefined;
};

export const DtoGetUsageAnalyticsRequest$zodSchema: z.ZodType<
  DtoGetUsageAnalyticsRequest
> = z.object({
  end_time: z.string().optional(),
  expand: z.array(z.string()).optional().describe(
    "allowed values: \"price\", \"meter\", \"feature\", \"subscription_line_item\",\"plan\",\"addon\"",
  ),
  external_customer_id: z.string(),
  feature_ids: z.array(z.string()).optional(),
  group_by: z.array(z.string()).optional().describe(
    "allowed values: \"source\", \"feature_id\", \"properties.<field_name>\"",
  ),
  property_filters: z.record(z.string(), z.array(z.string())).optional()
    .describe(
      "Property filters to filter the events by the keys in `properties` field of the event",
    ),
  sources: z.array(z.string()).optional(),
  start_time: z.string().optional(),
  window_size: WindowSize$zodSchema.optional(),
});
