/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoUsageAnalyticItem,
  DtoUsageAnalyticItem$zodSchema,
} from "./dtousageanalyticitem.js";

export type DtoGetUsageAnalyticsResponse = {
  currency?: string | undefined;
  items?: Array<DtoUsageAnalyticItem> | undefined;
  total_cost?: string | undefined;
};

export const DtoGetUsageAnalyticsResponse$zodSchema: z.ZodType<
  DtoGetUsageAnalyticsResponse
> = z.object({
  currency: z.string().optional(),
  items: z.array(DtoUsageAnalyticItem$zodSchema).optional(),
  total_cost: z.string().optional(),
});
