/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoInvoiceLineItemPreview,
  DtoInvoiceLineItemPreview$zodSchema,
} from "./dtoinvoicelineitempreview.js";

export type DtoInvoicePreview = {
  currency?: string | undefined;
  due_date?: string | undefined;
  line_items?: Array<DtoInvoiceLineItemPreview> | undefined;
  subtotal?: string | undefined;
  tax_amount?: string | undefined;
  total?: string | undefined;
};

export const DtoInvoicePreview$zodSchema: z.ZodType<DtoInvoicePreview> = z
  .object({
    currency: z.string().optional().describe(
      "currency is the currency for all amounts",
    ),
    due_date: z.string().optional().describe(
      "due_date is when the invoice would be due",
    ),
    line_items: z.array(DtoInvoiceLineItemPreview$zodSchema).optional()
      .describe("line_items contains preview of line items"),
    subtotal: z.string().optional().describe(
      "subtotal is the subtotal amount before taxes",
    ),
    tax_amount: z.string().optional().describe(
      "tax_amount is the total tax amount",
    ),
    total: z.string().optional().describe(
      "total is the total amount including taxes",
    ),
  });
