/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCouponApplicationResponse,
  DtoCouponApplicationResponse$zodSchema,
} from "./dtocouponapplicationresponse.js";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$zodSchema,
} from "./dtocustomerresponse.js";
import {
  DtoInvoiceLineItemResponse,
  DtoInvoiceLineItemResponse$zodSchema,
} from "./dtoinvoicelineitemresponse.js";
import {
  DtoSubscriptionResponse,
  DtoSubscriptionResponse$zodSchema,
} from "./dtosubscriptionresponse.js";
import {
  DtoTaxAppliedResponse,
  DtoTaxAppliedResponse$zodSchema,
} from "./dtotaxappliedresponse.js";
import { InvoiceStatus, InvoiceStatus$zodSchema } from "./invoicestatus.js";
import { InvoiceType, InvoiceType$zodSchema } from "./invoicetype.js";
import { PaymentStatus, PaymentStatus$zodSchema } from "./paymentstatus.js";
import { Status, Status$zodSchema } from "./status.js";

export type DtoInvoiceResponse = {
  adjustment_amount?: string | undefined;
  amount_due?: string | undefined;
  amount_paid?: string | undefined;
  amount_remaining?: string | undefined;
  billing_period?: string | undefined;
  billing_reason?: string | undefined;
  billing_sequence?: number | undefined;
  coupon_applications?: Array<DtoCouponApplicationResponse> | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  currency?: string | undefined;
  customer?: DtoCustomerResponse | undefined;
  customer_id?: string | undefined;
  description?: string | undefined;
  due_date?: string | undefined;
  environment_id?: string | undefined;
  finalized_at?: string | undefined;
  id?: string | undefined;
  idempotency_key?: string | undefined;
  invoice_number?: string | undefined;
  invoice_pdf_url?: string | undefined;
  invoice_status?: InvoiceStatus | undefined;
  invoice_type?: InvoiceType | undefined;
  last_computed_at?: string | undefined;
  line_items?: Array<DtoInvoiceLineItemResponse> | undefined;
  metadata?: { [k: string]: string } | undefined;
  overpaid_amount?: string | undefined;
  paid_at?: string | undefined;
  payment_status?: PaymentStatus | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  recalculated_invoice_id?: string | undefined;
  refunded_amount?: string | undefined;
  status?: Status | undefined;
  subscription?: DtoSubscriptionResponse | undefined;
  subscription_id?: string | undefined;
  subtotal?: string | undefined;
  taxes?: Array<DtoTaxAppliedResponse> | undefined;
  tenant_id?: string | undefined;
  total?: string | undefined;
  total_discount?: string | undefined;
  total_prepaid_credits_applied?: string | undefined;
  total_tax?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  version?: number | undefined;
  voided_at?: string | undefined;
};

export const DtoInvoiceResponse$zodSchema: z.ZodType<DtoInvoiceResponse> = z
  .object({
    adjustment_amount: z.string().optional().describe(
      "adjustment_amount is the total sum of credit notes of type \"adjustment\".\nThese are non-cash reductions applied to the invoice (e.g. goodwill credit, billing correction).",
    ),
    amount_due: z.string().optional().describe(
      "amount_due is the total amount that needs to be paid for this invoice",
    ),
    amount_paid: z.string().optional().describe(
      "amount_paid is the amount that has already been paid towards this invoice",
    ),
    amount_remaining: z.string().optional().describe(
      "amount_remaining is the outstanding amount still owed on this invoice (calculated as amount_due minus amount_paid)",
    ),
    billing_period: z.string().optional().describe(
      "billing_period describes the billing period this invoice covers (e.g., \"January 2024\", \"Q1 2024\")",
    ),
    billing_reason: z.string().optional().describe(
      "billing_reason indicates why this invoice was generated (e.g., \"subscription_billing\", \"manual_charge\")",
    ),
    billing_sequence: z.int().optional().describe(
      "billing_sequence is the sequential number indicating the billing cycle for subscription invoices",
    ),
    coupon_applications: z.array(DtoCouponApplicationResponse$zodSchema)
      .optional().describe(
        "coupon_applications contains the coupon applications associated with this invoice (overrides embedded field)",
      ),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    currency: z.string().optional().describe(
      "currency is the three-letter ISO currency code (e.g., USD, EUR, GBP) that applies to all monetary amounts on this invoice",
    ),
    customer: DtoCustomerResponse$zodSchema.optional().describe(
      "Customer response object containing all customer information",
    ),
    customer_id: z.string().optional().describe(
      "customer_id is the ID of the customer who will receive this invoice",
    ),
    description: z.string().optional().describe(
      "description is an optional description or notes about this invoice",
    ),
    due_date: z.string().optional().describe(
      "due_date is the date when payment for this invoice is due",
    ),
    environment_id: z.string().optional().describe(
      "environment_id is the ID of the environment this invoice belongs to (for multi-environment setups)",
    ),
    finalized_at: z.string().optional().describe(
      "finalized_at is the timestamp when this invoice was finalized and made ready for payment",
    ),
    id: z.string().optional().describe(
      "id is the unique identifier for this invoice",
    ),
    idempotency_key: z.string().optional().describe(
      "idempotency_key is a unique key used to prevent duplicate invoice creation when retrying API calls",
    ),
    invoice_number: z.string().optional().describe(
      "invoice_number is the human-readable invoice number displayed to customers (e.g., INV-2024-001)",
    ),
    invoice_pdf_url: z.string().optional().describe(
      "invoice_pdf_url is the URL where customers can download the PDF version of this invoice",
    ),
    invoice_status: InvoiceStatus$zodSchema.optional(),
    invoice_type: InvoiceType$zodSchema.optional(),
    last_computed_at: z.string().optional().describe(
      "last_computed_at is the timestamp when this invoice was last computed by ComputeInvoice",
    ),
    line_items: z.array(DtoInvoiceLineItemResponse$zodSchema).optional()
      .describe(
        "line_items contains the individual items that make up this invoice (overrides embedded field)",
      ),
    metadata: z.record(z.string(), z.string()).optional(),
    overpaid_amount: z.string().optional().describe(
      "overpaid_amount is the amount overpaid if payment_status is OVERPAID (amount_paid - total)",
    ),
    paid_at: z.string().optional().describe(
      "paid_at is the timestamp when this invoice was fully paid",
    ),
    payment_status: PaymentStatus$zodSchema.optional(),
    period_end: z.string().optional().describe(
      "period_end is the end date of the billing period covered by this invoice",
    ),
    period_start: z.string().optional().describe(
      "period_start is the start date of the billing period covered by this invoice",
    ),
    recalculated_invoice_id: z.string().optional().describe(
      "recalculated_invoice_id is the ID of the replacement invoice created when this invoice was voided and recalculated.\nWhen set, it forms a parent→child link from this (voided) invoice to the new replacement invoice.",
    ),
    refunded_amount: z.string().optional().describe(
      "refunded_amount is the total sum of credit notes of type \"refund\".\nThese are actual refunds issued to the customer.",
    ),
    status: Status$zodSchema.optional(),
    subscription: z.lazy(() => DtoSubscriptionResponse$zodSchema).optional(),
    subscription_id: z.string().optional().describe(
      "subscription_id is the ID of the subscription this invoice is associated with (only present for subscription-based invoices)",
    ),
    subtotal: z.string().optional().describe(
      "subtotal is the sum of all line items before any taxes, discounts, or additional fees",
    ),
    taxes: z.array(DtoTaxAppliedResponse$zodSchema).optional().describe(
      "tax_applied_records contains the tax applied records associated with this invoice",
    ),
    tenant_id: z.string().optional(),
    total: z.string().optional().describe(
      "total is the final amount including taxes, fees, and discounts",
    ),
    total_discount: z.string().optional().describe(
      "total_discount is the sum of all coupon discounts applied to the invoice",
    ),
    total_prepaid_credits_applied: z.string().optional().describe(
      "total_prepaid_credits_applied is the total amount of prepaid credits applied to this invoice.",
    ),
    total_tax: z.string().optional().describe(
      "total_tax is the sum of all taxes combined at the invoice level.",
    ),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
    version: z.int().optional().describe(
      "version is the version number for tracking changes to this invoice",
    ),
    voided_at: z.string().optional().describe(
      "voided_at is the timestamp when this invoice was voided or cancelled",
    ),
  });
