/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaskResponse,
  DtoTaskResponse$zodSchema,
} from "./dtotaskresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListTasksResponse = {
  items?: Array<DtoTaskResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListTasksResponse$zodSchema: z.ZodType<DtoListTasksResponse> = z
  .object({
    items: z.array(DtoTaskResponse$zodSchema).optional(),
    pagination: PaginationResponse$zodSchema.optional(),
  });
