/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoUserResponse,
  DtoUserResponse$zodSchema,
} from "./dtouserresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListUsersResponse = {
  items?: Array<DtoUserResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListUsersResponse$zodSchema: z.ZodType<DtoListUsersResponse> = z
  .object({
    items: z.array(DtoUserResponse$zodSchema).optional(),
    pagination: PaginationResponse$zodSchema.optional(),
  });
