/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreditNoteResponse,
  DtoCreditNoteResponse$zodSchema,
} from "./dtocreditnoteresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type DtoListCreditNotesResponse = {
  items?: Array<DtoCreditNoteResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const DtoListCreditNotesResponse$zodSchema: z.ZodType<
  DtoListCreditNotesResponse
> = z.object({
  items: z.array(DtoCreditNoteResponse$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
});
