/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSubscriptionResponse,
  DtoSubscriptionResponse$zodSchema,
} from "./dtosubscriptionresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListSubscriptionsResponse = {
  items?: Array<DtoSubscriptionResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListSubscriptionsResponse$zodSchema: z.ZodType<
  DtoListSubscriptionsResponse
> = z.object({
  items: z.array(DtoSubscriptionResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
