/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoAlertLogResponse,
  DtoAlertLogResponse$zodSchema,
} from "./dtoalertlogresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListAlertLogsResponse = {
  items?: Array<DtoAlertLogResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListAlertLogsResponse$zodSchema: z.ZodType<
  DtoListAlertLogsResponse
> = z.object({
  items: z.array(DtoAlertLogResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
