/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSecretResponse,
  DtoSecretResponse$zodSchema,
} from "./dtosecretresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListSecretsResponse = {
  items?: Array<DtoSecretResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListSecretsResponse$zodSchema: z.ZodType<
  DtoListSecretsResponse
> = z.object({
  items: z.array(DtoSecretResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
