/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCouponResponse,
  DtoCouponResponse$zodSchema,
} from "./dtocouponresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListCouponsResponse = {
  items?: Array<DtoCouponResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListCouponsResponse$zodSchema: z.ZodType<
  DtoListCouponsResponse
> = z.object({
  items: z.array(DtoCouponResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
