/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntityIntegrationMappingResponse,
  DtoEntityIntegrationMappingResponse$zodSchema,
} from "./dtoentityintegrationmappingresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type DtoListEntityIntegrationMappingsResponse = {
  items?: Array<DtoEntityIntegrationMappingResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const DtoListEntityIntegrationMappingsResponse$zodSchema: z.ZodType<
  DtoListEntityIntegrationMappingsResponse
> = z.object({
  items: z.array(DtoEntityIntegrationMappingResponse$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
});
