/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletTransactionResponse,
  DtoWalletTransactionResponse$zodSchema,
} from "./dtowallettransactionresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListWalletTransactionsResponse = {
  items?: Array<DtoWalletTransactionResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListWalletTransactionsResponse$zodSchema: z.ZodType<
  DtoListWalletTransactionsResponse
> = z.object({
  items: z.array(DtoWalletTransactionResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
