/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoScheduledTaskResponse,
  DtoScheduledTaskResponse$zodSchema,
} from "./dtoscheduledtaskresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListScheduledTasksResponse = {
  items?: Array<DtoScheduledTaskResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListScheduledTasksResponse$zodSchema: z.ZodType<
  DtoListScheduledTasksResponse
> = z.object({
  items: z.array(DtoScheduledTaskResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
