/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEnvironmentResponse,
  DtoEnvironmentResponse$zodSchema,
} from "./dtoenvironmentresponse.js";

export type DtoListEnvironmentsResponse = {
  environments?: Array<DtoEnvironmentResponse> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  total?: number | undefined;
};

export const DtoListEnvironmentsResponse$zodSchema: z.ZodType<
  DtoListEnvironmentsResponse
> = z.object({
  environments: z.array(DtoEnvironmentResponse$zodSchema).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  total: z.int().optional(),
});
