/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoLoginRequest = {
  email: string;
  password: string;
  token?: string | undefined;
};

export const DtoLoginRequest$zodSchema: z.ZodType<DtoLoginRequest> = z.object({
  email: z.string(),
  password: z.string(),
  token: z.string().optional(),
});
