/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceUnitResponse,
  DtoPriceUnitResponse$zodSchema,
} from "./dtopriceunitresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListPriceUnitsResponse = {
  items?: Array<DtoPriceUnitResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListPriceUnitsResponse$zodSchema: z.ZodType<
  DtoListPriceUnitsResponse
> = z.object({
  items: z.array(DtoPriceUnitResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
