/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoPlanSummary = {
  description?: string | undefined;
  id?: string | undefined;
  lookup_key?: string | undefined;
  name?: string | undefined;
};

export const DtoPlanSummary$zodSchema: z.ZodType<DtoPlanSummary> = z.object({
  description: z.string().optional().describe("description of the plan"),
  id: z.string().optional().describe("id of the plan"),
  lookup_key: z.string().optional().describe("lookup_key of the plan"),
  name: z.string().optional().describe("name of the plan"),
});
