/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoPortalSessionResponse = {
  expires_at?: string | undefined;
  token?: string | undefined;
  url?: string | undefined;
};

export const DtoPortalSessionResponse$zodSchema: z.ZodType<
  DtoPortalSessionResponse
> = z.object({
  expires_at: z.string().optional(),
  token: z.string().optional(),
  url: z.string().optional(),
});
