/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BillingCadence, BillingCadence$zodSchema } from "./billingcadence.js";
import { BillingCycle, BillingCycle$zodSchema } from "./billingcycle.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import {
  ProrationBehavior,
  ProrationBehavior$zodSchema,
} from "./prorationbehavior.js";
import { ScheduleType, ScheduleType$zodSchema } from "./scheduletype.js";

/**
 * Request object for changing a subscription plan (upgrade/downgrade)
 */
export type DtoSubscriptionChangeRequest = {
  billing_cadence: BillingCadence;
  billing_cycle: BillingCycle;
  billing_period: BillingPeriod;
  billing_period_count?: number | undefined;
  change_at?: ScheduleType | undefined;
  metadata?: { [k: string]: string } | undefined;
  proration_behavior: ProrationBehavior;
  target_plan_id: string;
};

export const DtoSubscriptionChangeRequest$zodSchema: z.ZodType<
  DtoSubscriptionChangeRequest
> = z.object({
  billing_cadence: BillingCadence$zodSchema,
  billing_cycle: BillingCycle$zodSchema,
  billing_period: BillingPeriod$zodSchema,
  billing_period_count: z.int().optional(),
  change_at: ScheduleType$zodSchema.optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  proration_behavior: ProrationBehavior$zodSchema,
  target_plan_id: z.string(),
}).describe(
  "Request object for changing a subscription plan (upgrade/downgrade)",
);
