/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoSignUpRequest = {
  email: string;
  password?: string | undefined;
  tenant_name?: string | undefined;
  token?: string | undefined;
};

export const DtoSignUpRequest$zodSchema: z.ZodType<DtoSignUpRequest> = z.object(
  {
    email: z.string(),
    password: z.string().optional(),
    tenant_name: z.string().optional(),
    token: z.string().optional(),
  },
);
