/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SecretProvider, SecretProvider$zodSchema } from "./secretprovider.js";
import { SecretType, SecretType$zodSchema } from "./secrettype.js";
import { Status, Status$zodSchema } from "./status.js";
import { UserType, UserType$zodSchema } from "./usertype.js";

export type DtoSecretResponse = {
  created_at?: string | undefined;
  display_id?: string | undefined;
  expires_at?: string | undefined;
  id?: string | undefined;
  last_used_at?: string | undefined;
  name?: string | undefined;
  provider?: SecretProvider | undefined;
  roles?: Array<string> | undefined;
  status?: Status | undefined;
  type?: SecretType | undefined;
  updated_at?: string | undefined;
  user_type?: UserType | undefined;
};

export const DtoSecretResponse$zodSchema: z.ZodType<DtoSecretResponse> = z
  .object({
    created_at: z.string().optional(),
    display_id: z.string().optional(),
    expires_at: z.string().optional(),
    id: z.string().optional(),
    last_used_at: z.string().optional(),
    name: z.string().optional(),
    provider: SecretProvider$zodSchema.optional(),
    roles: z.array(z.string()).optional(),
    status: Status$zodSchema.optional(),
    type: SecretType$zodSchema.optional(),
    updated_at: z.string().optional(),
    user_type: UserType$zodSchema.optional(),
  });
