/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";

export type DtoSubscriptionSummary = {
  archived_at?: string | undefined;
  billing_anchor?: string | undefined;
  created_at?: string | undefined;
  current_period_end?: string | undefined;
  current_period_start?: string | undefined;
  id?: string | undefined;
  plan_id?: string | undefined;
  status?: SubscriptionStatus | undefined;
};

export const DtoSubscriptionSummary$zodSchema: z.ZodType<
  DtoSubscriptionSummary
> = z.object({
  archived_at: z.string().optional().describe(
    "archived_at timestamp (for old subscriptions)",
  ),
  billing_anchor: z.string().optional().describe(
    "billing_anchor of the subscription",
  ),
  created_at: z.string().optional().describe("created_at timestamp"),
  current_period_end: z.string().optional().describe(
    "current_period_end of the subscription",
  ),
  current_period_start: z.string().optional().describe(
    "current_period_start of the subscription",
  ),
  id: z.string().optional().describe("id of the subscription"),
  plan_id: z.string().optional().describe("plan_id of the subscription"),
  status: SubscriptionStatus$zodSchema.optional(),
});
