/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { S3JobConfig, S3JobConfig$zodSchema } from "./s3jobconfig.js";
import {
  ScheduledTaskEntityType,
  ScheduledTaskEntityType$zodSchema,
} from "./scheduledtaskentitytype.js";
import {
  ScheduledTaskInterval,
  ScheduledTaskInterval$zodSchema,
} from "./scheduledtaskinterval.js";

export type DtoScheduledTaskResponse = {
  connection_id?: string | undefined;
  created_at?: string | undefined;
  enabled?: boolean | undefined;
  entity_type?: ScheduledTaskEntityType | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  interval?: ScheduledTaskInterval | undefined;
  job_config?: S3JobConfig | undefined;
  status?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
};

export const DtoScheduledTaskResponse$zodSchema: z.ZodType<
  DtoScheduledTaskResponse
> = z.object({
  connection_id: z.string().optional(),
  created_at: z.string().optional(),
  enabled: z.boolean().optional(),
  entity_type: ScheduledTaskEntityType$zodSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  interval: ScheduledTaskInterval$zodSchema.optional(),
  job_config: S3JobConfig$zodSchema.optional(),
  status: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
});
