/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { EntityType, EntityType$zodSchema } from "./entitytype.js";
import { FileType, FileType$zodSchema } from "./filetype.js";
import { Status, Status$zodSchema } from "./status.js";
import { TaskStatus, TaskStatus$zodSchema } from "./taskstatus.js";
import { TaskType, TaskType$zodSchema } from "./tasktype.js";

export type DtoTaskResponse = {
  completed_at?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  entity_type?: EntityType | undefined;
  environment_id?: string | undefined;
  error_summary?: string | undefined;
  failed_at?: string | undefined;
  failed_records?: number | undefined;
  file_name?: string | undefined;
  file_type?: FileType | undefined;
  file_url?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  processed_records?: number | undefined;
  scheduled_task_id?: string | undefined;
  started_at?: string | undefined;
  status?: Status | undefined;
  successful_records?: number | undefined;
  task_status?: TaskStatus | undefined;
  task_type?: TaskType | undefined;
  tenant_id?: string | undefined;
  total_records?: number | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  workflow_id?: string | undefined;
};

export const DtoTaskResponse$zodSchema: z.ZodType<DtoTaskResponse> = z.object({
  completed_at: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  entity_type: EntityType$zodSchema.optional(),
  environment_id: z.string().optional(),
  error_summary: z.string().optional(),
  failed_at: z.string().optional(),
  failed_records: z.int().optional(),
  file_name: z.string().optional(),
  file_type: FileType$zodSchema.optional(),
  file_url: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.any()).optional(),
  processed_records: z.int().optional(),
  scheduled_task_id: z.string().optional(),
  started_at: z.string().optional(),
  status: Status$zodSchema.optional(),
  successful_records: z.int().optional(),
  task_status: TaskStatus$zodSchema.optional(),
  task_type: TaskType$zodSchema.optional(),
  tenant_id: z.string().optional(),
  total_records: z.int().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
  workflow_id: z.string().optional(),
});
