/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DtoAlertConfig, DtoAlertConfig$zodSchema } from "./dtoalertconfig.js";
import { TypesAutoTopup, TypesAutoTopup$zodSchema } from "./typesautotopup.js";
import {
  TypesWalletConfig,
  TypesWalletConfig$zodSchema,
} from "./typeswalletconfig.js";

export type DtoUpdateWalletRequest = {
  alert_config?: DtoAlertConfig | undefined;
  alert_enabled?: boolean | undefined;
  auto_topup?: TypesAutoTopup | undefined;
  config?: TypesWalletConfig | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

export const DtoUpdateWalletRequest$zodSchema: z.ZodType<
  DtoUpdateWalletRequest
> = z.object({
  alert_config: DtoAlertConfig$zodSchema.optional(),
  alert_enabled: z.boolean().optional(),
  auto_topup: TypesAutoTopup$zodSchema.optional(),
  config: TypesWalletConfig$zodSchema.optional(),
  description: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
});
