/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TaskStatus, TaskStatus$zodSchema } from "./taskstatus.js";

export type DtoUpdateTaskStatusRequest = { task_status: TaskStatus };

export const DtoUpdateTaskStatusRequest$zodSchema: z.ZodType<
  DtoUpdateTaskStatusRequest
> = z.object({
  task_status: TaskStatus$zodSchema,
});
