/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AlertSettings, AlertSettings$zodSchema } from "./alertsettings.js";
import { MeterFilter, MeterFilter$zodSchema } from "./meterfilter.js";
import { ReportingUnit, ReportingUnit$zodSchema } from "./reportingunit.js";

export type DtoUpdateFeatureRequest = {
  alert_settings?: AlertSettings | undefined;
  description?: string | undefined;
  filters?: Array<MeterFilter> | undefined;
  group_id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  reporting_unit?: ReportingUnit | undefined;
  unit_plural?: string | undefined;
  unit_singular?: string | undefined;
};

export const DtoUpdateFeatureRequest$zodSchema: z.ZodType<
  DtoUpdateFeatureRequest
> = z.object({
  alert_settings: AlertSettings$zodSchema.optional(),
  description: z.string().optional(),
  filters: z.array(MeterFilter$zodSchema).optional(),
  group_id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  reporting_unit: ReportingUnit$zodSchema.optional(),
  unit_plural: z.string().optional(),
  unit_singular: z.string().optional(),
});
