/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTenantResponse,
  DtoTenantResponse$zodSchema,
} from "./dtotenantresponse.js";
import { UserType, UserType$zodSchema } from "./usertype.js";

export type DtoUserResponse = {
  email?: string | undefined;
  id?: string | undefined;
  roles?: Array<string> | undefined;
  tenant?: DtoTenantResponse | undefined;
  type?: UserType | undefined;
};

export const DtoUserResponse$zodSchema: z.ZodType<DtoUserResponse> = z.object({
  email: z.string().optional(),
  id: z.string().optional(),
  roles: z.array(z.string()).optional(),
  tenant: DtoTenantResponse$zodSchema.optional(),
  type: UserType$zodSchema.optional(),
});
