/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AggregationType,
  AggregationType$zodSchema,
} from "./aggregationtype.js";
import { CommitmentInfo, CommitmentInfo$zodSchema } from "./commitmentinfo.js";
import {
  DtoPriceResponse,
  DtoPriceResponse$zodSchema,
} from "./dtopriceresponse.js";
import {
  DtoUsageAnalyticPoint,
  DtoUsageAnalyticPoint$zodSchema,
} from "./dtousageanalyticpoint.js";
import {
  GithubComFlexpriceFlexpriceInternalDomainAddonAddon,
  GithubComFlexpriceFlexpriceInternalDomainAddonAddon$zodSchema,
} from "./githubcomflexpriceflexpriceinternaldomainaddonaddon.js";
import {
  GithubComFlexpriceFlexpriceInternalDomainFeatureFeature,
  GithubComFlexpriceFlexpriceInternalDomainFeatureFeature$zodSchema,
} from "./githubcomflexpriceflexpriceinternaldomainfeaturefeature.js";
import {
  GithubComFlexpriceFlexpriceInternalDomainPlanPlan,
  GithubComFlexpriceFlexpriceInternalDomainPlanPlan$zodSchema,
} from "./githubcomflexpriceflexpriceinternaldomainplanplan.js";
import { GroupGroup, GroupGroup$zodSchema } from "./groupgroup.js";
import { MeterMeter, MeterMeter$zodSchema } from "./metermeter.js";
import { ReportingUnit, ReportingUnit$zodSchema } from "./reportingunit.js";
import {
  SubscriptionSubscriptionLineItem,
  SubscriptionSubscriptionLineItem$zodSchema,
} from "./subscriptionsubscriptionlineitem.js";
import { WindowSize, WindowSize$zodSchema } from "./windowsize.js";

export type DtoUsageAnalyticItem = {
  add_on_id?: string | undefined;
  addon?: GithubComFlexpriceFlexpriceInternalDomainAddonAddon | undefined;
  aggregation_type?: AggregationType | undefined;
  commitment_info?: CommitmentInfo | undefined;
  currency?: string | undefined;
  event_count?: number | undefined;
  event_name?: string | undefined;
  feature?: GithubComFlexpriceFlexpriceInternalDomainFeatureFeature | undefined;
  feature_id?: string | undefined;
  group?: GroupGroup | undefined;
  meter?: MeterMeter | undefined;
  meter_id?: string | undefined;
  name?: string | undefined;
  plan?: GithubComFlexpriceFlexpriceInternalDomainPlanPlan | undefined;
  plan_id?: string | undefined;
  points?: Array<DtoUsageAnalyticPoint> | undefined;
  price?: DtoPriceResponse | undefined;
  price_id?: string | undefined;
  properties?: { [k: string]: string } | undefined;
  reporting_unit?: ReportingUnit | undefined;
  source?: string | undefined;
  sources?: Array<string> | undefined;
  sub_line_item_id?: string | undefined;
  subscription_id?: string | undefined;
  subscription_line_item?: SubscriptionSubscriptionLineItem | undefined;
  total_cost?: string | undefined;
  total_usage?: string | undefined;
  total_usage_display?: string | undefined;
  unit?: string | undefined;
  unit_plural?: string | undefined;
  window_size?: WindowSize | undefined;
};

export const DtoUsageAnalyticItem$zodSchema: z.ZodType<DtoUsageAnalyticItem> = z
  .object({
    add_on_id: z.string().optional(),
    addon: GithubComFlexpriceFlexpriceInternalDomainAddonAddon$zodSchema
      .optional(),
    aggregation_type: AggregationType$zodSchema.optional(),
    commitment_info: CommitmentInfo$zodSchema.optional(),
    currency: z.string().optional(),
    event_count: z.int().optional().describe(
      "Number of events that contributed to this aggregation",
    ),
    event_name: z.string().optional(),
    feature: GithubComFlexpriceFlexpriceInternalDomainFeatureFeature$zodSchema
      .optional(),
    feature_id: z.string().optional(),
    group: GroupGroup$zodSchema.optional(),
    meter: MeterMeter$zodSchema.optional(),
    meter_id: z.string().optional().describe("Meter ID"),
    name: z.string().optional(),
    plan: GithubComFlexpriceFlexpriceInternalDomainPlanPlan$zodSchema
      .optional(),
    plan_id: z.string().optional(),
    points: z.array(DtoUsageAnalyticPoint$zodSchema).optional(),
    price: DtoPriceResponse$zodSchema.optional(),
    price_id: z.string().optional().describe("Price ID used for this usage"),
    properties: z.record(z.string(), z.string()).optional().describe(
      "Stores property values for flexible grouping (e.g., org_id -> \"org123\")",
    ),
    reporting_unit: ReportingUnit$zodSchema.optional(),
    source: z.string().optional(),
    sources: z.array(z.string()).optional().describe(
      "List of sources when not grouping by source",
    ),
    sub_line_item_id: z.string().optional().describe(
      "Subscription line item ID",
    ),
    subscription_id: z.string().optional().describe("Subscription ID"),
    subscription_line_item: SubscriptionSubscriptionLineItem$zodSchema
      .optional(),
    total_cost: z.string().optional(),
    total_usage: z.string().optional(),
    total_usage_display: z.string().optional().describe(
      "Empty string when feature has no reporting unit; otherwise the value in reporting units",
    ),
    unit: z.string().optional(),
    unit_plural: z.string().optional(),
    window_size: WindowSize$zodSchema.optional(),
  });
