/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AlertSettings, AlertSettings$zodSchema } from "./alertsettings.js";
import { AlertState, AlertState$zodSchema } from "./alertstate.js";
import { AutoTopup, AutoTopup$zodSchema } from "./autotopup.js";
import {
  CreditBreakdown,
  CreditBreakdown$zodSchema,
} from "./creditbreakdown.js";
import { Status, Status$zodSchema } from "./status.js";
import { WalletConfig, WalletConfig$zodSchema } from "./walletconfig.js";
import { WalletStatus, WalletStatus$zodSchema } from "./walletstatus.js";
import { WalletType, WalletType$zodSchema } from "./wallettype.js";

export type DtoWalletBalanceResponse = {
  alert_settings?: AlertSettings | undefined;
  alert_state?: AlertState | undefined;
  auto_topup?: AutoTopup | undefined;
  balance?: string | undefined;
  balance_updated_at?: string | undefined;
  config?: WalletConfig | undefined;
  conversion_rate?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  credit_balance?: string | undefined;
  credits_available_breakdown?: CreditBreakdown | undefined;
  currency?: string | undefined;
  current_period_usage?: string | undefined;
  customer_id?: string | undefined;
  description?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  real_time_balance?: string | undefined;
  real_time_credit_balance?: string | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  topup_conversion_rate?: string | undefined;
  unpaid_invoices_amount?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  wallet_status?: WalletStatus | undefined;
  wallet_type?: WalletType | undefined;
};

export const DtoWalletBalanceResponse$zodSchema: z.ZodType<
  DtoWalletBalanceResponse
> = z.object({
  alert_settings: AlertSettings$zodSchema.optional(),
  alert_state: AlertState$zodSchema.optional(),
  auto_topup: AutoTopup$zodSchema.optional(),
  balance: z.string().optional(),
  balance_updated_at: z.string().optional(),
  config: WalletConfig$zodSchema.optional(),
  conversion_rate: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  credit_balance: z.string().optional(),
  credits_available_breakdown: CreditBreakdown$zodSchema.optional(),
  currency: z.string().optional(),
  current_period_usage: z.string().optional(),
  customer_id: z.string().optional(),
  description: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  real_time_balance: z.string().optional(),
  real_time_credit_balance: z.string().optional(),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  topup_conversion_rate: z.string().optional(),
  unpaid_invoices_amount: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
  wallet_status: WalletStatus$zodSchema.optional(),
  wallet_type: WalletType$zodSchema.optional(),
});
