/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  EntitlementEntityType,
  EntitlementEntityType$zodSchema,
} from "./entitlemententitytype.js";
import { FeatureType, FeatureType$zodSchema } from "./featuretype.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";

export const EntitlementFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type EntitlementFilterOrder = ClosedEnum<typeof EntitlementFilterOrder>;

export const EntitlementFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type EntitlementFilter = {
  end_time?: string | undefined;
  entity_ids?: Array<string> | undefined;
  entity_type?: EntitlementEntityType | undefined;
  expand?: string | undefined;
  feature_ids?: Array<string> | undefined;
  feature_type?: FeatureType | undefined;
  filters?: Array<FilterCondition> | undefined;
  is_enabled?: boolean | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: EntitlementFilterOrder | undefined;
  plan_ids?: Array<string> | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
};

export const EntitlementFilter$zodSchema: z.ZodType<EntitlementFilter> = z
  .object({
    end_time: z.string().optional(),
    entity_ids: z.array(z.string()).optional(),
    entity_type: EntitlementEntityType$zodSchema.optional(),
    expand: z.string().optional(),
    feature_ids: z.array(z.string()).optional(),
    feature_type: FeatureType$zodSchema.optional(),
    filters: z.array(FilterCondition$zodSchema).optional(),
    is_enabled: z.boolean().optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: EntitlementFilterOrder$zodSchema.optional(),
    plan_ids: z.array(z.string()).optional(),
    sort: z.array(SortCondition$zodSchema).optional(),
    start_time: z.string().optional(),
    status: Status$zodSchema.optional(),
  });
