/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EntityType = {
  Events: "EVENTS",
  Prices: "PRICES",
  Customers: "CUSTOMERS",
  Features: "FEATURES",
} as const;
export type EntityType = ClosedEnum<typeof EntityType>;

export const EntityType$zodSchema = z.enum([
  "EVENTS",
  "PRICES",
  "CUSTOMERS",
  "FEATURES",
]);
