/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SubModifyInheritanceRequest,
  SubModifyInheritanceRequest$zodSchema,
} from "./submodifyinheritancerequest.js";
import {
  SubModifyQuantityChangeRequest,
  SubModifyQuantityChangeRequest$zodSchema,
} from "./submodifyquantitychangerequest.js";
import {
  SubscriptionModifyType,
  SubscriptionModifyType$zodSchema,
} from "./subscriptionmodifytype.js";

export type ExecuteSubscriptionModifyRequest = {
  inheritance_params?: SubModifyInheritanceRequest | undefined;
  quantity_change_params?: SubModifyQuantityChangeRequest | undefined;
  type: SubscriptionModifyType;
};

export const ExecuteSubscriptionModifyRequest$zodSchema: z.ZodType<
  ExecuteSubscriptionModifyRequest
> = z.object({
  inheritance_params: SubModifyInheritanceRequest$zodSchema.optional(),
  quantity_change_params: SubModifyQuantityChangeRequest$zodSchema.optional(),
  type: SubscriptionModifyType$zodSchema,
});
