/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";

export const FeatureFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type FeatureFilterOrder = ClosedEnum<typeof FeatureFilterOrder>;

export const FeatureFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type FeatureFilter = {
  end_time?: string | undefined;
  expand?: string | undefined;
  feature_ids?: Array<string> | undefined;
  filters?: Array<FilterCondition> | undefined;
  limit?: number | undefined;
  lookup_key?: string | undefined;
  lookup_keys?: Array<string> | undefined;
  meter_ids?: Array<string> | undefined;
  name_contains?: string | undefined;
  offset?: number | undefined;
  order?: FeatureFilterOrder | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
};

export const FeatureFilter$zodSchema: z.ZodType<FeatureFilter> = z.object({
  end_time: z.string().optional(),
  expand: z.string().optional(),
  feature_ids: z.array(z.string()).optional(),
  filters: z.array(FilterCondition$zodSchema).optional(),
  limit: z.int().optional(),
  lookup_key: z.string().optional(),
  lookup_keys: z.array(z.string()).optional(),
  meter_ids: z.array(z.string()).optional(),
  name_contains: z.string().optional(),
  offset: z.int().optional(),
  order: FeatureFilterOrder$zodSchema.optional(),
  sort: z.array(SortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: Status$zodSchema.optional(),
});
