/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListEntitlementsResponse,
  DtoListEntitlementsResponse$zodSchema,
} from "./dtolistentitlementsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetAddonsIdEntitlementsRequest = { id: string };

export const GetAddonsIdEntitlementsRequest$zodSchema: z.ZodType<
  GetAddonsIdEntitlementsRequest
> = z.object({
  id: z.string().describe("Addon ID"),
});

export type GetAddonsIdEntitlementsResponse =
  | DtoListEntitlementsResponse
  | ErrorsErrorResponse;

export const GetAddonsIdEntitlementsResponse$zodSchema: z.ZodType<
  GetAddonsIdEntitlementsResponse
> = z.union([
  DtoListEntitlementsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
