/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoAddonResponse,
  DtoAddonResponse$zodSchema,
} from "./dtoaddonresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetAddonsLookupLookupKeyRequest = { lookup_key: string };

export const GetAddonsLookupLookupKeyRequest$zodSchema: z.ZodType<
  GetAddonsLookupLookupKeyRequest
> = z.object({
  lookup_key: z.string().describe("Addon Lookup Key"),
});

export type GetAddonsLookupLookupKeyResponse =
  | DtoAddonResponse
  | ErrorsErrorResponse;

export const GetAddonsLookupLookupKeyResponse$zodSchema: z.ZodType<
  GetAddonsLookupLookupKeyResponse
> = z.union([
  DtoAddonResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
