/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListAddonsResponse,
  DtoListAddonsResponse$zodSchema,
} from "./dtolistaddonsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const AddonType = {
  Onetime: "onetime",
} as const;
export type AddonType = ClosedEnum<typeof AddonType>;

export const AddonType$zodSchema = z.enum([
  "onetime",
]);

export const GetAddonsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetAddonsOrder = ClosedEnum<typeof GetAddonsOrder>;

export const GetAddonsOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const GetAddonsStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetAddonsStatus = ClosedEnum<typeof GetAddonsStatus>;

export const GetAddonsStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export type GetAddonsRequest = {
  addon_ids?: Array<string> | undefined;
  addon_type?: AddonType | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  lookup_keys?: Array<string> | undefined;
  offset?: number | undefined;
  order?: GetAddonsOrder | undefined;
  start_time?: string | undefined;
  status?: GetAddonsStatus | undefined;
};

export const GetAddonsRequest$zodSchema: z.ZodType<GetAddonsRequest> = z.object(
  {
    addon_ids: z.array(z.string()).optional(),
    addon_type: AddonType$zodSchema.optional(),
    end_time: z.string().optional(),
    expand: z.string().optional(),
    limit: z.int().optional(),
    lookup_keys: z.array(z.string()).optional(),
    offset: z.int().optional(),
    order: GetAddonsOrder$zodSchema.optional(),
    start_time: z.string().optional(),
    status: GetAddonsStatus$zodSchema.optional(),
  },
);

export type GetAddonsResponse = DtoListAddonsResponse | ErrorsErrorResponse;

export const GetAddonsResponse$zodSchema: z.ZodType<GetAddonsResponse> = z
  .union([
    DtoListAddonsResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
