/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerEntitlementsResponse,
  DtoCustomerEntitlementsResponse$zodSchema,
} from "./dtocustomerentitlementsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCustomersIdEntitlementsRequest = {
  id: string;
  feature_ids?: Array<string> | undefined;
  subscription_ids?: Array<string> | undefined;
};

export const GetCustomersIdEntitlementsRequest$zodSchema: z.ZodType<
  GetCustomersIdEntitlementsRequest
> = z.object({
  feature_ids: z.array(z.string()).optional(),
  id: z.string().describe("Customer ID"),
  subscription_ids: z.array(z.string()).optional(),
});

export type GetCustomersIdEntitlementsResponse =
  | DtoCustomerEntitlementsResponse
  | ErrorsErrorResponse;

export const GetCustomersIdEntitlementsResponse$zodSchema: z.ZodType<
  GetCustomersIdEntitlementsResponse
> = z.union([
  DtoCustomerEntitlementsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
