/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetCostsheetResponse,
  DtoGetCostsheetResponse$zodSchema,
} from "./dtogetcostsheetresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCostsIdRequest = { id: string; expand?: string | undefined };

export const GetCostsIdRequest$zodSchema: z.ZodType<GetCostsIdRequest> = z
  .object({
    expand: z.string().describe(
      "Comma-separated list of fields to expand (e.g., 'prices')",
    ).optional(),
    id: z.string().describe("Costsheet ID"),
  });

export type GetCostsIdResponse = DtoGetCostsheetResponse | ErrorsErrorResponse;

export const GetCostsIdResponse$zodSchema: z.ZodType<GetCostsIdResponse> = z
  .union([
    DtoGetCostsheetResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
