/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListCouponsResponse,
  DtoListCouponsResponse$zodSchema,
} from "./dtolistcouponsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const GetCouponsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetCouponsOrder = ClosedEnum<typeof GetCouponsOrder>;

export const GetCouponsOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const GetCouponsStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetCouponsStatus = ClosedEnum<typeof GetCouponsStatus>;

export const GetCouponsStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export type GetCouponsRequest = {
  coupon_ids?: Array<string> | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetCouponsOrder | undefined;
  status?: GetCouponsStatus | undefined;
};

export const GetCouponsRequest$zodSchema: z.ZodType<GetCouponsRequest> = z
  .object({
    coupon_ids: z.array(z.string()).optional(),
    expand: z.string().optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: GetCouponsOrder$zodSchema.optional(),
    status: GetCouponsStatus$zodSchema.optional(),
  });

export type GetCouponsResponse = DtoListCouponsResponse | ErrorsErrorResponse;

export const GetCouponsResponse$zodSchema: z.ZodType<GetCouponsResponse> = z
  .union([
    DtoListCouponsResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
