/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListCustomersResponse,
  DtoListCustomersResponse$zodSchema,
} from "./dtolistcustomersresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const GetCustomersOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetCustomersOrder = ClosedEnum<typeof GetCustomersOrder>;

export const GetCustomersOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const GetCustomersStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetCustomersStatus = ClosedEnum<typeof GetCustomersStatus>;

export const GetCustomersStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export type GetCustomersRequest = {
  customer_ids?: Array<string> | undefined;
  email?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_id?: string | undefined;
  external_ids?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetCustomersOrder | undefined;
  parent_customer_ids?: Array<string> | undefined;
  start_time?: string | undefined;
  status?: GetCustomersStatus | undefined;
};

export const GetCustomersRequest$zodSchema: z.ZodType<GetCustomersRequest> = z
  .object({
    customer_ids: z.array(z.string()).optional(),
    email: z.string().optional(),
    end_time: z.string().optional(),
    expand: z.string().optional(),
    external_id: z.string().optional(),
    external_ids: z.array(z.string()).optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: GetCustomersOrder$zodSchema.optional(),
    parent_customer_ids: z.array(z.string()).optional(),
    start_time: z.string().optional(),
    status: GetCustomersStatus$zodSchema.optional(),
  });

export type GetCustomersResponse =
  | DtoListCustomersResponse
  | ErrorsErrorResponse;

export const GetCustomersResponse$zodSchema: z.ZodType<GetCustomersResponse> = z
  .union([
    DtoListCustomersResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
