/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListCreditGrantsResponse,
  DtoListCreditGrantsResponse$zodSchema,
} from "./dtolistcreditgrantsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const GetCreditgrantsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetCreditgrantsOrder = ClosedEnum<typeof GetCreditgrantsOrder>;

export const GetCreditgrantsOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const GetCreditgrantsScope = {
  Plan: "PLAN",
  Subscription: "SUBSCRIPTION",
} as const;
export type GetCreditgrantsScope = ClosedEnum<typeof GetCreditgrantsScope>;

export const GetCreditgrantsScope$zodSchema = z.enum([
  "PLAN",
  "SUBSCRIPTION",
]);

export const GetCreditgrantsStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetCreditgrantsStatus = ClosedEnum<typeof GetCreditgrantsStatus>;

export const GetCreditgrantsStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export type GetCreditgrantsRequest = {
  end_time?: string | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetCreditgrantsOrder | undefined;
  plan_ids?: Array<string> | undefined;
  scope?: GetCreditgrantsScope | undefined;
  sort?: string | undefined;
  start_time?: string | undefined;
  status?: GetCreditgrantsStatus | undefined;
  subscription_ids?: Array<string> | undefined;
};

export const GetCreditgrantsRequest$zodSchema: z.ZodType<
  GetCreditgrantsRequest
> = z.object({
  end_time: z.string().optional(),
  expand: z.string().optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: GetCreditgrantsOrder$zodSchema.optional(),
  plan_ids: z.array(z.string()).describe("Specific filters for credit grants")
    .optional(),
  scope: GetCreditgrantsScope$zodSchema.optional(),
  sort: z.string().optional(),
  start_time: z.string().optional(),
  status: GetCreditgrantsStatus$zodSchema.optional(),
  subscription_ids: z.array(z.string()).optional(),
});

export type GetCreditgrantsResponse =
  | DtoListCreditGrantsResponse
  | ErrorsErrorResponse;

export const GetCreditgrantsResponse$zodSchema: z.ZodType<
  GetCreditgrantsResponse
> = z.union([
  DtoListCreditGrantsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
