/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListCreditNotesResponse,
  DtoListCreditNotesResponse$zodSchema,
} from "./dtolistcreditnotesresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const CreditNoteStatus = {
  Draft: "DRAFT",
  Finalized: "FINALIZED",
  Voided: "VOIDED",
} as const;
export type CreditNoteStatus = ClosedEnum<typeof CreditNoteStatus>;

export const CreditNoteStatus$zodSchema = z.enum([
  "DRAFT",
  "FINALIZED",
  "VOIDED",
]);

export const CreditNoteType = {
  Adjustment: "ADJUSTMENT",
  Refund: "REFUND",
} as const;
export type CreditNoteType = ClosedEnum<typeof CreditNoteType>;

export const CreditNoteType$zodSchema = z.enum([
  "ADJUSTMENT",
  "REFUND",
]);

export const GetCreditnotesOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetCreditnotesOrder = ClosedEnum<typeof GetCreditnotesOrder>;

export const GetCreditnotesOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const GetCreditnotesStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetCreditnotesStatus = ClosedEnum<typeof GetCreditnotesStatus>;

export const GetCreditnotesStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export type GetCreditnotesRequest = {
  credit_note_ids?: Array<string> | undefined;
  credit_note_status?: Array<CreditNoteStatus> | undefined;
  credit_note_type?: CreditNoteType | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  invoice_id?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetCreditnotesOrder | undefined;
  sort?: string | undefined;
  start_time?: string | undefined;
  status?: GetCreditnotesStatus | undefined;
};

export const GetCreditnotesRequest$zodSchema: z.ZodType<GetCreditnotesRequest> =
  z.object({
    credit_note_ids: z.array(z.string()).optional(),
    credit_note_status: z.array(CreditNoteStatus$zodSchema).optional(),
    credit_note_type: CreditNoteType$zodSchema.optional(),
    end_time: z.string().optional(),
    expand: z.string().optional(),
    invoice_id: z.string().optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: GetCreditnotesOrder$zodSchema.optional(),
    sort: z.string().optional(),
    start_time: z.string().optional(),
    status: GetCreditnotesStatus$zodSchema.optional(),
  });

export type GetCreditnotesResponse =
  | DtoListCreditNotesResponse
  | ErrorsErrorResponse;

export const GetCreditnotesResponse$zodSchema: z.ZodType<
  GetCreditnotesResponse
> = z.union([
  DtoListCreditNotesResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
