/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCustomersWalletsRequest = {
  expand?: string | undefined;
  id?: string | undefined;
  include_real_time_balance?: boolean | undefined;
  lookup_key?: string | undefined;
};

export const GetCustomersWalletsRequest$zodSchema: z.ZodType<
  GetCustomersWalletsRequest
> = z.object({
  expand: z.string().optional(),
  id: z.string().optional(),
  include_real_time_balance: z.boolean().default(false),
  lookup_key: z.string().optional(),
});

export type GetCustomersWalletsResponse =
  | Array<DtoWalletResponse>
  | ErrorsErrorResponse;

export const GetCustomersWalletsResponse$zodSchema: z.ZodType<
  GetCustomersWalletsResponse
> = z.union([
  z.array(DtoWalletResponse$zodSchema).describe("OK"),
  ErrorsErrorResponse$zodSchema,
]);
