/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$zodSchema,
} from "./dtocreditgrantresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCreditgrantsIdRequest = { id: string };

export const GetCreditgrantsIdRequest$zodSchema: z.ZodType<
  GetCreditgrantsIdRequest
> = z.object({
  id: z.string().describe("Credit Grant ID"),
});

export type GetCreditgrantsIdResponse =
  | DtoCreditGrantResponse
  | ErrorsErrorResponse;

export const GetCreditgrantsIdResponse$zodSchema: z.ZodType<
  GetCreditgrantsIdResponse
> = z.union([
  DtoCreditGrantResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
