/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$zodSchema,
} from "./dtocustomerresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCustomersExternalExternalIdRequest = { external_id: string };

export const GetCustomersExternalExternalIdRequest$zodSchema: z.ZodType<
  GetCustomersExternalExternalIdRequest
> = z.object({
  external_id: z.string().describe("Customer External ID"),
});

export type GetCustomersExternalExternalIdResponse =
  | DtoCustomerResponse
  | ErrorsErrorResponse;

export const GetCustomersExternalExternalIdResponse$zodSchema: z.ZodType<
  GetCustomersExternalExternalIdResponse
> = z.union([
  DtoCustomerResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
