/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCustomersIdWalletsRequest = { id: string };

export const GetCustomersIdWalletsRequest$zodSchema: z.ZodType<
  GetCustomersIdWalletsRequest
> = z.object({
  id: z.string().describe("Customer ID"),
});

export type GetCustomersIdWalletsResponse =
  | Array<DtoWalletResponse>
  | ErrorsErrorResponse;

export const GetCustomersIdWalletsResponse$zodSchema: z.ZodType<
  GetCustomersIdWalletsResponse
> = z.union([
  z.array(DtoWalletResponse$zodSchema).describe("OK"),
  ErrorsErrorResponse$zodSchema,
]);
