/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListCreditGrantApplicationsResponse,
  DtoListCreditGrantApplicationsResponse$zodSchema,
} from "./dtolistcreditgrantapplicationsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCustomersIdGrantsUpcomingRequest = { id: string };

export const GetCustomersIdGrantsUpcomingRequest$zodSchema: z.ZodType<
  GetCustomersIdGrantsUpcomingRequest
> = z.object({
  id: z.string().describe("Customer ID"),
});

export type GetCustomersIdGrantsUpcomingResponse =
  | DtoListCreditGrantApplicationsResponse
  | ErrorsErrorResponse;

export const GetCustomersIdGrantsUpcomingResponse$zodSchema: z.ZodType<
  GetCustomersIdGrantsUpcomingResponse
> = z.union([
  DtoListCreditGrantApplicationsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
