/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreditNoteResponse,
  DtoCreditNoteResponse$zodSchema,
} from "./dtocreditnoteresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCreditnotesIdRequest = { id: string };

export const GetCreditnotesIdRequest$zodSchema: z.ZodType<
  GetCreditnotesIdRequest
> = z.object({
  id: z.string().describe("Credit note ID"),
});

export type GetCreditnotesIdResponse =
  | DtoCreditNoteResponse
  | ErrorsErrorResponse;

export const GetCreditnotesIdResponse$zodSchema: z.ZodType<
  GetCreditnotesIdResponse
> = z.union([
  DtoCreditNoteResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
