/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$zodSchema,
} from "./dtocustomerresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCustomersIdRequest = { id: string };

export const GetCustomersIdRequest$zodSchema: z.ZodType<GetCustomersIdRequest> =
  z.object({
    id: z.string().describe("Customer ID"),
  });

export type GetCustomersIdResponse = DtoCustomerResponse | ErrorsErrorResponse;

export const GetCustomersIdResponse$zodSchema: z.ZodType<
  GetCustomersIdResponse
> = z.union([
  DtoCustomerResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
