/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListEntityIntegrationMappingsResponse,
  DtoListEntityIntegrationMappingsResponse$zodSchema,
} from "./dtolistentityintegrationmappingsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetEntityIntegrationMappingsRequest = {
  entity_id?: string | undefined;
  entity_type?: string | undefined;
  provider_type?: string | undefined;
  provider_entity_id?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export const GetEntityIntegrationMappingsRequest$zodSchema: z.ZodType<
  GetEntityIntegrationMappingsRequest
> = z.object({
  entity_id: z.string().describe("Filter by FlexPrice entity ID").optional(),
  entity_type: z.string().describe("Filter by entity type").optional(),
  limit: z.int().describe("Number of results to return (default: 20, max: 100)")
    .optional(),
  offset: z.int().describe("Pagination offset (default: 0)").optional(),
  provider_entity_id: z.string().describe("Filter by provider entity ID")
    .optional(),
  provider_type: z.string().describe("Filter by provider type").optional(),
});

export type GetEntityIntegrationMappingsResponse =
  | DtoListEntityIntegrationMappingsResponse
  | ErrorsErrorResponse;

export const GetEntityIntegrationMappingsResponse$zodSchema: z.ZodType<
  GetEntityIntegrationMappingsResponse
> = z.union([
  DtoListEntityIntegrationMappingsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
