/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$zodSchema,
} from "./dtoentitlementresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetEntitlementsIdRequest = { id: string };

export const GetEntitlementsIdRequest$zodSchema: z.ZodType<
  GetEntitlementsIdRequest
> = z.object({
  id: z.string().describe("Entitlement ID"),
});

export type GetEntitlementsIdResponse =
  | DtoEntitlementResponse
  | ErrorsErrorResponse;

export const GetEntitlementsIdResponse$zodSchema: z.ZodType<
  GetEntitlementsIdResponse
> = z.union([
  DtoEntitlementResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
