/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetMonitoringDataResponse,
  DtoGetMonitoringDataResponse$zodSchema,
} from "./dtogetmonitoringdataresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetEventsMonitoringRequest = { window_size?: string | undefined };

export const GetEventsMonitoringRequest$zodSchema: z.ZodType<
  GetEventsMonitoringRequest
> = z.object({
  window_size: z.string().describe(
    "Window size for time series data (e.g., 'HOUR', 'DAY') - optional",
  ).optional(),
});

export type GetEventsMonitoringResponse =
  | DtoGetMonitoringDataResponse
  | ErrorsErrorResponse;

export const GetEventsMonitoringResponse$zodSchema: z.ZodType<
  GetEventsMonitoringResponse
> = z.union([
  DtoGetMonitoringDataResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
