/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListEntitlementsResponse,
  DtoListEntitlementsResponse$zodSchema,
} from "./dtolistentitlementsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const GetEntitlementsEntityType = {
  Plan: "PLAN",
  Subscription: "SUBSCRIPTION",
  Addon: "ADDON",
} as const;
export type GetEntitlementsEntityType = ClosedEnum<
  typeof GetEntitlementsEntityType
>;

export const GetEntitlementsEntityType$zodSchema = z.enum([
  "PLAN",
  "SUBSCRIPTION",
  "ADDON",
]);

export const FeatureType = {
  Metered: "metered",
  Boolean: "boolean",
  Static: "static",
} as const;
export type FeatureType = ClosedEnum<typeof FeatureType>;

export const FeatureType$zodSchema = z.enum([
  "metered",
  "boolean",
  "static",
]);

export const GetEntitlementsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetEntitlementsOrder = ClosedEnum<typeof GetEntitlementsOrder>;

export const GetEntitlementsOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const GetEntitlementsStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetEntitlementsStatus = ClosedEnum<typeof GetEntitlementsStatus>;

export const GetEntitlementsStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export type GetEntitlementsRequest = {
  end_time?: string | undefined;
  entity_ids?: Array<string> | undefined;
  entity_type?: GetEntitlementsEntityType | undefined;
  expand?: string | undefined;
  feature_ids?: Array<string> | undefined;
  feature_type?: FeatureType | undefined;
  is_enabled?: boolean | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetEntitlementsOrder | undefined;
  plan_ids?: Array<string> | undefined;
  start_time?: string | undefined;
  status?: GetEntitlementsStatus | undefined;
};

export const GetEntitlementsRequest$zodSchema: z.ZodType<
  GetEntitlementsRequest
> = z.object({
  end_time: z.string().optional(),
  entity_ids: z.array(z.string()).optional(),
  entity_type: GetEntitlementsEntityType$zodSchema.optional(),
  expand: z.string().optional(),
  feature_ids: z.array(z.string()).optional(),
  feature_type: FeatureType$zodSchema.optional(),
  is_enabled: z.boolean().optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: GetEntitlementsOrder$zodSchema.optional(),
  plan_ids: z.array(z.string()).optional(),
  start_time: z.string().optional(),
  status: GetEntitlementsStatus$zodSchema.optional(),
});

export type GetEntitlementsResponse =
  | DtoListEntitlementsResponse
  | ErrorsErrorResponse;

export const GetEntitlementsResponse$zodSchema: z.ZodType<
  GetEntitlementsResponse
> = z.union([
  DtoListEntitlementsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
