/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoFeatureResponse,
  DtoFeatureResponse$zodSchema,
} from "./dtofeatureresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetFeaturesIdRequest = { id: string };

export const GetFeaturesIdRequest$zodSchema: z.ZodType<GetFeaturesIdRequest> = z
  .object({
    id: z.string().describe("Feature ID"),
  });

export type GetFeaturesIdResponse = DtoFeatureResponse | ErrorsErrorResponse;

export const GetFeaturesIdResponse$zodSchema: z.ZodType<GetFeaturesIdResponse> =
  z.union([
    DtoFeatureResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
