/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGroupResponse,
  DtoGroupResponse$zodSchema,
} from "./dtogroupresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetGroupsIdRequest = { id: string };

export const GetGroupsIdRequest$zodSchema: z.ZodType<GetGroupsIdRequest> = z
  .object({
    id: z.string().describe("Group ID"),
  });

export type GetGroupsIdResponse = DtoGroupResponse | ErrorsErrorResponse;

export const GetGroupsIdResponse$zodSchema: z.ZodType<GetGroupsIdResponse> = z
  .union([
    DtoGroupResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
