/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";

export type GetInvoicesIdPdfRequest = { id: string; url?: boolean | undefined };

export const GetInvoicesIdPdfRequest$zodSchema: z.ZodType<
  GetInvoicesIdPdfRequest
> = z.object({
  id: z.string().describe("Invoice ID"),
  url: z.boolean().describe("Return presigned URL from s3 instead of PDF")
    .optional(),
});

export type GetInvoicesIdPdfResponse =
  | Uint8Array
  | string
  | Uint8Array
  | string;

export const GetInvoicesIdPdfResponse$zodSchema: z.ZodType<
  GetInvoicesIdPdfResponse
> = z.union([
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
]);
