/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListInvoicesResponse,
  DtoListInvoicesResponse$zodSchema,
} from "./dtolistinvoicesresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const InvoiceStatus = {
  Draft: "DRAFT",
  Finalized: "FINALIZED",
  Voided: "VOIDED",
} as const;
export type InvoiceStatus = ClosedEnum<typeof InvoiceStatus>;

export const InvoiceStatus$zodSchema = z.enum([
  "DRAFT",
  "FINALIZED",
  "VOIDED",
]);

/**
 * invoice_type filters by the nature of the invoice (SUBSCRIPTION, ONE_OFF, or CREDIT)
 *
 * @remarks
 * Use this to separate recurring charges from one-time fees or credit adjustments
 */
export const InvoiceType = {
  Subscription: "SUBSCRIPTION",
  OneOff: "ONE_OFF",
  Credit: "CREDIT",
} as const;
/**
 * invoice_type filters by the nature of the invoice (SUBSCRIPTION, ONE_OFF, or CREDIT)
 *
 * @remarks
 * Use this to separate recurring charges from one-time fees or credit adjustments
 */
export type InvoiceType = ClosedEnum<typeof InvoiceType>;

export const InvoiceType$zodSchema = z.enum([
  "SUBSCRIPTION",
  "ONE_OFF",
  "CREDIT",
]).describe(
  "invoice_type filters by the nature of the invoice (SUBSCRIPTION, ONE_OFF, or CREDIT)\nUse this to separate recurring charges from one-time fees or credit adjustments",
);

export const GetInvoicesOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetInvoicesOrder = ClosedEnum<typeof GetInvoicesOrder>;

export const GetInvoicesOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const PaymentStatus = {
  Initiated: "INITIATED",
  Pending: "PENDING",
  Processing: "PROCESSING",
  Succeeded: "SUCCEEDED",
  Overpaid: "OVERPAID",
  Failed: "FAILED",
  Refunded: "REFUNDED",
  PartiallyRefunded: "PARTIALLY_REFUNDED",
} as const;
export type PaymentStatus = ClosedEnum<typeof PaymentStatus>;

export const PaymentStatus$zodSchema = z.enum([
  "INITIATED",
  "PENDING",
  "PROCESSING",
  "SUCCEEDED",
  "OVERPAID",
  "FAILED",
  "REFUNDED",
  "PARTIALLY_REFUNDED",
]);

export const GetInvoicesStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetInvoicesStatus = ClosedEnum<typeof GetInvoicesStatus>;

export const GetInvoicesStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export type GetInvoicesRequest = {
  amount_due_gt?: number | undefined;
  amount_remaining_gt?: number | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_customer_id?: string | undefined;
  invoice_ids?: Array<string> | undefined;
  invoice_status?: Array<InvoiceStatus> | undefined;
  invoice_type?: InvoiceType | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetInvoicesOrder | undefined;
  payment_status?: Array<PaymentStatus> | undefined;
  skip_line_items?: boolean | undefined;
  start_time?: string | undefined;
  status?: GetInvoicesStatus | undefined;
  subscription_id?: string | undefined;
};

export const GetInvoicesRequest$zodSchema: z.ZodType<GetInvoicesRequest> = z
  .object({
    amount_due_gt: z.number().describe(
      "amount_due_gt filters invoices with a total amount due greater than the specified value\nUseful for finding invoices above a certain threshold or identifying high-value invoices",
    ).optional(),
    amount_remaining_gt: z.number().describe(
      "amount_remaining_gt filters invoices with an outstanding balance greater than the specified value\nUseful for finding invoices that still have significant unpaid amounts",
    ).optional(),
    customer_id: z.string().describe(
      "customer_id filters invoices for a specific customer using FlexPrice's internal customer ID\nThis is the ID returned by FlexPrice when creating or retrieving customers",
    ).optional(),
    end_time: z.string().optional(),
    expand: z.string().optional(),
    external_customer_id: z.string().describe(
      "external_customer_id filters invoices for a customer using your system's customer identifier\nThis is the ID you provided when creating the customer in FlexPrice",
    ).optional(),
    invoice_ids: z.array(z.string()).describe(
      "invoice_ids restricts results to invoices with the specified IDs\nUse this to retrieve specific invoices when you know their exact identifiers",
    ).optional(),
    invoice_status: z.array(InvoiceStatus$zodSchema).describe(
      "invoice_status filters by the current state of invoices in their lifecycle\nMultiple statuses can be specified to include invoices in any of the listed states",
    ).optional(),
    invoice_type: InvoiceType$zodSchema.optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: GetInvoicesOrder$zodSchema.optional(),
    payment_status: z.array(PaymentStatus$zodSchema).describe(
      "payment_status filters by the payment state of invoices\nMultiple statuses can be specified to include invoices with any of the listed payment states",
    ).optional(),
    skip_line_items: z.boolean().describe(
      "SkipLineItems if true, will not include line items in the response",
    ).optional(),
    start_time: z.string().optional(),
    status: GetInvoicesStatus$zodSchema.optional(),
    subscription_id: z.string().describe(
      "subscription_id filters invoices generated for a specific subscription\nOnly returns invoices that were created as part of the specified subscription's billing",
    ).optional(),
  });

export type GetInvoicesResponse = DtoListInvoicesResponse | ErrorsErrorResponse;

export const GetInvoicesResponse$zodSchema: z.ZodType<GetInvoicesResponse> = z
  .union([
    DtoListInvoicesResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
