/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  InvoiceResponse,
  InvoiceResponse$zodSchema,
} from "./invoiceresponse.js";

export type GetMeterUsagePreviewInvoiceResponse =
  | InvoiceResponse
  | ErrorResponse;

export const GetMeterUsagePreviewInvoiceResponse$zodSchema: z.ZodType<
  GetMeterUsagePreviewInvoiceResponse
> = z.union([
  InvoiceResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
