/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceUnitResponse,
  DtoPriceUnitResponse$zodSchema,
} from "./dtopriceunitresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetPricesUnitsIdRequest = { id: string };

export const GetPricesUnitsIdRequest$zodSchema: z.ZodType<
  GetPricesUnitsIdRequest
> = z.object({
  id: z.string().describe("Price unit ID"),
});

export type GetPricesUnitsIdResponse =
  | DtoPriceUnitResponse
  | ErrorsErrorResponse;

export const GetPricesUnitsIdResponse$zodSchema: z.ZodType<
  GetPricesUnitsIdResponse
> = z.union([
  DtoPriceUnitResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
