/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListCreditGrantsResponse,
  DtoListCreditGrantsResponse$zodSchema,
} from "./dtolistcreditgrantsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetPlansIdCreditgrantsRequest = { id: string };

export const GetPlansIdCreditgrantsRequest$zodSchema: z.ZodType<
  GetPlansIdCreditgrantsRequest
> = z.object({
  id: z.string().describe("Plan ID"),
});

export type GetPlansIdCreditgrantsResponse =
  | DtoListCreditGrantsResponse
  | ErrorsErrorResponse;

export const GetPlansIdCreditgrantsResponse$zodSchema: z.ZodType<
  GetPlansIdCreditgrantsResponse
> = z.union([
  DtoListCreditGrantsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
