/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPortalSessionResponse,
  DtoPortalSessionResponse$zodSchema,
} from "./dtoportalsessionresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetPortalExternalIdRequest = { external_id: string };

export const GetPortalExternalIdRequest$zodSchema: z.ZodType<
  GetPortalExternalIdRequest
> = z.object({
  external_id: z.string().describe("Customer External ID"),
});

export type GetPortalExternalIdResponse =
  | DtoPortalSessionResponse
  | ErrorsErrorResponse;

export const GetPortalExternalIdResponse$zodSchema: z.ZodType<
  GetPortalExternalIdResponse
> = z.union([
  DtoPortalSessionResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
