/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPaymentResponse,
  DtoPaymentResponse$zodSchema,
} from "./dtopaymentresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetPaymentsIdRequest = { id: string };

export const GetPaymentsIdRequest$zodSchema: z.ZodType<GetPaymentsIdRequest> = z
  .object({
    id: z.string().describe("Payment ID"),
  });

export type GetPaymentsIdResponse = DtoPaymentResponse | ErrorsErrorResponse;

export const GetPaymentsIdResponse$zodSchema: z.ZodType<GetPaymentsIdResponse> =
  z.union([
    DtoPaymentResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
