/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoAddonAssociationResponse,
  DtoAddonAssociationResponse$zodSchema,
} from "./dtoaddonassociationresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetSubscriptionsIdAddonsAssociationsRequest = { id: string };

export const GetSubscriptionsIdAddonsAssociationsRequest$zodSchema: z.ZodType<
  GetSubscriptionsIdAddonsAssociationsRequest
> = z.object({
  id: z.string().describe("Subscription ID"),
});

export type GetSubscriptionsIdAddonsAssociationsResponse =
  | Array<DtoAddonAssociationResponse>
  | ErrorsErrorResponse;

export const GetSubscriptionsIdAddonsAssociationsResponse$zodSchema: z.ZodType<
  GetSubscriptionsIdAddonsAssociationsResponse
> = z.union([
  z.array(DtoAddonAssociationResponse$zodSchema).describe("OK"),
  ErrorsErrorResponse$zodSchema,
]);
