/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListSubscriptionsResponse,
  DtoListSubscriptionsResponse$zodSchema,
} from "./dtolistsubscriptionsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const BillingCadence = {
  Recurring: "RECURRING",
  Onetime: "ONETIME",
} as const;
export type BillingCadence = ClosedEnum<typeof BillingCadence>;

export const BillingCadence$zodSchema = z.enum([
  "RECURRING",
  "ONETIME",
]);

export const BillingPeriod = {
  Monthly: "MONTHLY",
  Annual: "ANNUAL",
  Weekly: "WEEKLY",
  Daily: "DAILY",
  Quarterly: "QUARTERLY",
  HalfYearly: "HALF_YEARLY",
} as const;
export type BillingPeriod = ClosedEnum<typeof BillingPeriod>;

export const BillingPeriod$zodSchema = z.enum([
  "MONTHLY",
  "ANNUAL",
  "WEEKLY",
  "DAILY",
  "QUARTERLY",
  "HALF_YEARLY",
]);

export const GetSubscriptionsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetSubscriptionsOrder = ClosedEnum<typeof GetSubscriptionsOrder>;

export const GetSubscriptionsOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const GetSubscriptionsStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetSubscriptionsStatus = ClosedEnum<typeof GetSubscriptionsStatus>;

export const GetSubscriptionsStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export const SubscriptionStatus = {
  Active: "active",
  Paused: "paused",
  Cancelled: "cancelled",
  Incomplete: "incomplete",
  Trialing: "trialing",
  Draft: "draft",
} as const;
export type SubscriptionStatus = ClosedEnum<typeof SubscriptionStatus>;

export const SubscriptionStatus$zodSchema = z.enum([
  "active",
  "paused",
  "cancelled",
  "incomplete",
  "trialing",
  "draft",
]);

export type GetSubscriptionsRequest = {
  active_at?: string | undefined;
  billing_cadence?: Array<BillingCadence> | undefined;
  billing_period?: Array<BillingPeriod> | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_customer_id?: string | undefined;
  invoicing_customer_ids?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetSubscriptionsOrder | undefined;
  plan_id?: string | undefined;
  start_time?: string | undefined;
  status?: GetSubscriptionsStatus | undefined;
  subscription_ids?: Array<string> | undefined;
  subscription_status?: Array<SubscriptionStatus> | undefined;
  with_line_items?: boolean | undefined;
};

export const GetSubscriptionsRequest$zodSchema: z.ZodType<
  GetSubscriptionsRequest
> = z.object({
  active_at: z.string().describe(
    "ActiveAt filters subscriptions that are active at the given time",
  ).optional(),
  billing_cadence: z.array(BillingCadence$zodSchema).describe(
    "BillingCadence filters by billing cadence",
  ).optional(),
  billing_period: z.array(BillingPeriod$zodSchema).describe(
    "BillingPeriod filters by billing period",
  ).optional(),
  customer_id: z.string().describe("CustomerID filters by customer ID")
    .optional(),
  end_time: z.string().optional(),
  expand: z.string().optional(),
  external_customer_id: z.string().describe(
    "ExternalCustomerID filters by external customer ID",
  ).optional(),
  invoicing_customer_ids: z.array(z.string()).describe(
    "InvoicingCustomerIDs filters by invoicing customer ID",
  ).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: GetSubscriptionsOrder$zodSchema.optional(),
  plan_id: z.string().describe("PlanID filters by plan ID").optional(),
  start_time: z.string().optional(),
  status: GetSubscriptionsStatus$zodSchema.optional(),
  subscription_ids: z.array(z.string()).optional(),
  subscription_status: z.array(SubscriptionStatus$zodSchema).describe(
    "SubscriptionStatus filters by subscription status",
  ).optional(),
  with_line_items: z.boolean().describe(
    "WithLineItems includes line items in the response",
  ).optional(),
});

export type GetSubscriptionsResponse =
  | DtoListSubscriptionsResponse
  | ErrorsErrorResponse;

export const GetSubscriptionsResponse$zodSchema: z.ZodType<
  GetSubscriptionsResponse
> = z.union([
  DtoListSubscriptionsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
