/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListSecretsResponse,
  DtoListSecretsResponse$zodSchema,
} from "./dtolistsecretsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetSecretsApiKeysRequest = {
  limit?: number | undefined;
  offset?: number | undefined;
  status?: string | undefined;
};

export const GetSecretsApiKeysRequest$zodSchema: z.ZodType<
  GetSecretsApiKeysRequest
> = z.object({
  limit: z.int().describe("Limit").optional(),
  offset: z.int().describe("Offset").optional(),
  status: z.string().describe("Status (published/archived)").optional(),
});

export type GetSecretsApiKeysResponse =
  | DtoListSecretsResponse
  | ErrorsErrorResponse;

export const GetSecretsApiKeysResponse$zodSchema: z.ZodType<
  GetSecretsApiKeysResponse
> = z.union([
  DtoListSecretsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
