/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSubscriptionResponseV2,
  DtoSubscriptionResponseV2$zodSchema,
} from "./dtosubscriptionresponsev2.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetSubscriptionsIdV2Request = {
  id: string;
  expand?: string | undefined;
};

export const GetSubscriptionsIdV2Request$zodSchema: z.ZodType<
  GetSubscriptionsIdV2Request
> = z.object({
  expand: z.string().describe(
    "Comma-separated list of fields to expand (e.g., 'subscription_line_items,prices,plan')",
  ).optional(),
  id: z.string().describe("Subscription ID"),
});

export type GetSubscriptionsIdV2Response =
  | DtoSubscriptionResponseV2
  | ErrorsErrorResponse;

export const GetSubscriptionsIdV2Response$zodSchema: z.ZodType<
  GetSubscriptionsIdV2Response
> = z.union([
  DtoSubscriptionResponseV2$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
