/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSubscriptionEntitlementsResponse,
  DtoSubscriptionEntitlementsResponse$zodSchema,
} from "./dtosubscriptionentitlementsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetSubscriptionsIdEntitlementsRequest = {
  id: string;
  feature_ids?: Array<string> | undefined;
};

export const GetSubscriptionsIdEntitlementsRequest$zodSchema: z.ZodType<
  GetSubscriptionsIdEntitlementsRequest
> = z.object({
  feature_ids: z.array(z.string()).describe("Feature IDs to filter by")
    .optional(),
  id: z.string().describe("Subscription ID"),
});

export type GetSubscriptionsIdEntitlementsResponse =
  | DtoSubscriptionEntitlementsResponse
  | ErrorsErrorResponse;

export const GetSubscriptionsIdEntitlementsResponse$zodSchema: z.ZodType<
  GetSubscriptionsIdEntitlementsResponse
> = z.union([
  DtoSubscriptionEntitlementsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
