/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoLinkedIntegrationsResponse,
  DtoLinkedIntegrationsResponse$zodSchema,
} from "./dtolinkedintegrationsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetSecretsIntegrationsLinkedResponse =
  | DtoLinkedIntegrationsResponse
  | ErrorsErrorResponse;

export const GetSecretsIntegrationsLinkedResponse$zodSchema: z.ZodType<
  GetSecretsIntegrationsLinkedResponse
> = z.union([
  DtoLinkedIntegrationsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
