/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaxAssociationResponse,
  DtoTaxAssociationResponse$zodSchema,
} from "./dtotaxassociationresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetTaxesAssociationsIdRequest = { id: string };

export const GetTaxesAssociationsIdRequest$zodSchema: z.ZodType<
  GetTaxesAssociationsIdRequest
> = z.object({
  id: z.string().describe("Tax Config ID"),
});

export type GetTaxesAssociationsIdResponse =
  | DtoTaxAssociationResponse
  | ErrorsErrorResponse;

export const GetTaxesAssociationsIdResponse$zodSchema: z.ZodType<
  GetTaxesAssociationsIdResponse
> = z.union([
  DtoTaxAssociationResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
