/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaxRateResponse,
  DtoTaxRateResponse$zodSchema,
} from "./dtotaxrateresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetTaxesRatesIdRequest = { id: string };

export const GetTaxesRatesIdRequest$zodSchema: z.ZodType<
  GetTaxesRatesIdRequest
> = z.object({
  id: z.string().describe("Tax rate ID"),
});

export type GetTaxesRatesIdResponse = DtoTaxRateResponse | ErrorsErrorResponse;

export const GetTaxesRatesIdResponse$zodSchema: z.ZodType<
  GetTaxesRatesIdResponse
> = z.union([
  DtoTaxRateResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
