/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaskResponse,
  DtoTaskResponse$zodSchema,
} from "./dtotaskresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetTasksIdRequest = { id: string };

export const GetTasksIdRequest$zodSchema: z.ZodType<GetTasksIdRequest> = z
  .object({
    id: z.string().describe("Task ID"),
  });

export type GetTasksIdResponse = DtoTaskResponse | ErrorsErrorResponse;

export const GetTasksIdResponse$zodSchema: z.ZodType<GetTasksIdResponse> = z
  .union([
    DtoTaskResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
