/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetTasksIdDownloadRequest = { id: string };

export const GetTasksIdDownloadRequest$zodSchema: z.ZodType<
  GetTasksIdDownloadRequest
> = z.object({
  id: z.string().describe("Task ID"),
});

export type GetTasksIdDownloadResponse =
  | { [k: string]: string }
  | ErrorsErrorResponse;

export const GetTasksIdDownloadResponse$zodSchema: z.ZodType<
  GetTasksIdDownloadResponse
> = z.union([
  z.record(z.string(), z.string()).describe("OK"),
  ErrorsErrorResponse$zodSchema,
]);
