/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTenantResponse,
  DtoTenantResponse$zodSchema,
} from "./dtotenantresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetTenantsIdRequest = { id: string };

export const GetTenantsIdRequest$zodSchema: z.ZodType<GetTenantsIdRequest> = z
  .object({
    id: z.string().describe("Tenant ID"),
  });

export type GetTenantsIdResponse = DtoTenantResponse | ErrorsErrorResponse;

export const GetTenantsIdResponse$zodSchema: z.ZodType<GetTenantsIdResponse> = z
  .union([
    DtoTenantResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
