/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListScheduledTasksResponse,
  DtoListScheduledTasksResponse$zodSchema,
} from "./dtolistscheduledtasksresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetTasksScheduledRequest = {
  limit?: number | undefined;
  offset?: number | undefined;
  connection_id?: string | undefined;
  entity_type?: string | undefined;
  interval?: string | undefined;
  enabled?: boolean | undefined;
};

export const GetTasksScheduledRequest$zodSchema: z.ZodType<
  GetTasksScheduledRequest
> = z.object({
  connection_id: z.string().describe("Filter by connection ID").optional(),
  enabled: z.boolean().describe("Filter by enabled status").optional(),
  entity_type: z.string().describe("Filter by entity type").optional(),
  interval: z.string().describe("Filter by interval").optional(),
  limit: z.int().describe("Limit").optional(),
  offset: z.int().describe("Offset").optional(),
});

export type GetTasksScheduledResponse =
  | DtoListScheduledTasksResponse
  | ErrorsErrorResponse;

export const GetTasksScheduledResponse$zodSchema: z.ZodType<
  GetTasksScheduledResponse
> = z.union([
  DtoListScheduledTasksResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
