/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTenantBillingUsage,
  DtoTenantBillingUsage$zodSchema,
} from "./dtotenantbillingusage.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetTenantBillingResponse =
  | DtoTenantBillingUsage
  | ErrorsErrorResponse;

export const GetTenantBillingResponse$zodSchema: z.ZodType<
  GetTenantBillingResponse
> = z.union([
  DtoTenantBillingUsage$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
