/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";
import {
  ModelsTemporalWorkflowResult,
  ModelsTemporalWorkflowResult$zodSchema,
} from "./modelstemporalworkflowresult.js";

export type GetTasksResultRequest = { workflow_id: string };

export const GetTasksResultRequest$zodSchema: z.ZodType<GetTasksResultRequest> =
  z.object({
    workflow_id: z.string().describe("Workflow ID"),
  });

export type GetTasksResultResponse =
  | ModelsTemporalWorkflowResult
  | ErrorsErrorResponse;

export const GetTasksResultResponse$zodSchema: z.ZodType<
  GetTasksResultResponse
> = z.union([
  ModelsTemporalWorkflowResult$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
