/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListTasksResponse,
  DtoListTasksResponse$zodSchema,
} from "./dtolisttasksresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const GetTasksEntityType = {
  Events: "EVENTS",
  Prices: "PRICES",
  Customers: "CUSTOMERS",
  Features: "FEATURES",
} as const;
export type GetTasksEntityType = ClosedEnum<typeof GetTasksEntityType>;

export const GetTasksEntityType$zodSchema = z.enum([
  "EVENTS",
  "PRICES",
  "CUSTOMERS",
  "FEATURES",
]);

export const GetTasksOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetTasksOrder = ClosedEnum<typeof GetTasksOrder>;

export const GetTasksOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const GetTasksStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetTasksStatus = ClosedEnum<typeof GetTasksStatus>;

export const GetTasksStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export const TaskStatus = {
  Pending: "PENDING",
  Processing: "PROCESSING",
  Completed: "COMPLETED",
  Failed: "FAILED",
} as const;
export type TaskStatus = ClosedEnum<typeof TaskStatus>;

export const TaskStatus$zodSchema = z.enum([
  "PENDING",
  "PROCESSING",
  "COMPLETED",
  "FAILED",
]);

export const TaskType = {
  Import: "IMPORT",
  Export: "EXPORT",
} as const;
export type TaskType = ClosedEnum<typeof TaskType>;

export const TaskType$zodSchema = z.enum([
  "IMPORT",
  "EXPORT",
]);

export type GetTasksRequest = {
  created_by?: string | undefined;
  end_time?: string | undefined;
  entity_type?: GetTasksEntityType | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetTasksOrder | undefined;
  scheduled_task_id?: string | undefined;
  sort?: string | undefined;
  start_time?: string | undefined;
  status?: GetTasksStatus | undefined;
  task_status?: TaskStatus | undefined;
  task_type?: TaskType | undefined;
};

export const GetTasksRequest$zodSchema: z.ZodType<GetTasksRequest> = z.object({
  created_by: z.string().optional(),
  end_time: z.string().optional(),
  entity_type: GetTasksEntityType$zodSchema.optional(),
  expand: z.string().optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: GetTasksOrder$zodSchema.optional(),
  scheduled_task_id: z.string().optional(),
  sort: z.string().optional(),
  start_time: z.string().optional(),
  status: GetTasksStatus$zodSchema.optional(),
  task_status: TaskStatus$zodSchema.optional(),
  task_type: TaskType$zodSchema.optional(),
});

export type GetTasksResponse = DtoListTasksResponse | ErrorsErrorResponse;

export const GetTasksResponse$zodSchema: z.ZodType<GetTasksResponse> = z.union([
  DtoListTasksResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
