/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetV1SubscriptionSchedulesIdRequest = { id: string };

export const GetV1SubscriptionSchedulesIdRequest$zodSchema: z.ZodType<
  GetV1SubscriptionSchedulesIdRequest
> = z.object({
  id: z.string().describe("Schedule ID"),
});
