/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";
import {
  TypesListResponseDtoWalletResponse,
  TypesListResponseDtoWalletResponse$zodSchema,
} from "./typeslistresponsedtowalletresponse.js";

export const GetWalletsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetWalletsOrder = ClosedEnum<typeof GetWalletsOrder>;

export const GetWalletsOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const GetWalletsStatus = {
  Active: "active",
  Frozen: "frozen",
  Closed: "closed",
} as const;
export type GetWalletsStatus = ClosedEnum<typeof GetWalletsStatus>;

export const GetWalletsStatus$zodSchema = z.enum([
  "active",
  "frozen",
  "closed",
]);

export type GetWalletsRequest = {
  alert_enabled?: boolean | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetWalletsOrder | undefined;
  sort?: string | undefined;
  status?: GetWalletsStatus | undefined;
  wallet_ids?: Array<string> | undefined;
};

export const GetWalletsRequest$zodSchema: z.ZodType<GetWalletsRequest> = z
  .object({
    alert_enabled: z.boolean().optional(),
    expand: z.string().optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: GetWalletsOrder$zodSchema.optional(),
    sort: z.string().optional(),
    status: GetWalletsStatus$zodSchema.optional(),
    wallet_ids: z.array(z.string()).optional(),
  });

export type GetWalletsResponse =
  | TypesListResponseDtoWalletResponse
  | ErrorsErrorResponse;

export const GetWalletsResponse$zodSchema: z.ZodType<GetWalletsResponse> = z
  .union([
    TypesListResponseDtoWalletResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
