/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetWalletsIdRequest = { id: string };

export const GetWalletsIdRequest$zodSchema: z.ZodType<GetWalletsIdRequest> = z
  .object({
    id: z.string().describe("Wallet ID"),
  });

export type GetWalletsIdResponse = DtoWalletResponse | ErrorsErrorResponse;

export const GetWalletsIdResponse$zodSchema: z.ZodType<GetWalletsIdResponse> = z
  .union([
    DtoWalletResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
