/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const InvoiceBilling = {
  InvoiceToParent: "invoice_to_parent",
  InvoiceToSelf: "invoice_to_self",
} as const;
export type InvoiceBilling = ClosedEnum<typeof InvoiceBilling>;

export const InvoiceBilling$zodSchema = z.enum([
  "invoice_to_parent",
  "invoice_to_self",
]);
