/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type ListResponseDtoWalletResponse = {
  items?: Array<DtoWalletResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const ListResponseDtoWalletResponse$zodSchema: z.ZodType<
  ListResponseDtoWalletResponse
> = z.object({
  items: z.array(DtoWalletResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
