/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PauseMode, PauseMode$zodSchema } from "./pausemode.js";

/**
 * Request object for pausing an active subscription with various pause modes and options
 */
export type PauseSubscriptionRequest = {
  dry_run?: boolean | undefined;
  metadata?: { [k: string]: string } | undefined;
  pause_days?: number | undefined;
  pause_end?: string | undefined;
  pause_mode: PauseMode;
  pause_start?: string | undefined;
  reason?: string | undefined;
};

export const PauseSubscriptionRequest$zodSchema: z.ZodType<
  PauseSubscriptionRequest
> = z.object({
  dry_run: z.boolean().optional().describe(
    "Whether to perform a dry run\n@Description If true, validates the request and shows impact without actually pausing the subscription\n@Example false",
  ),
  metadata: z.record(z.string(), z.string()).optional().describe(
    "Additional metadata as key-value pairs\n@Description Optional metadata for storing additional information about the pause\n@Example {\"requested_by\": \"customer\", \"channel\": \"support_ticket\"}",
  ),
  pause_days: z.int().optional().describe(
    "Duration of the pause in days\n@Description Number of days to pause the subscription. Cannot be used together with pause_end. Must be greater than 0\n@Example 30",
  ),
  pause_end: z.iso.datetime({ offset: true }).optional().describe(
    "End date for the subscription pause\n@Description ISO 8601 timestamp when the pause should end. Cannot be used together with pause_days. Must be after pause_start\n@Example \"2024-02-15T00:00:00Z\"",
  ),
  pause_mode: PauseMode$zodSchema,
  pause_start: z.iso.datetime({ offset: true }).optional().describe(
    "Start date for the subscription pause\n@Description ISO 8601 timestamp when the pause should begin. Required when pause_mode is \"scheduled\"\n@Example \"2024-01-15T00:00:00Z\"",
  ),
  reason: z.string().optional().describe(
    "Reason for pausing the subscription\n@Description Optional reason for the pause. Maximum 255 characters\n@Example \"Customer requested temporary suspension\"",
  ),
}).describe(
  "Request object for pausing an active subscription with various pause modes and options",
);
