/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTopUpWalletRequest,
  DtoTopUpWalletRequest$zodSchema,
} from "./dtotopupwalletrequest.js";
import {
  DtoTopUpWalletResponse,
  DtoTopUpWalletResponse$zodSchema,
} from "./dtotopupwalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostWalletsIdTopUpRequest = {
  id: string;
  body: DtoTopUpWalletRequest;
};

export const PostWalletsIdTopUpRequest$zodSchema: z.ZodType<
  PostWalletsIdTopUpRequest
> = z.object({
  body: DtoTopUpWalletRequest$zodSchema,
  id: z.string().describe("Wallet ID"),
});

export type PostWalletsIdTopUpResponse =
  | DtoTopUpWalletResponse
  | ErrorsErrorResponse;

export const PostWalletsIdTopUpResponse$zodSchema: z.ZodType<
  PostWalletsIdTopUpResponse
> = z.union([
  DtoTopUpWalletResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
