/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostInvoicesIdCommsTriggerRequest = { id: string };

export const PostInvoicesIdCommsTriggerRequest$zodSchema: z.ZodType<
  PostInvoicesIdCommsTriggerRequest
> = z.object({
  id: z.string().describe("Invoice ID"),
});

export type PostInvoicesIdCommsTriggerResponse =
  | DtoSuccessResponse
  | ErrorsErrorResponse;

export const PostInvoicesIdCommsTriggerResponse$zodSchema: z.ZodType<
  PostInvoicesIdCommsTriggerResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
