/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListGroupsResponse,
  DtoListGroupsResponse$zodSchema,
} from "./dtolistgroupsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostGroupsSearchRequest = {
  entity_type?: string | undefined;
  name?: string | undefined;
  lookup_key?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  sort_by?: string | undefined;
  sort_order?: string | undefined;
};

export const PostGroupsSearchRequest$zodSchema: z.ZodType<
  PostGroupsSearchRequest
> = z.object({
  entity_type: z.string().describe("Filter by entity type (e.g., 'price')")
    .optional(),
  limit: z.int().describe("Number of items to return (default: 20)").optional(),
  lookup_key: z.string().describe("Filter by lookup key (exact match)")
    .optional(),
  name: z.string().describe("Filter by group name (contains search)")
    .optional(),
  offset: z.int().describe("Number of items to skip (default: 0)").optional(),
  sort_by: z.string().describe(
    "Field to sort by (name, created_at, updated_at)",
  ).optional(),
  sort_order: z.string().describe("Sort order (asc, desc)").optional(),
});

export type PostGroupsSearchResponse =
  | DtoListGroupsResponse
  | ErrorsErrorResponse;

export const PostGroupsSearchResponse$zodSchema: z.ZodType<
  PostGroupsSearchResponse
> = z.union([
  DtoListGroupsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
