/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListCostsheetResponse,
  DtoListCostsheetResponse$zodSchema,
} from "./dtolistcostsheetresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostCostsSearchResponse =
  | DtoListCostsheetResponse
  | ErrorsErrorResponse;

export const PostCostsSearchResponse$zodSchema: z.ZodType<
  PostCostsSearchResponse
> = z.union([
  DtoListCostsheetResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
