/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostWalletsIdTerminateRequest = { id: string };

export const PostWalletsIdTerminateRequest$zodSchema: z.ZodType<
  PostWalletsIdTerminateRequest
> = z.object({
  id: z.string().describe("Wallet ID"),
});

export type PostWalletsIdTerminateResponse =
  | DtoWalletResponse
  | ErrorsErrorResponse;

export const PostWalletsIdTerminateResponse$zodSchema: z.ZodType<
  PostWalletsIdTerminateResponse
> = z.union([
  DtoWalletResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
