/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSubscriptionChangeExecuteResponse,
  DtoSubscriptionChangeExecuteResponse$zodSchema,
} from "./dtosubscriptionchangeexecuteresponse.js";
import {
  DtoSubscriptionChangeRequest,
  DtoSubscriptionChangeRequest$zodSchema,
} from "./dtosubscriptionchangerequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostSubscriptionsIdChangeExecuteRequest = {
  id: string;
  body: DtoSubscriptionChangeRequest;
};

export const PostSubscriptionsIdChangeExecuteRequest$zodSchema: z.ZodType<
  PostSubscriptionsIdChangeExecuteRequest
> = z.object({
  body: DtoSubscriptionChangeRequest$zodSchema,
  id: z.string().describe("Subscription ID"),
});

export type PostSubscriptionsIdChangeExecuteResponse =
  | DtoSubscriptionChangeExecuteResponse
  | ErrorsErrorResponse;

export const PostSubscriptionsIdChangeExecuteResponse$zodSchema: z.ZodType<
  PostSubscriptionsIdChangeExecuteResponse
> = z.union([
  DtoSubscriptionChangeExecuteResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
