/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";
import {
  ModelsTemporalWorkflowResult,
  ModelsTemporalWorkflowResult$zodSchema,
} from "./modelstemporalworkflowresult.js";

export type PostPlansIdSyncSubscriptionsRequest = { id: string };

export const PostPlansIdSyncSubscriptionsRequest$zodSchema: z.ZodType<
  PostPlansIdSyncSubscriptionsRequest
> = z.object({
  id: z.string().describe("Plan ID"),
});

export type PostPlansIdSyncSubscriptionsResponse =
  | ModelsTemporalWorkflowResult
  | ErrorsErrorResponse;

export const PostPlansIdSyncSubscriptionsResponse$zodSchema: z.ZodType<
  PostPlansIdSyncSubscriptionsResponse
> = z.union([
  ModelsTemporalWorkflowResult$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
