/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PostWebhooksRazorpayTenantIdEnvironmentIdRequest = {
  tenant_id: string;
  environment_id: string;
  xRazorpaySignature: string;
};

export const PostWebhooksRazorpayTenantIdEnvironmentIdRequest$zodSchema:
  z.ZodType<PostWebhooksRazorpayTenantIdEnvironmentIdRequest> = z.object({
    environment_id: z.string().describe("Environment ID"),
    tenant_id: z.string().describe("Tenant ID"),
    xRazorpaySignature: z.string().describe("Razorpay webhook signature"),
  });
