/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListEntitlementsResponse,
  DtoListEntitlementsResponse$zodSchema,
} from "./dtolistentitlementsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEntitlementsSearchResponse =
  | DtoListEntitlementsResponse
  | ErrorsErrorResponse;

export const PostEntitlementsSearchResponse$zodSchema: z.ZodType<
  PostEntitlementsSearchResponse
> = z.union([
  DtoListEntitlementsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
