/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoResumeSubscriptionRequest,
  DtoResumeSubscriptionRequest$zodSchema,
} from "./dtoresumesubscriptionrequest.js";
import {
  DtoSubscriptionPauseResponse,
  DtoSubscriptionPauseResponse$zodSchema,
} from "./dtosubscriptionpauseresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostSubscriptionsIdResumeRequest = {
  id: string;
  body: DtoResumeSubscriptionRequest;
};

export const PostSubscriptionsIdResumeRequest$zodSchema: z.ZodType<
  PostSubscriptionsIdResumeRequest
> = z.object({
  body: DtoResumeSubscriptionRequest$zodSchema,
  id: z.string().describe("Subscription ID"),
});

export type PostSubscriptionsIdResumeResponse =
  | DtoSubscriptionPauseResponse
  | ErrorsErrorResponse;

export const PostSubscriptionsIdResumeResponse$zodSchema: z.ZodType<
  PostSubscriptionsIdResumeResponse
> = z.union([
  DtoSubscriptionPauseResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
