/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreateBulkEntitlementResponse,
  DtoCreateBulkEntitlementResponse$zodSchema,
} from "./dtocreatebulkentitlementresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEntitlementsBulkResponse =
  | DtoCreateBulkEntitlementResponse
  | ErrorsErrorResponse;

export const PostEntitlementsBulkResponse$zodSchema: z.ZodType<
  PostEntitlementsBulkResponse
> = z.union([
  DtoCreateBulkEntitlementResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
