/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PostWebhooksQuickbooksTenantIdEnvironmentIdRequest = {
  tenant_id: string;
  environment_id: string;
  intuitSignature?: string | undefined;
};

export const PostWebhooksQuickbooksTenantIdEnvironmentIdRequest$zodSchema:
  z.ZodType<PostWebhooksQuickbooksTenantIdEnvironmentIdRequest> = z.object({
    environment_id: z.string().describe("Environment ID"),
    intuitSignature: z.string().describe("QuickBooks webhook signature")
      .optional(),
    tenant_id: z.string().describe("Tenant ID"),
  });

export type PostWebhooksQuickbooksTenantIdEnvironmentIdResponse =
  | { [k: string]: any }
  | { [k: string]: any }
  | { [k: string]: any }
  | { [k: string]: any };

export const PostWebhooksQuickbooksTenantIdEnvironmentIdResponse$zodSchema:
  z.ZodType<PostWebhooksQuickbooksTenantIdEnvironmentIdResponse> = z.union([
    z.record(z.string(), z.any()).describe("Webhook processed successfully"),
    z.record(z.string(), z.any()).describe("Bad request"),
    z.record(z.string(), z.any()).describe("Unauthorized - invalid signature"),
    z.record(z.string(), z.any()).describe("Internal server error"),
  ]);
