/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostWalletsResponse = DtoWalletResponse | ErrorsErrorResponse;

export const PostWalletsResponse$zodSchema: z.ZodType<PostWalletsResponse> = z
  .union([
    DtoWalletResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
