/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoAuthResponse,
  DtoAuthResponse$zodSchema,
} from "./dtoauthresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostAuthSignupResponse = DtoAuthResponse | ErrorsErrorResponse;

export const PostAuthSignupResponse$zodSchema: z.ZodType<
  PostAuthSignupResponse
> = z.union([
  DtoAuthResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
