/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEnvironmentResponse,
  DtoEnvironmentResponse$zodSchema,
} from "./dtoenvironmentresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEnvironmentsResponse =
  | DtoEnvironmentResponse
  | ErrorsErrorResponse;

export const PostEnvironmentsResponse$zodSchema: z.ZodType<
  PostEnvironmentsResponse
> = z.union([
  DtoEnvironmentResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
