/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetUsageResponse,
  DtoGetUsageResponse$zodSchema,
} from "./dtogetusageresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEventsUsageMeterResponse =
  | DtoGetUsageResponse
  | ErrorsErrorResponse;

export const PostEventsUsageMeterResponse$zodSchema: z.ZodType<
  PostEventsUsageMeterResponse
> = z.union([
  DtoGetUsageResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
