/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$zodSchema,
} from "./dtoinvoiceresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostInvoicesIdRecalculateRequest = {
  id: string;
  finalize?: boolean | undefined;
};

export const PostInvoicesIdRecalculateRequest$zodSchema: z.ZodType<
  PostInvoicesIdRecalculateRequest
> = z.object({
  finalize: z.boolean().describe(
    "Whether to finalize the invoice after recalculation (default: true)",
  ).optional(),
  id: z.string().describe("Invoice ID"),
});

export type PostInvoicesIdRecalculateResponse =
  | DtoInvoiceResponse
  | ErrorsErrorResponse;

export const PostInvoicesIdRecalculateResponse$zodSchema: z.ZodType<
  PostInvoicesIdRecalculateResponse
> = z.union([
  DtoInvoiceResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
