/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCancelSubscriptionRequest,
  DtoCancelSubscriptionRequest$zodSchema,
} from "./dtocancelsubscriptionrequest.js";
import {
  DtoCancelSubscriptionResponse,
  DtoCancelSubscriptionResponse$zodSchema,
} from "./dtocancelsubscriptionresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostSubscriptionsIdCancelRequest = {
  id: string;
  body: DtoCancelSubscriptionRequest;
};

export const PostSubscriptionsIdCancelRequest$zodSchema: z.ZodType<
  PostSubscriptionsIdCancelRequest
> = z.object({
  body: DtoCancelSubscriptionRequest$zodSchema,
  id: z.string().describe("Subscription ID"),
});

export type PostSubscriptionsIdCancelResponse =
  | DtoCancelSubscriptionResponse
  | ErrorsErrorResponse;

export const PostSubscriptionsIdCancelResponse$zodSchema: z.ZodType<
  PostSubscriptionsIdCancelResponse
> = z.union([
  DtoCancelSubscriptionResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
