/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaxAssociationResponse,
  DtoTaxAssociationResponse$zodSchema,
} from "./dtotaxassociationresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostTaxesAssociationsResponse =
  | DtoTaxAssociationResponse
  | ErrorsErrorResponse;

export const PostTaxesAssociationsResponse$zodSchema: z.ZodType<
  PostTaxesAssociationsResponse
> = z.union([
  DtoTaxAssociationResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
