/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PostWebhooksStripeTenantIdEnvironmentIdRequest = {
  tenant_id: string;
  environment_id: string;
  stripeSignature: string;
};

export const PostWebhooksStripeTenantIdEnvironmentIdRequest$zodSchema:
  z.ZodType<PostWebhooksStripeTenantIdEnvironmentIdRequest> = z.object({
    environment_id: z.string().describe("Environment ID"),
    stripeSignature: z.string().describe("Stripe webhook signature"),
    tenant_id: z.string().describe("Tenant ID"),
  });

export type PostWebhooksStripeTenantIdEnvironmentIdResponse =
  | { [k: string]: any }
  | { [k: string]: any }
  | { [k: string]: any };

export const PostWebhooksStripeTenantIdEnvironmentIdResponse$zodSchema:
  z.ZodType<PostWebhooksStripeTenantIdEnvironmentIdResponse> = z.union([
    z.record(z.string(), z.any()).describe("Webhook processed successfully"),
    z.record(z.string(), z.any()).describe(
      "Bad request - missing parameters or invalid signature",
    ),
    z.record(z.string(), z.any()).describe("Internal server error"),
  ]);
