/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEventsBulkResponse =
  | { [k: string]: string }
  | ErrorsErrorResponse;

export const PostEventsBulkResponse$zodSchema: z.ZodType<
  PostEventsBulkResponse
> = z.union([
  z.record(z.string(), z.string()).describe(
    "message:Event accepted for processing",
  ),
  ErrorsErrorResponse$zodSchema,
]);
