/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";
import {
  TypesListResponseDtoWalletResponse,
  TypesListResponseDtoWalletResponse$zodSchema,
} from "./typeslistresponsedtowalletresponse.js";

export type PostWalletsSearchResponse =
  | TypesListResponseDtoWalletResponse
  | ErrorsErrorResponse;

export const PostWalletsSearchResponse$zodSchema: z.ZodType<
  PostWalletsSearchResponse
> = z.union([
  TypesListResponseDtoWalletResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
