/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListPriceUnitsResponse,
  DtoListPriceUnitsResponse$zodSchema,
} from "./dtolistpriceunitsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostPricesUnitsSearchResponse =
  | DtoListPriceUnitsResponse
  | ErrorsErrorResponse;

export const PostPricesUnitsSearchResponse$zodSchema: z.ZodType<
  PostPricesUnitsSearchResponse
> = z.union([
  DtoListPriceUnitsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
