/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoScheduledTaskResponse,
  DtoScheduledTaskResponse$zodSchema,
} from "./dtoscheduledtaskresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostTasksScheduledResponse =
  | DtoScheduledTaskResponse
  | ErrorsErrorResponse;

export const PostTasksScheduledResponse$zodSchema: z.ZodType<
  PostTasksScheduledResponse
> = z.union([
  DtoScheduledTaskResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
