/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$zodSchema,
} from "./dtocreditgrantresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostCreditgrantsResponse =
  | DtoCreditGrantResponse
  | ErrorsErrorResponse;

export const PostCreditgrantsResponse$zodSchema: z.ZodType<
  PostCreditgrantsResponse
> = z.union([
  DtoCreditGrantResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
