/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListInvoicesResponse,
  DtoListInvoicesResponse$zodSchema,
} from "./dtolistinvoicesresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostInvoicesSearchResponse =
  | DtoListInvoicesResponse
  | ErrorsErrorResponse;

export const PostInvoicesSearchResponse$zodSchema: z.ZodType<
  PostInvoicesSearchResponse
> = z.union([
  DtoListInvoicesResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
