/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoAddonAssociationResponse,
  DtoAddonAssociationResponse$zodSchema,
} from "./dtoaddonassociationresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostSubscriptionsAddonResponse =
  | DtoAddonAssociationResponse
  | ErrorsErrorResponse;

export const PostSubscriptionsAddonResponse$zodSchema: z.ZodType<
  PostSubscriptionsAddonResponse
> = z.union([
  DtoAddonAssociationResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
