/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetUsageAnalyticsResponse,
  DtoGetUsageAnalyticsResponse$zodSchema,
} from "./dtogetusageanalyticsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEventsAnalyticsResponse =
  | DtoGetUsageAnalyticsResponse
  | ErrorsErrorResponse;

export const PostEventsAnalyticsResponse$zodSchema: z.ZodType<
  PostEventsAnalyticsResponse
> = z.union([
  DtoGetUsageAnalyticsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
