/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListFeaturesResponse,
  DtoListFeaturesResponse$zodSchema,
} from "./dtolistfeaturesresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostFeaturesSearchResponse =
  | DtoListFeaturesResponse
  | ErrorsErrorResponse;

export const PostFeaturesSearchResponse$zodSchema: z.ZodType<
  PostFeaturesSearchResponse
> = z.union([
  DtoListFeaturesResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
