/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreditNoteResponse,
  DtoCreditNoteResponse$zodSchema,
} from "./dtocreditnoteresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostCreditnotesIdVoidRequest = { id: string };

export const PostCreditnotesIdVoidRequest$zodSchema: z.ZodType<
  PostCreditnotesIdVoidRequest
> = z.object({
  id: z.string().describe("Credit note ID"),
});

export type PostCreditnotesIdVoidResponse =
  | DtoCreditNoteResponse
  | ErrorsErrorResponse;

export const PostCreditnotesIdVoidResponse$zodSchema: z.ZodType<
  PostCreditnotesIdVoidResponse
> = z.union([
  DtoCreditNoteResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
