/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPaymentResponse,
  DtoPaymentResponse$zodSchema,
} from "./dtopaymentresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostPaymentsIdProcessRequest = { id: string };

export const PostPaymentsIdProcessRequest$zodSchema: z.ZodType<
  PostPaymentsIdProcessRequest
> = z.object({
  id: z.string().describe("Payment ID"),
});

export type PostPaymentsIdProcessResponse =
  | DtoPaymentResponse
  | ErrorsErrorResponse;

export const PostPaymentsIdProcessResponse$zodSchema: z.ZodType<
  PostPaymentsIdProcessResponse
> = z.union([
  DtoPaymentResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
