/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PostWebhooksHubspotTenantIdEnvironmentIdRequest = {
  tenant_id: string;
  environment_id: string;
  xHubSpotSignatureV3: string;
};

export const PostWebhooksHubspotTenantIdEnvironmentIdRequest$zodSchema:
  z.ZodType<PostWebhooksHubspotTenantIdEnvironmentIdRequest> = z.object({
    environment_id: z.string().describe("Environment ID"),
    tenant_id: z.string().describe("Tenant ID"),
    xHubSpotSignatureV3: z.string().describe("HubSpot webhook signature"),
  });
