/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$zodSchema,
} from "./dtoinvoiceresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostInvoicesResponse = DtoInvoiceResponse | ErrorsErrorResponse;

export const PostInvoicesResponse$zodSchema: z.ZodType<PostInvoicesResponse> = z
  .union([
    DtoInvoiceResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
