/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListConnectionsResponse,
  DtoListConnectionsResponse$zodSchema,
} from "./dtolistconnectionsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostConnectionsSearchResponse =
  | DtoListConnectionsResponse
  | ErrorsErrorResponse;

export const PostConnectionsSearchResponse$zodSchema: z.ZodType<
  PostConnectionsSearchResponse
> = z.union([
  DtoListConnectionsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
