/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoUserResponse,
  DtoUserResponse$zodSchema,
} from "./dtouserresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostUsersResponse = DtoUserResponse | ErrorsErrorResponse;

export const PostUsersResponse$zodSchema: z.ZodType<PostUsersResponse> = z
  .union([
    DtoUserResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
