/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$zodSchema,
} from "./dtoentitlementresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEntitlementsResponse =
  | DtoEntitlementResponse
  | ErrorsErrorResponse;

export const PostEntitlementsResponse$zodSchema: z.ZodType<
  PostEntitlementsResponse
> = z.union([
  DtoEntitlementResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
