/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEventsResponse = { [k: string]: string } | ErrorsErrorResponse;

export const PostEventsResponse$zodSchema: z.ZodType<PostEventsResponse> = z
  .union([
    z.record(z.string(), z.string()).describe(
      "message:Event accepted for processing",
    ),
    ErrorsErrorResponse$zodSchema,
  ]);
