/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListSubscriptionsResponse,
  DtoListSubscriptionsResponse$zodSchema,
} from "./dtolistsubscriptionsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostSubscriptionsSearchResponse =
  | DtoListSubscriptionsResponse
  | ErrorsErrorResponse;

export const PostSubscriptionsSearchResponse$zodSchema: z.ZodType<
  PostSubscriptionsSearchResponse
> = z.union([
  DtoListSubscriptionsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
