/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCancelScheduleRequest,
  DtoCancelScheduleRequest$zodSchema,
} from "./dtocancelschedulerequest.js";

export type PostV1SubscriptionsSchedulesScheduleIdCancelRequest = {
  schedule_id: string;
  body?: DtoCancelScheduleRequest | undefined;
};

export const PostV1SubscriptionsSchedulesScheduleIdCancelRequest$zodSchema:
  z.ZodType<PostV1SubscriptionsSchedulesScheduleIdCancelRequest> = z.object({
    body: DtoCancelScheduleRequest$zodSchema.optional(),
    schedule_id: z.string().describe(
      "Schedule ID (optional if using request body)",
    ),
  });
