/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoActivateDraftSubscriptionRequest,
  DtoActivateDraftSubscriptionRequest$zodSchema,
} from "./dtoactivatedraftsubscriptionrequest.js";
import {
  DtoSubscriptionResponse,
  DtoSubscriptionResponse$zodSchema,
} from "./dtosubscriptionresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostSubscriptionsIdActivateRequest = {
  id: string;
  body: DtoActivateDraftSubscriptionRequest;
};

export const PostSubscriptionsIdActivateRequest$zodSchema: z.ZodType<
  PostSubscriptionsIdActivateRequest
> = z.object({
  body: DtoActivateDraftSubscriptionRequest$zodSchema,
  id: z.string().describe("Subscription ID"),
});

export type PostSubscriptionsIdActivateResponse =
  | DtoSubscriptionResponse
  | ErrorsErrorResponse;

export const PostSubscriptionsIdActivateResponse$zodSchema: z.ZodType<
  PostSubscriptionsIdActivateResponse
> = z.union([
  DtoSubscriptionResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
