/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListUsersResponse,
  DtoListUsersResponse$zodSchema,
} from "./dtolistusersresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostUsersSearchResponse =
  | DtoListUsersResponse
  | ErrorsErrorResponse;

export const PostUsersSearchResponse$zodSchema: z.ZodType<
  PostUsersSearchResponse
> = z.union([
  DtoListUsersResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
