/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetDetailedCostAnalyticsResponse,
  DtoGetDetailedCostAnalyticsResponse$zodSchema,
} from "./dtogetdetailedcostanalyticsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostCostsAnalyticsV2Response =
  | DtoGetDetailedCostAnalyticsResponse
  | ErrorsErrorResponse;

export const PostCostsAnalyticsV2Response$zodSchema: z.ZodType<
  PostCostsAnalyticsV2Response
> = z.union([
  DtoGetDetailedCostAnalyticsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
