/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPaymentResponse,
  DtoPaymentResponse$zodSchema,
} from "./dtopaymentresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostPaymentsResponse = DtoPaymentResponse | ErrorsErrorResponse;

export const PostPaymentsResponse$zodSchema: z.ZodType<PostPaymentsResponse> = z
  .union([
    DtoPaymentResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
