/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaskResponse,
  DtoTaskResponse$zodSchema,
} from "./dtotaskresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostTasksResponse = DtoTaskResponse | ErrorsErrorResponse;

export const PostTasksResponse$zodSchema: z.ZodType<PostTasksResponse> = z
  .union([
    DtoTaskResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
