/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ClonePlanRequest,
  ClonePlanRequest$zodSchema,
} from "./cloneplanrequest.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { PlanResponse, PlanResponse$zodSchema } from "./planresponse.js";

export type PostPlansIdCloneRequest = { id: string; body: ClonePlanRequest };

export const PostPlansIdCloneRequest$zodSchema: z.ZodType<
  PostPlansIdCloneRequest
> = z.object({
  body: ClonePlanRequest$zodSchema.describe("Clone configuration"),
  id: z.string().describe("Source Plan ID"),
});

export type PostPlansIdCloneResponse = PlanResponse | ErrorResponse;

export const PostPlansIdCloneResponse$zodSchema: z.ZodType<
  PostPlansIdCloneResponse
> = z.union([
  PlanResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
