/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetEventsResponse,
  DtoGetEventsResponse$zodSchema,
} from "./dtogeteventsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEventsQueryResponse =
  | DtoGetEventsResponse
  | ErrorsErrorResponse;

export const PostEventsQueryResponse$zodSchema: z.ZodType<
  PostEventsQueryResponse
> = z.union([
  DtoGetEventsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
