/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGroupResponse,
  DtoGroupResponse$zodSchema,
} from "./dtogroupresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostGroupsResponse = DtoGroupResponse | ErrorsErrorResponse;

export const PostGroupsResponse$zodSchema: z.ZodType<PostGroupsResponse> = z
  .union([
    DtoGroupResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
