/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntityIntegrationMappingResponse,
  DtoEntityIntegrationMappingResponse$zodSchema,
} from "./dtoentityintegrationmappingresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEntityIntegrationMappingsResponse =
  | DtoEntityIntegrationMappingResponse
  | ErrorsErrorResponse;

export const PostEntityIntegrationMappingsResponse$zodSchema: z.ZodType<
  PostEntityIntegrationMappingsResponse
> = z.union([
  DtoEntityIntegrationMappingResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
