/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetUsageResponse,
  DtoGetUsageResponse$zodSchema,
} from "./dtogetusageresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostEventsUsageResponse = DtoGetUsageResponse | ErrorsErrorResponse;

export const PostEventsUsageResponse$zodSchema: z.ZodType<
  PostEventsUsageResponse
> = z.union([
  DtoGetUsageResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
