/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";

export const PriceUnitFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type PriceUnitFilterOrder = ClosedEnum<typeof PriceUnitFilterOrder>;

export const PriceUnitFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type PriceUnitFilter = {
  end_time?: string | undefined;
  expand?: string | undefined;
  filters?: Array<FilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: PriceUnitFilterOrder | undefined;
  price_unit_ids?: Array<string> | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
};

export const PriceUnitFilter$zodSchema: z.ZodType<PriceUnitFilter> = z.object({
  end_time: z.string().optional(),
  expand: z.string().optional(),
  filters: z.array(FilterCondition$zodSchema).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: PriceUnitFilterOrder$zodSchema.optional(),
  price_unit_ids: z.array(z.string()).optional(),
  sort: z.array(SortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: Status$zodSchema.optional(),
});
