/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$zodSchema,
} from "./dtocustomerresponse.js";
import {
  DtoUpdateCustomerRequest,
  DtoUpdateCustomerRequest$zodSchema,
} from "./dtoupdatecustomerrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutCustomersRequest = {
  id?: string | undefined;
  external_customer_id?: string | undefined;
  body: DtoUpdateCustomerRequest;
};

export const PutCustomersRequest$zodSchema: z.ZodType<PutCustomersRequest> = z
  .object({
    body: DtoUpdateCustomerRequest$zodSchema,
    external_customer_id: z.string().describe("Customer External ID")
      .optional(),
    id: z.string().describe("Customer ID").optional(),
  });

export type PutCustomersResponse = DtoCustomerResponse | ErrorsErrorResponse;

export const PutCustomersResponse$zodSchema: z.ZodType<PutCustomersResponse> = z
  .union([
    DtoCustomerResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
