/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoConnectionResponse,
  DtoConnectionResponse$zodSchema,
} from "./dtoconnectionresponse.js";
import {
  DtoUpdateConnectionRequest,
  DtoUpdateConnectionRequest$zodSchema,
} from "./dtoupdateconnectionrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutConnectionsIdRequest = {
  id: string;
  body: DtoUpdateConnectionRequest;
};

export const PutConnectionsIdRequest$zodSchema: z.ZodType<
  PutConnectionsIdRequest
> = z.object({
  body: DtoUpdateConnectionRequest$zodSchema,
  id: z.string().describe("Connection ID"),
});

export type PutConnectionsIdResponse =
  | DtoConnectionResponse
  | ErrorsErrorResponse;

export const PutConnectionsIdResponse$zodSchema: z.ZodType<
  PutConnectionsIdResponse
> = z.union([
  DtoConnectionResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
