/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$zodSchema,
} from "./dtoentitlementresponse.js";
import {
  DtoUpdateEntitlementRequest,
  DtoUpdateEntitlementRequest$zodSchema,
} from "./dtoupdateentitlementrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutEntitlementsIdRequest = {
  id: string;
  body: DtoUpdateEntitlementRequest;
};

export const PutEntitlementsIdRequest$zodSchema: z.ZodType<
  PutEntitlementsIdRequest
> = z.object({
  body: DtoUpdateEntitlementRequest$zodSchema,
  id: z.string().describe("Entitlement ID"),
});

export type PutEntitlementsIdResponse =
  | DtoEntitlementResponse
  | ErrorsErrorResponse;

export const PutEntitlementsIdResponse$zodSchema: z.ZodType<
  PutEntitlementsIdResponse
> = z.union([
  DtoEntitlementResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
