/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEnvironmentResponse,
  DtoEnvironmentResponse$zodSchema,
} from "./dtoenvironmentresponse.js";
import {
  DtoUpdateEnvironmentRequest,
  DtoUpdateEnvironmentRequest$zodSchema,
} from "./dtoupdateenvironmentrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutEnvironmentsIdRequest = {
  id: string;
  body: DtoUpdateEnvironmentRequest;
};

export const PutEnvironmentsIdRequest$zodSchema: z.ZodType<
  PutEnvironmentsIdRequest
> = z.object({
  body: DtoUpdateEnvironmentRequest$zodSchema,
  id: z.string().describe("Environment ID"),
});

export type PutEnvironmentsIdResponse =
  | DtoEnvironmentResponse
  | ErrorsErrorResponse;

export const PutEnvironmentsIdResponse$zodSchema: z.ZodType<
  PutEnvironmentsIdResponse
> = z.union([
  DtoEnvironmentResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
