/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoFeatureResponse,
  DtoFeatureResponse$zodSchema,
} from "./dtofeatureresponse.js";
import {
  DtoUpdateFeatureRequest,
  DtoUpdateFeatureRequest$zodSchema,
} from "./dtoupdatefeaturerequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutFeaturesIdRequest = {
  id: string;
  body: DtoUpdateFeatureRequest;
};

export const PutFeaturesIdRequest$zodSchema: z.ZodType<PutFeaturesIdRequest> = z
  .object({
    body: DtoUpdateFeatureRequest$zodSchema,
    id: z.string().describe("Feature ID"),
  });

export type PutFeaturesIdResponse = DtoFeatureResponse | ErrorsErrorResponse;

export const PutFeaturesIdResponse$zodSchema: z.ZodType<PutFeaturesIdResponse> =
  z.union([
    DtoFeatureResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
