/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$zodSchema,
} from "./dtoinvoiceresponse.js";
import {
  DtoUpdatePaymentStatusRequest,
  DtoUpdatePaymentStatusRequest$zodSchema,
} from "./dtoupdatepaymentstatusrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutInvoicesIdPaymentRequest = {
  id: string;
  body: DtoUpdatePaymentStatusRequest;
};

export const PutInvoicesIdPaymentRequest$zodSchema: z.ZodType<
  PutInvoicesIdPaymentRequest
> = z.object({
  body: DtoUpdatePaymentStatusRequest$zodSchema,
  id: z.string().describe("Invoice ID"),
});

export type PutInvoicesIdPaymentResponse =
  | DtoInvoiceResponse
  | ErrorsErrorResponse;

export const PutInvoicesIdPaymentResponse$zodSchema: z.ZodType<
  PutInvoicesIdPaymentResponse
> = z.union([
  DtoInvoiceResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
