/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  DtoUpdateTaskStatusRequest,
  DtoUpdateTaskStatusRequest$zodSchema,
} from "./dtoupdatetaskstatusrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutTasksIdStatusRequest = {
  id: string;
  body: DtoUpdateTaskStatusRequest;
};

export const PutTasksIdStatusRequest$zodSchema: z.ZodType<
  PutTasksIdStatusRequest
> = z.object({
  body: DtoUpdateTaskStatusRequest$zodSchema,
  id: z.string().describe("Task ID"),
});

export type PutTasksIdStatusResponse = DtoSuccessResponse | ErrorsErrorResponse;

export const PutTasksIdStatusResponse$zodSchema: z.ZodType<
  PutTasksIdStatusResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
