/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoScheduledTaskResponse,
  DtoScheduledTaskResponse$zodSchema,
} from "./dtoscheduledtaskresponse.js";
import {
  DtoUpdateScheduledTaskRequest,
  DtoUpdateScheduledTaskRequest$zodSchema,
} from "./dtoupdatescheduledtaskrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutTasksScheduledIdRequest = {
  id: string;
  body: DtoUpdateScheduledTaskRequest;
};

export const PutTasksScheduledIdRequest$zodSchema: z.ZodType<
  PutTasksScheduledIdRequest
> = z.object({
  body: DtoUpdateScheduledTaskRequest$zodSchema,
  id: z.string().describe("Scheduled Task ID"),
});

export type PutTasksScheduledIdResponse =
  | DtoScheduledTaskResponse
  | ErrorsErrorResponse;

export const PutTasksScheduledIdResponse$zodSchema: z.ZodType<
  PutTasksScheduledIdResponse
> = z.union([
  DtoScheduledTaskResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
