/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaxRateResponse,
  DtoTaxRateResponse$zodSchema,
} from "./dtotaxrateresponse.js";
import {
  DtoUpdateTaxRateRequest,
  DtoUpdateTaxRateRequest$zodSchema,
} from "./dtoupdatetaxraterequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutTaxesRatesIdRequest = {
  id: string;
  body: DtoUpdateTaxRateRequest;
};

export const PutTaxesRatesIdRequest$zodSchema: z.ZodType<
  PutTaxesRatesIdRequest
> = z.object({
  body: DtoUpdateTaxRateRequest$zodSchema,
  id: z.string().describe("Tax rate ID"),
});

export type PutTaxesRatesIdResponse = DtoTaxRateResponse | ErrorsErrorResponse;

export const PutTaxesRatesIdResponse$zodSchema: z.ZodType<
  PutTaxesRatesIdResponse
> = z.union([
  DtoTaxRateResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
