/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTenantResponse,
  DtoTenantResponse$zodSchema,
} from "./dtotenantresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutTenantsUpdateResponse = DtoTenantResponse | ErrorsErrorResponse;

export const PutTenantsUpdateResponse$zodSchema: z.ZodType<
  PutTenantsUpdateResponse
> = z.union([
  DtoTenantResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
