/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoUpdateWalletRequest,
  DtoUpdateWalletRequest$zodSchema,
} from "./dtoupdatewalletrequest.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PutWalletsIdRequest = { id: string; body: DtoUpdateWalletRequest };

export const PutWalletsIdRequest$zodSchema: z.ZodType<PutWalletsIdRequest> = z
  .object({
    body: DtoUpdateWalletRequest$zodSchema,
    id: z.string().describe("Wallet ID"),
  });

export type PutWalletsIdResponse = DtoWalletResponse | ErrorsErrorResponse;

export const PutWalletsIdResponse$zodSchema: z.ZodType<PutWalletsIdResponse> = z
  .union([
    DtoWalletResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
