/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Status, Status$zodSchema } from "./status.js";

export const QueryFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type QueryFilterOrder = ClosedEnum<typeof QueryFilterOrder>;

export const QueryFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type QueryFilter = {
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: QueryFilterOrder | undefined;
  sort?: string | undefined;
  status?: Status | undefined;
};

export const QueryFilter$zodSchema: z.ZodType<QueryFilter> = z.object({
  expand: z.string().optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: QueryFilterOrder$zodSchema.optional(),
  sort: z.string().optional(),
  status: Status$zodSchema.optional(),
});
