/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";
import {
  ListResponseDtoWalletResponse,
  ListResponseDtoWalletResponse$zodSchema,
} from "./listresponsedtowalletresponse.js";

export type QueryWalletResponse =
  | ListResponseDtoWalletResponse
  | ErrorsErrorResponse;

export const QueryWalletResponse$zodSchema: z.ZodType<QueryWalletResponse> = z
  .union([
    ListResponseDtoWalletResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
