/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$zodSchema,
} from "./dtoinvoiceresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type RecalculateInvoiceV2Request = {
  id: string;
  finalize?: boolean | undefined;
};

export const RecalculateInvoiceV2Request$zodSchema: z.ZodType<
  RecalculateInvoiceV2Request
> = z.object({
  finalize: z.boolean().describe(
    "Whether to finalize the invoice after recalculation (default: true)",
  ).optional(),
  id: z.string().describe("Invoice ID"),
});

export type RecalculateInvoiceV2Response =
  | DtoInvoiceResponse
  | ErrorsErrorResponse;

export const RecalculateInvoiceV2Response$zodSchema: z.ZodType<
  RecalculateInvoiceV2Response
> = z.union([
  DtoInvoiceResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
