/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RemoveAddonRequest = {
  addon_association_id: string;
  reason?: string | undefined;
};

export const RemoveAddonRequest$zodSchema: z.ZodType<RemoveAddonRequest> = z
  .object({
    addon_association_id: z.string(),
    reason: z.string().optional(),
  });
