/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const S3CompressionType = {
  None: "none",
  Gzip: "gzip",
} as const;
export type S3CompressionType = ClosedEnum<typeof S3CompressionType>;

export const S3CompressionType$zodSchema = z.enum([
  "none",
  "gzip",
]);
