/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ScheduledTaskEntityType = {
  Events: "events",
  Invoice: "invoice",
  CreditTopups: "credit_topups",
  CreditUsage: "credit_usage",
} as const;
export type ScheduledTaskEntityType = ClosedEnum<
  typeof ScheduledTaskEntityType
>;

export const ScheduledTaskEntityType$zodSchema = z.enum([
  "events",
  "invoice",
  "credit_topups",
  "credit_usage",
]);
