/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ScheduledTaskInterval = {
  FifteenMIN: "15MIN",
  Custom: "custom",
  Hourly: "hourly",
  Daily: "daily",
} as const;
export type ScheduledTaskInterval = ClosedEnum<typeof ScheduledTaskInterval>;

export const ScheduledTaskInterval$zodSchema = z.enum([
  "15MIN",
  "custom",
  "hourly",
  "daily",
]);
