/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SecretType = {
  PrivateKey: "private_key",
  PublishableKey: "publishable_key",
  Integration: "integration",
} as const;
export type SecretType = ClosedEnum<typeof SecretType>;

export const SecretType$zodSchema = z.enum([
  "private_key",
  "publishable_key",
  "integration",
]);
