/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BillingCadence, BillingCadence$zodSchema } from "./billingcadence.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";

export const SubscriptionFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type SubscriptionFilterOrder = ClosedEnum<
  typeof SubscriptionFilterOrder
>;

export const SubscriptionFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type SubscriptionFilter = {
  active_at?: string | undefined;
  billing_cadence?: Array<BillingCadence> | undefined;
  billing_period?: Array<BillingPeriod> | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_customer_id?: string | undefined;
  filters?: Array<FilterCondition> | undefined;
  invoicing_customer_ids?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: SubscriptionFilterOrder | undefined;
  parent_subscription_ids?: Array<string> | undefined;
  plan_id?: string | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
  subscription_ids?: Array<string> | undefined;
  subscription_status?: Array<SubscriptionStatus> | undefined;
  with_line_items?: boolean | undefined;
};

export const SubscriptionFilter$zodSchema: z.ZodType<SubscriptionFilter> = z
  .object({
    active_at: z.string().optional(),
    billing_cadence: z.array(BillingCadence$zodSchema).optional(),
    billing_period: z.array(BillingPeriod$zodSchema).optional(),
    customer_id: z.string().optional(),
    end_time: z.string().optional(),
    expand: z.string().optional(),
    external_customer_id: z.string().optional(),
    filters: z.array(FilterCondition$zodSchema).optional(),
    invoicing_customer_ids: z.array(z.string()).optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: SubscriptionFilterOrder$zodSchema.optional(),
    parent_subscription_ids: z.array(z.string()).optional(),
    plan_id: z.string().optional(),
    sort: z.array(SortCondition$zodSchema).optional(),
    start_time: z.string().optional(),
    status: Status$zodSchema.optional(),
    subscription_ids: z.array(z.string()).optional(),
    subscription_status: z.array(SubscriptionStatus$zodSchema).optional(),
    with_line_items: z.boolean().optional(),
  });
