/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TaskType = {
  Import: "IMPORT",
  Export: "EXPORT",
} as const;
export type TaskType = ClosedEnum<typeof TaskType>;

export const TaskType$zodSchema = z.enum([
  "IMPORT",
  "EXPORT",
]);
