/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TimeRangeFilter = {
  end_time?: string | undefined;
  start_time?: string | undefined;
};

export const TimeRangeFilter$zodSchema: z.ZodType<TimeRangeFilter> = z.object({
  end_time: z.string().optional(),
  start_time: z.string().optional(),
});
