/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesWalletAlertThreshold,
  TypesWalletAlertThreshold$zodSchema,
} from "./typeswalletalertthreshold.js";

export type TypesAlertConfig = {
  threshold?: TypesWalletAlertThreshold | undefined;
};

export const TypesAlertConfig$zodSchema: z.ZodType<TypesAlertConfig> = z.object(
  {
    threshold: TypesWalletAlertThreshold$zodSchema.optional(),
  },
);
