/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSecretProvider,
  TypesSecretProvider$zodSchema,
} from "./typessecretprovider.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export const TypesConnectionFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesConnectionFilterOrder = ClosedEnum<
  typeof TypesConnectionFilterOrder
>;

export const TypesConnectionFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesConnectionFilter = {
  connection_ids?: Array<string> | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesConnectionFilterOrder | undefined;
  provider_type?: TypesSecretProvider | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  start_time?: string | undefined;
  status?: TypesStatus | undefined;
};

export const TypesConnectionFilter$zodSchema: z.ZodType<TypesConnectionFilter> =
  z.object({
    connection_ids: z.array(z.string()).optional(),
    end_time: z.string().optional(),
    expand: z.string().optional(),
    filters: z.array(TypesFilterCondition$zodSchema).optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: TypesConnectionFilterOrder$zodSchema.optional(),
    provider_type: TypesSecretProvider$zodSchema.optional(),
    sort: z.array(TypesSortCondition$zodSchema).optional(),
    start_time: z.string().optional(),
    status: TypesStatus$zodSchema.optional(),
  });
