/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesEntitySyncConfig = {
  inbound?: boolean | undefined;
  outbound?: boolean | undefined;
};

export const TypesEntitySyncConfig$zodSchema: z.ZodType<TypesEntitySyncConfig> =
  z.object({
    inbound: z.boolean().optional(),
    outbound: z.boolean().optional(),
  });
