/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesS3CompressionType,
  TypesS3CompressionType$zodSchema,
} from "./typess3compressiontype.js";
import {
  TypesS3EncryptionType,
  TypesS3EncryptionType$zodSchema,
} from "./typess3encryptiontype.js";

export type TypesS3ExportConfig = {
  bucket?: string | undefined;
  compression?: TypesS3CompressionType | undefined;
  encryption?: TypesS3EncryptionType | undefined;
  is_flexprice_managed?: boolean | undefined;
  key_prefix?: string | undefined;
  region?: string | undefined;
};

export const TypesS3ExportConfig$zodSchema: z.ZodType<TypesS3ExportConfig> = z
  .object({
    bucket: z.string().optional(),
    compression: TypesS3CompressionType$zodSchema.optional(),
    encryption: TypesS3EncryptionType$zodSchema.optional(),
    is_flexprice_managed: z.boolean().optional(),
    key_prefix: z.string().optional(),
    region: z.string().optional(),
  });
