/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesNomodConnectionMetadata = {
  api_key?: string | undefined;
  webhook_secret?: string | undefined;
};

export const TypesNomodConnectionMetadata$zodSchema: z.ZodType<
  TypesNomodConnectionMetadata
> = z.object({
  api_key: z.string().optional(),
  webhook_secret: z.string().optional(),
});
