/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesConnectionSettings = {
  invoice_sync_enable?: boolean | undefined;
};

export const TypesConnectionSettings$zodSchema: z.ZodType<
  TypesConnectionSettings
> = z.object({
  invoice_sync_enable: z.boolean().optional(),
});
