/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesS3ConnectionMetadata = {
  aws_access_key_id?: string | undefined;
  aws_secret_access_key?: string | undefined;
  aws_session_token?: string | undefined;
};

export const TypesS3ConnectionMetadata$zodSchema: z.ZodType<
  TypesS3ConnectionMetadata
> = z.object({
  aws_access_key_id: z.string().optional(),
  aws_secret_access_key: z.string().optional(),
  aws_session_token: z.string().optional(),
});
