/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesChargebeeConnectionMetadata,
  TypesChargebeeConnectionMetadata$zodSchema,
} from "./typeschargebeeconnectionmetadata.js";
import {
  TypesConnectionSettings,
  TypesConnectionSettings$zodSchema,
} from "./typesconnectionsettings.js";
import {
  TypesGenericConnectionMetadata,
  TypesGenericConnectionMetadata$zodSchema,
} from "./typesgenericconnectionmetadata.js";
import {
  TypesHubSpotConnectionMetadata,
  TypesHubSpotConnectionMetadata$zodSchema,
} from "./typeshubspotconnectionmetadata.js";
import {
  TypesNomodConnectionMetadata,
  TypesNomodConnectionMetadata$zodSchema,
} from "./typesnomodconnectionmetadata.js";
import {
  TypesQuickBooksConnectionMetadata,
  TypesQuickBooksConnectionMetadata$zodSchema,
} from "./typesquickbooksconnectionmetadata.js";
import {
  TypesRazorpayConnectionMetadata,
  TypesRazorpayConnectionMetadata$zodSchema,
} from "./typesrazorpayconnectionmetadata.js";
import {
  TypesS3ConnectionMetadata,
  TypesS3ConnectionMetadata$zodSchema,
} from "./typess3connectionmetadata.js";
import {
  TypesStripeConnectionMetadata,
  TypesStripeConnectionMetadata$zodSchema,
} from "./typesstripeconnectionmetadata.js";

export type TypesConnectionMetadata = {
  chargebee?: TypesChargebeeConnectionMetadata | undefined;
  generic?: TypesGenericConnectionMetadata | undefined;
  hubspot?: TypesHubSpotConnectionMetadata | undefined;
  nomod?: TypesNomodConnectionMetadata | undefined;
  quickbooks?: TypesQuickBooksConnectionMetadata | undefined;
  razorpay?: TypesRazorpayConnectionMetadata | undefined;
  s3?: TypesS3ConnectionMetadata | undefined;
  settings?: TypesConnectionSettings | undefined;
  stripe?: TypesStripeConnectionMetadata | undefined;
};

export const TypesConnectionMetadata$zodSchema: z.ZodType<
  TypesConnectionMetadata
> = z.object({
  chargebee: TypesChargebeeConnectionMetadata$zodSchema.optional(),
  generic: TypesGenericConnectionMetadata$zodSchema.optional(),
  hubspot: TypesHubSpotConnectionMetadata$zodSchema.optional(),
  nomod: TypesNomodConnectionMetadata$zodSchema.optional(),
  quickbooks: TypesQuickBooksConnectionMetadata$zodSchema.optional(),
  razorpay: TypesRazorpayConnectionMetadata$zodSchema.optional(),
  s3: TypesS3ConnectionMetadata$zodSchema.optional(),
  settings: TypesConnectionSettings$zodSchema.optional(),
  stripe: TypesStripeConnectionMetadata$zodSchema.optional(),
});
