/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export type TypesFilter = {
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  sort?: string | undefined;
  status?: TypesStatus | undefined;
};

export const TypesFilter$zodSchema: z.ZodType<TypesFilter> = z.object({
  expand: z.string().optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: z.string().optional(),
  sort: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
});
