/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesAlertThresholdType,
  TypesAlertThresholdType$zodSchema,
} from "./typesalertthresholdtype.js";

export type TypesWalletAlertThreshold = {
  type?: TypesAlertThresholdType | undefined;
  value?: number | undefined;
};

export const TypesWalletAlertThreshold$zodSchema: z.ZodType<
  TypesWalletAlertThreshold
> = z.object({
  type: TypesAlertThresholdType$zodSchema.optional(),
  value: z.number().optional(),
});
