/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesGenericConnectionMetadata = {
  data?: { [k: string]: any } | undefined;
};

export const TypesGenericConnectionMetadata$zodSchema: z.ZodType<
  TypesGenericConnectionMetadata
> = z.object({
  data: z.record(z.string(), z.any()).optional(),
});
