/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesQuickBooksConnectionMetadata = {
  access_token?: string | undefined;
  auth_code?: string | undefined;
  client_id?: string | undefined;
  client_secret?: string | undefined;
  environment?: string | undefined;
  income_account_id?: string | undefined;
  oauth_session_data?: string | undefined;
  realm_id?: string | undefined;
  redirect_uri?: string | undefined;
  refresh_token?: string | undefined;
  webhook_verifier_token?: string | undefined;
};

export const TypesQuickBooksConnectionMetadata$zodSchema: z.ZodType<
  TypesQuickBooksConnectionMetadata
> = z.object({
  access_token: z.string().optional(),
  auth_code: z.string().optional(),
  client_id: z.string().optional(),
  client_secret: z.string().optional(),
  environment: z.string().optional(),
  income_account_id: z.string().optional(),
  oauth_session_data: z.string().optional(),
  realm_id: z.string().optional(),
  redirect_uri: z.string().optional(),
  refresh_token: z.string().optional(),
  webhook_verifier_token: z.string().optional(),
});
