/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesRazorpayConnectionMetadata = {
  key_id?: string | undefined;
  secret_key?: string | undefined;
  webhook_secret?: string | undefined;
};

export const TypesRazorpayConnectionMetadata$zodSchema: z.ZodType<
  TypesRazorpayConnectionMetadata
> = z.object({
  key_id: z.string().optional(),
  secret_key: z.string().optional(),
  webhook_secret: z.string().optional(),
});
