/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSubscriptionLineItemResponse,
  DtoSubscriptionLineItemResponse$zodSchema,
} from "./dtosubscriptionlineitemresponse.js";
import {
  DtoUpdateSubscriptionLineItemRequest,
  DtoUpdateSubscriptionLineItemRequest$zodSchema,
} from "./dtoupdatesubscriptionlineitemrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type UpdateSubscriptionLineItemRequest = {
  id: string;
  body: DtoUpdateSubscriptionLineItemRequest;
};

export const UpdateSubscriptionLineItemRequest$zodSchema: z.ZodType<
  UpdateSubscriptionLineItemRequest
> = z.object({
  body: DtoUpdateSubscriptionLineItemRequest$zodSchema.describe(
    "Update Line Item Request",
  ),
  id: z.string().describe("Line Item ID"),
});

export type UpdateSubscriptionLineItemResponse =
  | DtoSubscriptionLineItemResponse
  | ErrorsErrorResponse;

export const UpdateSubscriptionLineItemResponse$zodSchema: z.ZodType<
  UpdateSubscriptionLineItemResponse
> = z.union([
  DtoSubscriptionLineItemResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
