/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";
import {
  TransactionReason,
  TransactionReason$zodSchema,
} from "./transactionreason.js";
import {
  TransactionStatus,
  TransactionStatus$zodSchema,
} from "./transactionstatus.js";
import {
  TransactionType,
  TransactionType$zodSchema,
} from "./transactiontype.js";

export const WalletTransactionFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type WalletTransactionFilterOrder = ClosedEnum<
  typeof WalletTransactionFilterOrder
>;

export const WalletTransactionFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type WalletTransactionFilter = {
  created_by?: string | undefined;
  credits_available_gt?: number | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  expiry_date_after?: string | undefined;
  expiry_date_before?: string | undefined;
  filters?: Array<FilterCondition> | undefined;
  id?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: WalletTransactionFilterOrder | undefined;
  priority?: number | undefined;
  reference_id?: string | undefined;
  reference_type?: string | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
  transaction_reason?: TransactionReason | undefined;
  transaction_status?: TransactionStatus | undefined;
  type?: TransactionType | undefined;
};

export const WalletTransactionFilter$zodSchema: z.ZodType<
  WalletTransactionFilter
> = z.object({
  created_by: z.string().optional(),
  credits_available_gt: z.number().optional(),
  end_time: z.string().optional(),
  expand: z.string().optional(),
  expiry_date_after: z.string().optional(),
  expiry_date_before: z.string().optional(),
  filters: z.array(FilterCondition$zodSchema).optional(),
  id: z.string().optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: WalletTransactionFilterOrder$zodSchema.optional(),
  priority: z.int().optional(),
  reference_id: z.string().optional(),
  reference_type: z.string().optional(),
  sort: z.array(SortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: Status$zodSchema.optional(),
  transaction_reason: TransactionReason$zodSchema.optional(),
  transaction_status: TransactionStatus$zodSchema.optional(),
  type: TransactionType$zodSchema.optional(),
});
