/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  WalletConfigPriceType,
  WalletConfigPriceType$zodSchema,
} from "./walletconfigpricetype.js";

export type WalletConfig = {
  allowed_price_types?: Array<WalletConfigPriceType> | undefined;
};

export const WalletConfig$zodSchema: z.ZodType<WalletConfig> = z.object({
  allowed_price_types: z.array(WalletConfigPriceType$zodSchema).optional(),
});
