/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";

export const WorkflowExecutionFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type WorkflowExecutionFilterOrder = ClosedEnum<
  typeof WorkflowExecutionFilterOrder
>;

export const WorkflowExecutionFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type WorkflowExecutionFilter = {
  end_time?: string | undefined;
  entity?: string | undefined;
  entity_id?: string | undefined;
  expand?: string | undefined;
  filters?: Array<FilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: WorkflowExecutionFilterOrder | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
  task_queue?: string | undefined;
  workflow_id?: string | undefined;
  workflow_status?: string | undefined;
  workflow_type?: string | undefined;
};

export const WorkflowExecutionFilter$zodSchema: z.ZodType<
  WorkflowExecutionFilter
> = z.object({
  end_time: z.string().optional(),
  entity: z.string().optional(),
  entity_id: z.string().optional(),
  expand: z.string().optional(),
  filters: z.array(FilterCondition$zodSchema).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: WorkflowExecutionFilterOrder$zodSchema.optional(),
  sort: z.array(SortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: Status$zodSchema.optional(),
  task_queue: z.string().optional(),
  workflow_id: z.string().optional(),
  workflow_status: z.string().optional(),
  workflow_type: z.string().optional(),
});
